(function(g){var window=this;'use strict';var ZG=function(M){M.publish("cardstatechange",M.bA()&&M.kW()?1:0)},aD=function(M,U){var N=g.pt(U),m=N?U:arguments;
for(N=N?0:1;N<m.length;N++){if(M==null)return;M=M[m[N]]}return M},Z$H=function(M){var U=g.$Y(M);
M=g.VA(M);return new g.jG(U.x,U.y,M.width,M.height)},a2Q=function(M,U,N){var m;
return m=g.z3(M,U,function(){g.nJ(m);N.apply(M,arguments)},{})},q3=function(M){M=g.Fc(M);
delete Fj[M];g.JH(Fj)&&BD&&BD.stop()},Be7=function(){BD||(BD=new g.Fy(function(){FVF()},20));
var M=BD;M.isActive()||M.start()},FVF=function(){var M=g.zA();
g.Tn(Fj,function(U){qma(U,M)});
g.JH(Fj)||Be7()},DG=function(M,U,N,m){g.Hk.call(this);
if(!Array.isArray(M)||!Array.isArray(U))throw Error("Start and end parameters must be arrays");if(M.length!=U.length)throw Error("Start and end points must be the same length");this.K=M;this.V=U;this.duration=N;this.B=m;this.coords=[];this.progress=this.A=0;this.S=null},qma=function(M,U){U<M.startTime&&(M.endTime=U+M.endTime-M.startTime,M.startTime=U);
M.progress=(U-M.startTime)/(M.endTime-M.startTime);M.progress>1&&(M.progress=1);M.A=1E3/(U-M.S);M.S=U;D1i(M,M.progress);M.progress==1?(M.Z=0,q3(M),M.onFinish(),M.Pm()):M.isPlaying()&&M.K5()},D1i=function(M,U){typeof M.B==="function"&&(U=M.B(U));
M.coords=Array(M.K.length);for(let N=0;N<M.K.length;N++)M.coords[N]=(M.V[N]-M.K[N])*U+M.K[N]},zZa=function(M,U){g.Tf.call(this,M);
this.coords=U.coords;this.x=U.coords[0];this.y=U.coords[1];this.z=U.coords[2];this.duration=U.duration;this.progress=U.progress;this.fps=U.A;this.state=U.Z},zX=function(M,U,N,m,O){DG.call(this,U,N,m,O);
this.element=M},nH=function(M,U,N,m,O){if(U.length!=2||N.length!=2)throw Error("Start and end points must be 2D");
zX.call(this,M,U,N,m,O)},nEO=function(M){return Math.pow(M,3)},hZG=function(M){return 3*M*M-2*M*M*M},h4=function(M){return M.baseUrl||null},GX=function(M,U){return g.Xc(g.ug(M,U),N=>!!N)},GT7=function(M,U,N){function m(Kt){var sJ=Kt.hovercardButton;
if(!sJ)return null;sJ=sJ.subscribeButtonRenderer;if(!sJ)return null;var d0=v(sJ.unsubscribedButtonText),n7=v(sJ.subscribedButtonText);if(sJ.subscribed){var nt=v(sJ.subscriberCountWithUnsubscribeText);var Gs=v(sJ.subscriberCountText)}else nt=v(sJ.subscriberCountText),Gs=v(sJ.subscriberCountWithSubscribeText);var uJ=null;return Kt.signinEndpoint&&((uJ=aD(Kt,"signinEndpoint","webNavigationEndpointData","url"))||(uJ=g.X(sJ.signInEndpoint?.commandMetadata,g.a0)?.url),!uJ)?null:d0&&(n7||uJ)?{subscribed:sJ.subscribed,
subscribeText:d0,subscribeCount:nt,unsubscribeText:n7,unsubscribeCount:Gs,enabled:sJ.enabled,signinUrl:uJ,classic:Kt.useClassicSubscribeButton}:null}
function O(Kt){if(Kt){var sJ=[],d0=Kt.videoId;d0&&sJ.push("v="+d0);(d0=Kt.playlistId)&&sJ.push("list="+d0);(Kt=Kt.startTimeSeconds)&&sJ.push("t="+Kt);return"/watch?"+sJ.join("&")}}
function v(Kt){if(!Kt)return null;var sJ=Kt.simpleText;return sJ?sJ:Kt.runs?g.ug(Kt.runs,d0=>d0.text).join(""):null}
U=U.endscreenElementRenderer;if(!U)return null;var Y=U.style,w=U.endpoint||{},l=null,c=null,S=!1,y=null,E=null,L=null,C=null,q=!1,r=null,k=null,Q=null,b=null,I=null,MO=null;if(Y==="VIDEO")g.X(w,g.m$)?l=g.X(w,g.m$).url:(MO=g.X(w,g.j8),l=O(MO)),c=!1,y=M,U.thumbnailOverlays?(S=U.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,E=v(S.text),S=S.style==="LIVE"):E=v(U.videoDuration);else if(Y==="PLAYLIST")g.X(w,g.m$)?l=g.X(w,g.m$).url:(MO=g.X(w,g.j8),l=O(MO)),c=!1,y=M,L=v(U.playlistLength);else if(Y===
"CHANNEL"){if(q=aD(w,"browseEndpoint","browseId"))C=q,l=`/channel/${C}`;c=!1;y="new";(q=!!U.isSubscribe)?r=m(U):k=v(U.subscribersText)}else Y==="WEBSITE"?((Q=aD(w,"urlEndpoint","url"))&&(l=Q),c=!0,y="new",Q=U.icon.thumbnails[0].url):Y==="CREATOR_MERCHANDISE"&&(U.productPrice&&(b=v(U.productPrice)),U.additionalFeesText&&(I=v(U.additionalFeesText)),(c=aD(w,"urlEndpoint","url"))&&(l=c),c=!0,y="new");M=aD(U,"title","accessibility","accessibilityData","label");var e9=U.endpoint?U.endpoint.clickTrackingParams:
null,D3="";if(U.metadata){let Kt=v(U.metadata);Kt&&(D3=Kt)}return{id:`element-${N}`,type:Y,title:v(U.title),metadata:D3,callToAction:v(U.callToAction),CE:U.image,iconUrl:Q,left:Number(U.left),width:Number(U.width),top:Number(U.top),aspectRatio:Number(U.aspectRatio),startMs:Math.floor(Number(U.startMs)),endMs:Math.floor(Number(U.endMs)),videoDuration:E,yk:S,playlistLength:L,channelId:C,subscribeButton:r,subscribersText:k,isSubscribe:q,targetUrl:l||null,Xd:c,sessionData:e9?{itct:e9}:null,DT:y,Kp:M?
M:null,isPlaceholder:U.isPlaceholder,impressionUrls:GX(U.impressionUrls||[],h4),VS:GX(U.hovercardShowUrls||[],h4),clickUrls:GX(w.loggingUrls||[],h4),visualElement:g.us(U.trackingParams),productPrice:b,additionalFeesText:I,watchEndpoint:MO||null}},jx=function(M,U){var N={startMs:Math.floor(Number(M.startMs)),
impressionUrls:GX(M.impressionUrls||[],h4),elements:GX(M.elements||[],(m,O)=>GT7(U,m,O))};
M.trackingParams&&(N.visualElement=g.us(M.trackingParams));return N},rA=function(M){return M.player.J().playerStyle==="creator-endscreen-editor"},ju7=function(M){return M.player.getVideoData().nP?"current":M.Y?"new":"current"},KH=function(M,U,N=!0){M.player.sa("creatorendscreen");
M.O&&(M.O.dispose(),M.O=null,M.B.dispose(),M.B=null);for(var m of Object.values(M.K))m.dispose();M.K={};M.A={};M.D.length>0&&(M.D.forEach(O=>{O.dispose()}),M.D.length=0);
M.Z&&(g.Tu(M.Z,"ytp-ce-element-show"),M.Z.setAttribute("aria-hidden","true"));M.V=0;if((M.endscreen=U)&&U.elements){N&&Ten(M);N=[];m=new g.OH(U.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});N.push(m);M.player.J().O||(M.O=new g.d({W:"div",N:"ytp-ce-shadow"}),g.tE(M.player,M.O.element,4),M.B=new g.sQ(M.O,200));for(m=0;m<U.elements.length;++m){let O=U.elements[m],v=rW7(M,O);if(!v){g.tC(new g.LQ("buildEndscreenElement null",O));continue}M.K[O.id]=v;M.A[O.id]=O;g.tE(M.player,
v.element,4);let Y=new g.OH(O.startMs,O.endMs,{id:"ytp-ce-element-"+O.id,namespace:"creatorendscreen"});N.push(Y);KVa(M,v,O)}M.player.ek(N);M.eb()}},H$u=function(M){var U=M.player.getVideoData(),N=U.videoId;
M.S&&M.S.abort();N={method:"POST",onFinish:O=>{var v=M.S=null;O.status===200&&(O=O.responseText,O.substring(0,3)===")]}"&&(O=O.substring(3),v=JSON.parse(O),v=jx(v,ju7(M))));KH(M,v)},
urlParams:{v:N},withCredentials:!0};M.Y&&(N.urlParams.ptype="embedded");var m=U.Xl;m&&(N.postParams={ad_tracking:m});if(U=g.ne0(U))if(U=g.XF(U),U=g.k_(U))M.S=g.hn(U,N)},Ten=function(M){var U=g.$Z(),N=g.is();
N&&U&&M.endscreen.visualElement&&g.YA(g.e0)(void 0,N,U,M.endscreen.visualElement)},rW7=function(M,U){var N=null;
switch(U.type){case "VIDEO":M={W:"div",aS:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":U.Kp||"","aria-hidden":"true"},X:[{W:"div",N:"ytp-ce-element-shadow"},{W:"div",N:"ytp-ce-covering-image",L:HD(U)},{W:"div",N:"ytp-ce-covering-shadow-top"},{W:"a",N:"ytp-ce-covering-overlay",L:{href:kn(M,U.targetUrl),tabindex:"-1"},X:[{W:"div",aS:["ytp-ce-video-title","ytp-webkit-ellipsis"],L:{dir:g.Xy(U.title||"")},Hv:U.title},{W:"div",N:U.yk?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Hv:U.videoDuration||void 0}]}]};N=new g.d(M);break;case "PLAYLIST":M={W:"div",aS:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":U.Kp||"","aria-hidden":"true"},X:[{W:"div",N:"ytp-ce-element-shadow"},{W:"div",N:"ytp-ce-covering-image",L:HD(U)},{W:"div",N:"ytp-ce-covering-shadow-top"},{W:"a",N:"ytp-ce-covering-overlay",L:{href:kn(M,U.targetUrl),tabindex:"-1"},X:[{W:"div",aS:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],L:{dir:g.Xy(U.title||"")},Hv:U.title},{W:"div",N:"ytp-ce-playlist-count",
X:[{W:"div",N:"ytp-ce-playlist-icon"},{W:"div",N:"ytp-ce-playlist-count-text",Hv:U.playlistLength||void 0}]}]}]};N=new g.d(M);break;case "CHANNEL":N={W:"div",aS:["ytp-ce-element","ytp-ce-channel",U.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":U.Kp||"","aria-hidden":"true"},X:[{W:"div",N:"ytp-ce-element-shadow"},{W:"div",N:"ytp-ce-expanding-overlay",X:[{W:"div",N:"ytp-ce-expanding-overlay-hider"},{W:"div",N:"ytp-ce-expanding-overlay-background"},{W:"div",N:"ytp-ce-expanding-overlay-content",
X:[{W:"div",N:"ytp-ce-expanding-overlay-body",X:[{W:"div",N:"ytp-ce-expanding-overlay-body-padding",X:[{W:"a",aS:["ytp-ce-channel-title","ytp-ce-link"],L:{href:kn(M,U.targetUrl),target:"_blank",tabindex:"-1",dir:g.Xy(U.title||"")},Hv:U.title},U.subscribeButton?{W:"div",N:"ytp-ce-subscribe-container",X:[{W:"div",N:"ytp-ce-channel-subscribe"}]}:"",U.subscribersText?{W:"div",N:"ytp-ce-channel-subscribers-text",L:U.Kp?{"aria-hidden":"true"}:{},Hv:U.subscribersText}:"",U.metadata?{W:"div",aS:["ytp-ce-channel-metadata",
"yt-ui-ellipsis","yt-ui-ellipsis-3"],Hv:U.metadata}:""]}]}]}]},{W:"div",N:"ytp-ce-expanding-image",L:HD(U)}]};N=new g.d(N);let O=g.tY(document,"div","ytp-ce-channel-subscribe",N.element)[0];if(U.subscribeButton&&U.channelId){g.Gu(O,"ytp-ce-subscribe-button");let v;if(M.player.J().O){var m=null;v=U.sessionData.itct}else m="endscreen",v=null;m=new g.IL(U.subscribeButton.subscribeText,U.subscribeButton.subscribeCount,U.subscribeButton.unsubscribeText,U.subscribeButton.unsubscribeCount,!!U.subscribeButton.enabled,
!!U.subscribeButton.classic,U.channelId,!!U.subscribeButton.subscribed,m,v,M.player,!1);O.appendChild(m.element);M.D.push(m)}break;case "WEBSITE":M={W:"div",aS:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":U.Kp||"","aria-hidden":"true"},X:[{W:"div",N:"ytp-ce-element-shadow"},{W:"div",N:"ytp-ce-expanding-overlay",X:[{W:"div",N:"ytp-ce-expanding-overlay-hider"},{W:"div",N:"ytp-ce-expanding-overlay-background"},{W:"div",N:"ytp-ce-expanding-overlay-content",X:[{W:"div",N:"ytp-ce-expanding-overlay-body",
X:[{W:"div",N:"ytp-ce-expanding-overlay-body-padding",X:[{W:"div",N:"ytp-ce-website-title",L:{dir:g.Xy(U.title||"")},Hv:U.title},{W:"div",N:"ytp-ce-website-metadata",Hv:U.metadata},{W:"a",aS:["ytp-ce-website-goto","ytp-ce-link"],L:{href:kn(M,U.targetUrl),target:"_blank",tabindex:"-1"},Hv:U.callToAction}]}]}]}]},{W:"div",N:"ytp-ce-expanding-image",L:HD(U)},{W:"div",N:"ytp-ce-expanding-icon",L:kTn(U.iconUrl)}]};N=new g.d(M);break;case "CREATOR_MERCHANDISE":N="",U.productPrice&&(N={W:"div",N:"ytp-ce-merchandise-price-container",
X:[{W:"div",N:"ytp-ce-merchandise-price",Hv:U.productPrice}]},U.additionalFeesText&&N.X.push({W:"div",N:"ytp-ce-merchandise-additional-fees",Hv:U.additionalFeesText})),M={W:"div",aS:["ytp-ce-element","ytp-ce-merchandise"],L:{tabindex:"0","aria-label":U.Kp||"","aria-hidden":"true"},X:[{W:"div",N:"ytp-ce-element-shadow"},{W:"div",N:"ytp-ce-expanding-overlay",X:[{W:"div",N:"ytp-ce-expanding-overlay-hider"},{W:"div",N:"ytp-ce-expanding-overlay-background"},{W:"div",N:"ytp-ce-expanding-overlay-content",
X:[{W:"div",N:"ytp-ce-expanding-overlay-body",X:[{W:"div",N:"ytp-ce-expanding-overlay-body-padding",X:[{W:"div",N:"ytp-ce-merchandise-title",L:{dir:g.Xy(U.title||"")},Hv:U.title},N,{W:"div",N:"ytp-ce-merchandise-metadata",Hv:U.metadata},{W:"a",aS:["ytp-ce-merchandise-goto","ytp-ce-link"],L:{href:kn(M,U.targetUrl),target:"_blank",tabindex:"-1"},Hv:U.callToAction}]}]}]}]},{W:"div",N:"ytp-ce-expanding-image",L:HD(U)},{W:"div",N:"ytp-ce-merchandise-invideo-cta-container",X:[{W:"div",N:"ytp-ce-merchandise-invideo-cta",
Hv:U.callToAction||void 0}]}]},N=new g.d(M)}U.isPlaceholder&&g.Gu(N.element,"ytp-ce-placeholder");return N},KVa=function(M,U,N){function m(){Y(1)}
function O(){Y(-1)}
U.listen("mouseenter",()=>{xn(M,U,N)});
U.listen("mouseleave",()=>{Qr(M,U,N)});
M.player.J().O||U.listen("click",()=>{g.Gu(U.element,"ytp-ce-element-hover")});
U.listen("click",w=>{x1F(M,N,w)});
U.listen("keypress",w=>{x1F(M,N,w)});
U.listen("focus",()=>{xn(M,U,N)});
U.listen("blur",()=>{Qr(M,U,N)});
U.listen("touchstart",()=>{xn(M,U,N)});
var v=g.Rw("ytp-ce-expanding-overlay-hider",U.element);v&&U.U(v,"touchstart",w=>{w.stopPropagation();g.Tu(U.element,"ytp-ce-element-hover");g.Tu(U.element,"ytp-ce-force-expand")});
U.listen("keydown",w=>{M.OM=w.keyCode===9&&!w.shiftKey});
var Y=w=>{M.V+=w;M.V>0?(g.Gu(U.element,"ytp-ce-force-expand"),bA(M,N.id,!0)):(g.Tu(U.element,"ytp-ce-force-expand"),g.Tu(U.element,"ytp-ce-element-hover"),bA(M,N.id,!1))};
v=w=>{w&&(U.listen("blur",()=>{w.style.display!="none"&&M.OM&&w.focus()}),U.U(w,"focus",m),U.U(w,"blur",O))};
v(g.Rw("ytp-sb-subscribe",U.element));v(g.Rw("ytp-sb-unsubscribe",U.element));U.listen("focus",m);U.listen("blur",O)},Xj=function(M,U,N){function m(){v||(O++,O===U.length&&(Y.stop(),N&&N()))}
if(!U||U.length===0||rA(M))N&&N();else{U=Qua(M,U);var O=0,v=!1,Y=new g.Fy(()=>{v=!0;N&&N()},1E3,M);
Y.start();for(M=0;M<U.length;M++)g.E0(U[M],m)}},HD=function(M){if(M.CE)var U=M.CE.thumbnails;
return kTn(U?U[U.length-1].url:null)},kn=function(M,U){M=M.player.J();
if(U){if(U.startsWith("//"))return M.protocol+":"+U;if(U.startsWith("/"))return g.KZ(M)+U}else return"";return U},kTn=function(M){return M?{style:"background-image: url("+M+")"}:{}},xn=function(M,U,N){g.h1(U.element,"ytp-ce-element-hover")||(N.type==="VIDEO"||N.type==="PLAYLIST"?g.Gu(U.element,"ytp-ce-element-hover"):M.player.J().O?(new g.Fy(()=>{g.Gu(U.element,"ytp-ce-element-hover")},200)).start():g.Gu(U.element,"ytp-ce-element-hover"),Xj(M,N.VS),bA(M,N.id,!0))},Qr=function(M,U,N){g.Tu(U.element,
"ytp-ce-element-hover");
g.Tu(U.element,"ytp-ce-force-expand");bA(M,N.id,!1)},x1F=function(M,U,N){if(U.targetUrl&&(!N||N.type!=="keypress"||N.keyCode===13)){for(var m=N.target;m&&!g.h1(m,"ytp-ce-element");){g.h1(m,"subscribe-label")&&uA(M,U);
if(g.h1(m,"ytp-ce-channel-subscribe"))return;m=m.parentElement||null}if(!m||g.h1(m,"ytp-ce-element-hover")){N.preventDefault();N.stopPropagation();if(m=M.K[U.id])Qr(M,m,U),m.element.blur();if(N.ctrlKey||N.metaKey||U.DT==="new")uA(M,U),M.player.sendVideoStatsEngageEvent(17,void 0),M.player.pauseVideo(),N=g.XF(kn(M,U.targetUrl)),N=g.k_(N),g.B0(N,void 0,U.sessionData);else{let O=g.qN(M.player.J())||M.player.getVideoData().nP,v=()=>{var Y=kn(M,U.targetUrl),w=U.sessionData,l=U.watchEndpoint,c=g.yD(Y);
O&&c&&(c.v||c.list)?M.player.UE(c.v,w,c.list,!1,void 0,l||void 0):g.FM(Y,w)};
uA(M,U,()=>{M.player.sendVideoStatsEngageEvent(17,v)})}}}},bA=function(M,U,N){M.O&&(N?M.B.show():M.B.hide());
for(let m of Object.keys(M.K))m!==U&&g.KO(M.K[m].element,"ytp-ce-element-shadow-show",N)},uA=function(M,U,N){Xj(M,U.clickUrls,N);
(M=g.is())&&U.Xd&&g.Df(M,U.visualElement)},Qua=function(M,U){var N=M.player.getVideoData().clientPlaybackNonce;
M=M.player.getCurrentTime().toFixed(2);N={CPN:N,AD_CPN:N,MT:M};M=[];for(let m=0;m<U.length;m++)M.push(b$J(U[m],N));return M},b$J=function(M,U){return M.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,N=>{var m=unescape(N);
m=m.substring(1,m.length-1);return U[m]?escape(U[m]):N})},XGF=function(M){return typeof M==="string"?M:""},ID=function(M,U,N){for(let m in U)if(U[m]===M)return M;
return N},s9=function(M){if(!M)return null;
var U=g.XF(XGF(M.value));U=g.k_(U);if(!U)return null;var N=ID(M.target,uia,"current");if(N==null)M=null;else{var m=M.show_link_icon;M=new I2J(U,N,m==="true"||m==="false"?m==="true":!0,M.pause_on_navigation!=null?M.pause_on_navigation:!0)}return M},JW4=function(M){if(!M)return null;
var U=ID(M.type,suJ),N=ID(M.trigger,$1J);M=M.url;M=Array.isArray(M)&&M.length?M[0]:M;M=s9(M?M:null);return U?new i$7(U,N,M):null},tDN=function(M,U){return g.R6(M.action,U)},$n=function(M,U){M="background-image: url("+M+");";
var N=[];U&&N.push(U);return{W:"div",N:"iv-card-image",L:{style:M},X:N}},J4=function(M){return M.customMessage?iA("div","iv-card-message",M.customMessage):""},t4=function(M){if(!M.metaInfo||M.metaInfo.length===0)return"";
var U=[];for(let N of M.metaInfo)U.push(iA("li","",N));return{W:"ul",N:"iv-card-meta-info",X:U}},RD=function(M,U,N,m){if(m)for(let O of U)M.Z(O,m,N.id,N.sessionData,N.W8.click,5)},iA=function(M,U,N){U?typeof U==="string"?U={"class":U}:Array.isArray(U)&&(U={"class":U.join(" ")}):U={};
U.dir=g.Xy(N);return{W:M,L:U,Hv:N}},RZu=function(M){if(!M.customMessage)return"";
var U=["iv-card-action","iv-card-primary-link"],N={};M.zN&&(U.push("iv-card-action-icon"),N.style="background-image: url("+M.zN+");");N.dir=g.Xy(M.customMessage);var m=[{W:"span",Hv:M.customMessage}];M.showLinkIcon&&(m.push("\u00a0"),m.push({W:"span",N:"iv-card-link-icon"}));return{W:"div",aS:U,L:N,X:m}},f2a=function(M){var U;
(U=M)&&!(U=M.length>1?M.charAt(0)==="/"&&M.charAt(1)!=="/":M==="/")&&(U=M.replace(/^(https?:)?\/\//,"").split("/",1),U=!U||U.length<1||!U[0]?[]:U[0].toLowerCase().split(".").reverse(),U=U[0]==="com"&&U[1]==="youtube"||U[0]==="be"&&U[1]==="youtu");return U?M.indexOf("/redirect?")===-1:!1},d1Q=function(M,U){return U?U:f2a(M)?"current":"new"},fH=function(M,U,N,m,O,v,Y){M.context.Z.listen(U,"click",w=>{M.xf(N,m,O,v||[],Y||0,w)});
M.context.Z.listen(U,"touchstart",()=>{M.po=!1});
M.context.Z.listen(U,"touchmove",()=>{M.po=!0})},VDN=function(M){if(g.X(M,g.m$)?.url)return g.X(M,g.m$).url;
if((M=g.X(M,g.j8))&&M.videoId){let U="/watch?v="+M.videoId;M.playlistId&&(U+="&list="+M.playlistId);M.index&&(U+="&index="+M.index);M.startTimeSeconds&&(U+="&t="+M.startTimeSeconds);return U}return null},dA=function(M,U,N){return{xY:(M.impressionLoggingUrlsV2s||[]).map(m=>m.baseUrl||""),
click:(N.loggingUrls||[]).map(m=>m.baseUrl||""),
close:(U.dismissLoggingUrlsV2s||[]).map(m=>m.baseUrl||""),
Lc:(U.impressionLoggingUrlsV2s||[]).map(m=>m.baseUrl||""),
Wk:(U.clickLoggingUrlsV2s||[]).map(m=>m.baseUrl||"")}},Uq=function(M,U){if(U.onClickCommand&&g.X(U.onClickCommand,g.zfu)?.targetId==="engagement-panel-error-corrections"){M.ZQ=U;
var N=!0}else N=!1;if(!N||g7j(M,U))if(N=M54(M,U)){var m={AX:U,bj:N.element,Qx:!1};if(U.onClickCommand)M.C.G("web_infocards_teaser_show_logging_fix")&&(M.zb||N$O(M),Vr(M,U.id),N=M.findLastIndex(m),g.cJ(M.cards,N,0,m));else{M.isInitialized||Unu(M);Vr(M,U.id);let O=M.findLastIndex(m);g.cJ(M.cards,O,0,m);N.IS(M.K,O);M.d6()}U.autoOpen?M.addCueRange(U.startMs,0x8000000000000,U.id,()=>{M.O||(M.Z=m,gF(M),mnu(M,m),Ma(M,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(N=M.context.C.getCurrentTime()*1E3,N<5E3&&N>U.startMs&&
OEG(M,m),M.addCueRange(U.startMs,U.startMs+1,U.id,()=>{OEG(M,m)}),gF(M))}},Na=function(M){M.O&&(M.jw.hide(),M.VT.K(),g.Tu(M.context.C.getRootNode(),g.z2.IV_DRAWER_OPEN),M.O=!1,ZG(M.C),M.B&&M.B.stop(),M.B=new g.Fy(()=>{M.sM&&(M.sM.focus(),M.sM=null)},330),M.B.start())},v7F=function(M,U){U=U.data;
U.autoOpenMs&&M.addCueRange(U.autoOpenMs,0x8000000000000,"",()=>{Ma(M,"YOUTUBE_DRAWER_AUTO_OPEN")});
U.autoCloseMs&&M.addCueRange(U.autoCloseMs,0x8000000000000,"",()=>{Na(M)});
var N=U.headerText;g.Ea(M.uZ,N);M.D&&M.D.setAttribute("data-tooltip-title",N);U.eventId&&(M.eventId=U.eventId);M.ML=g.us(U.trackingParams);M.V=g.us(U.closeTrackingParams);M.lH=g.us(U.iconTrackingParams)},mA=function(M,U,N){var m=-1,O=-1;
for(let v=0;v<M.length;v++){if(M[v].height===U||M[v].width===N)return M[v];((M[v].height||0)<U||(M[v].width||0)<N)&&(m<0||(M[m].height||0)<(M[v].height||0)||(M[m].width||0)<(M[v].width||0))?m=v:((M[v].height||0)>=U||(M[v].width||0)>=N)&&(O<0||(M[O].height||0)>(M[v].height||0)||(M[O].width||0)>(M[v].width||0))&&(O=v)}return M[O>=0?O:m]},Oq=function(M,U,N,m){return{feature:N.feature?N.feature:"cards",
src_vid:M.context.videoData.videoId,annotation_id:U,ei:M.context.videoData.eventId||"",itct:m.trackingParams||""}},YSn=function(M,U){var N=U.cardId?U.cardId:`cr:${M.A}`,m=M.C.J().experiments.cv("enable_error_corrections_infocard_web_client");
if(!U.content&&U.teaser.simpleCardTeaserRenderer&&m){m=U.teaser.simpleCardTeaserRenderer;var O=U.icon?U.icon.infoCardIconRenderer:null;if(m.channelAvatar&&m.channelAvatar.thumbnails&&m.channelAvatar.thumbnails.length>0)var v=mA(m.channelAvatar.thumbnails,22,22).url;U={id:N,timestamp:M.A,type:"simple",teaserText:g.Kl(m.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:{},sponsored:!1,W8:{},YW:null,pV:m.trackingParams?
g.us(m.trackingParams):null,lH:O&&O.trackingParams?g.us(O.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,zN:null,title:"",customMessage:"",url:null,onClickCommand:m.onTapCommand||null,lf:v};Uq(M,U)}else if(U.content?.simpleCardContentRenderer){if(!U.cueRanges.length)return;v=U.content?.simpleCardContentRenderer;m=U.teaser.simpleCardTeaserRenderer;O=U.icon?U.icon.infoCardIconRenderer:null;U={id:N,timestamp:M.A,type:"simple",teaserText:g.Kl(m.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),
startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:Oq(M,N,U,v),sponsored:!1,W8:dA(v,m,v.command),YW:v.trackingParams?g.us(v.trackingParams):null,pV:m.trackingParams?g.us(m.trackingParams):null,lH:O&&O.trackingParams?g.us(O.trackingParams):null,imageUrl:mA(v.image.thumbnails,290,290).url,displayDomain:v.displayDomain?g.Kl(v.displayDomain):null,showLinkIcon:!!v.showLinkIcon,zN:null,title:v.title?g.Kl(v.title):"",customMessage:v.callToAction?g.Kl(v.callToAction):"",url:g.X(v.command,
g.m$).url?s9({pause_on_navigation:!M.context.videoData.isLivePlayback,target:"new",value:g.X(v.command,g.m$).url}):null,onClickCommand:null};Uq(M,U)}else if(U.content?.collaboratorInfoCardContentRenderer){if(!U.cueRanges.length)return;v=U.content?.collaboratorInfoCardContentRenderer;m=U.teaser.simpleCardTeaserRenderer;O=U.icon?U.icon.infoCardIconRenderer:null;U={id:N,timestamp:M.A,type:"collaborator",teaserText:g.Kl(m.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),
autoOpen:!!U.autoOpen,sessionData:Oq(M,N,U,v),sponsored:!1,W8:dA(v,m,v.endpoint),YW:v.trackingParams?g.us(v.trackingParams):null,pV:m.trackingParams?g.us(m.trackingParams):null,lH:O&&O.trackingParams?g.us(O.trackingParams):null,channelId:g.X(v.endpoint,g.CW).browseId,customMessage:v.customText?g.Kl(v.customText):null,profileImageUrl:mA(v.channelAvatar.thumbnails,290,290).url,title:v.channelName?g.Kl(v.channelName):"",metaInfo:[v.subscriberCountText?g.Kl(v.subscriberCountText):""],url:s9({pause_on_navigation:!M.context.videoData.isLivePlayback,
target:"new",value:g.X(v.endpoint,g.CW).canonicalBaseUrl?g.X(v.endpoint,g.CW).canonicalBaseUrl:`/channel/${g.X(v.endpoint,g.CW).browseId}`}),onClickCommand:null};Uq(M,U)}else if(U.content?.playlistInfoCardContentRenderer){if(!U.cueRanges.length)return;v=U.content?.playlistInfoCardContentRenderer;m=U.teaser.simpleCardTeaserRenderer;O=U.icon?U.icon.infoCardIconRenderer:null;U={id:N,timestamp:M.A,type:"playlist",teaserText:g.Kl(m.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),
autoOpen:!!U.autoOpen,sessionData:Oq(M,N,U,v),sponsored:!1,W8:dA(v,m,v.action),YW:v.trackingParams?g.us(v.trackingParams):null,pV:m.trackingParams?g.us(m.trackingParams):null,lH:O&&O.trackingParams?g.us(O.trackingParams):null,kg:mA(v.playlistThumbnail.thumbnails,258,290).url,customMessage:v.customMessage?g.Kl(v.customMessage):null,playlistVideoCount:g.Kl(v.playlistVideoCount),title:v.playlistTitle?g.Kl(v.playlistTitle):"",metaInfo:[v.channelName?g.Kl(v.channelName):"",v.videoCountText?g.Kl(v.videoCountText):
""],url:s9({pause_on_navigation:!M.context.videoData.isLivePlayback,target:"new",value:VDN(v.action)}),onClickCommand:null};Uq(M,U)}else if(U.content?.videoInfoCardContentRenderer){if(!U.cueRanges.length)return;v=U.content?.videoInfoCardContentRenderer;m=U.teaser.simpleCardTeaserRenderer;O=U.icon?U.icon.infoCardIconRenderer:null;U={id:N,timestamp:M.A,type:"video",teaserText:g.Kl(m.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,
sessionData:Oq(M,N,U,v),sponsored:!1,W8:dA(v,m,v.action),YW:v.trackingParams?g.us(v.trackingParams):null,pV:m.trackingParams?g.us(m.trackingParams):null,lH:O&&O.trackingParams?g.us(O.trackingParams):null,kg:mA(v.videoThumbnail.thumbnails,258,290).url,videoDuration:v.lengthString?g.Kl(v.lengthString):null,customMessage:v.customMessage?g.Kl(v.customMessage):null,title:v.videoTitle?g.Kl(v.videoTitle):"",metaInfo:[v.channelName?g.Kl(v.channelName):"",v.viewCountText?g.Kl(v.viewCountText):""],isLiveNow:!!v.badge,
url:s9({pause_on_navigation:!M.context.videoData.isLivePlayback,target:"new",value:VDN(v.action)}),onClickCommand:null};Uq(M,U)}M.A++},o7u=function(M,U){return g.R6(M.cards,N=>N.AX.id===U)},gF=function(M){g.KO(M.C.getRootNode(),"ytp-cards-shopping-active",w$n(M))},Vr=function(M,U){if(U=o7u(M,U))U===M.Z&&(M.Z=null),M.C.removeCueRange(U.AX.id),g.SG(U.bj),g.UO(M.cards,U),M.d6(),gF(M)},Ma=function(M,U,N){if(!M.O){M.jw.show();
M.DQ=new g.Fy(()=>{g.Gu(M.context.C.getRootNode(),g.z2.IV_DRAWER_OPEN)},0);
M.DQ.start();M.VT.U(M.K,"mousewheel",O=>{M.Sw.start();O.preventDefault();O=O||window.event;var v=0;O.type=="MozMousePixelScroll"?v=0==(O.axis==O.HORIZONTAL_AXIS)?O.detail:0:window.opera?v=O.detail:v=O.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?O.wheelDeltaY/-30:O.wheelDeltaY/-1.2:O.wheelDelta/-1.6:O.wheelDeltaY/-3;if(O=v)M.K.scrollTop+=O});
M.O=!0;var m=g.is();m&&M.ML&&M.V&&g.Bw(m,[M.ML,M.V]);U={TRIGGER_TYPE:U};for(let O of M.cards)O.Qx||(O.Qx=!0,lkQ(M.context.logger,O.AX.W8.xY,U)),m&&g.Bw(m,[O.AX.YW]);ZG(M.C);N&&(M.B=new g.Fy(()=>{M.sM=M.D;M.EM.focus()},330),M.B.start())}},Unu=function(M){g.j7(M.BV(),[g.z2.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.tE(M.C,M.S,5);M.wa();M.D=g.Rw("ytp-cards-button",M.C.getRootNode());M.EM=g.Rw("iv-drawer-close-button",M.S);M.isInitialized=!0},N$O=function(M){M.OM.push(g.n0("iv-teaser-shown",M.rK,M));
M.OM.push(g.n0("iv-teaser-hidden",M.iZ,M));M.OM.push(g.n0("iv-teaser-clicked",M.Mh,M));M.zb=!0},g7j=function(M,U){M.ZQ=U;
var N=M.C.getVideoData();if(!N)return!1;N=g.lR(N.getWatchNextResponse());if(N?.markersMap)for(let O=0;N?.markersMap.length>O;O++){var m=N?.markersMap[O];if(m.key==="ERROR_CORRECTION_MARKERS"&&(m=m.value?.markers)&&m.length>0)return U.startMs=g.X(m[0],g.wL9)?.timeRangeStartMillis||0,M.ZQ=null,!0}return!1},M54=function(M,U){switch(U.type){case "simple":M=M.u0;
var N=U.displayDomain?{W:"div",N:"iv-card-image-text",Hv:U.displayDomain}:void 0;var m=RZu(U);N={W:"div",aS:["iv-card"],X:[{W:"a",N:"iv-click-target",L:{href:U.url?U.url.Z()||"":""},X:[$n(U.imageUrl,N),{W:"div",N:"iv-card-content",X:[iA("h2",void 0,U.title),m]}]}]};N=new g.d(N);RD(M,g.JY("iv-click-target",N.element),U,U.url);U=N;break;case "collaborator":M=M.u0;N={W:"div",aS:["iv-card","iv-card-channel"],X:[{W:"a",aS:["iv-click-target"],L:{href:U.url.Z()||"","data-ytid":U.channelId},X:[$n(U.profileImageUrl),
{W:"div",N:"iv-card-content",X:[J4(U),{W:"h2",N:"iv-card-primary-link",Hv:U.title},t4(U)]}]}]};N=new g.d(N);RD(M,g.JY("iv-click-target",N.element),U,U.url);U=N;break;case "playlist":M=M.u0;N={W:"div",aS:["iv-card","iv-card-playlist"],X:[{W:"a",N:"iv-click-target",L:{href:U.url.Z()||""},X:[$n(U.kg,{W:"div",N:"iv-card-image-overlay",X:[{W:"span",N:"iv-card-playlist-video-count",Hv:U.playlistVideoCount}]}),{W:"div",N:"iv-card-content",X:[J4(U),iA("h2","iv-card-primary-link",U.title),t4(U)]}]}]};N=new g.d(N);
RD(M,g.JY("iv-click-target",N.element),U,U.url);U=N;break;case "productListing":M=M.u0;var O=U.offers.length!=0;N=["iv-card"];m="";var v=RZu(U);O&&(N.push("iv-card-product-listing"),m="iv-card-primary-link",v=U.offers[0],O=[],v.price&&O.push({W:"div",N:"iv-card-offer-price",Hv:v.price}),v.merchant&&O.push({W:"div",N:"iv-card-offer-merchant",Hv:v.merchant}),v={W:"div",X:O});O=U.url?U.url.Z()||"":"";N={W:"div",aS:N,L:{tabindex:"0"},X:[{W:"a",aS:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+
U.imageUrl+");",href:O,"aria-hidden":"true",tabindex:"-1"}},{W:"div",N:"iv-card-content",X:[U.sponsored?{W:"div",N:"iv-card-sponsored",X:["Sponsored",{W:"div",N:"iv-ad-info-container",X:[{W:"div",N:"iv-ad-info",Hv:"{{adInfo}}"},{W:"div",N:"iv-ad-info-icon-container",X:[{W:"div",N:"iv-ad-info-icon"},{W:"div",N:"iv-ad-info-callout"}]}]}]}:"",{W:"a",N:"iv-click-target",L:{href:O},X:[iA("h2",m,U.title),v]}]}]};N=new g.d(N);m=g.YY("span");g.Ea(m,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
N.setContent(m,"adInfo");RD(M,g.JY("iv-click-target",N.element),U,U.url);U=N;break;case "video":M=M.u0;N=U.isLiveNow?{W:"span",aS:["yt-badge","yt-badge-live"],Hv:"LIVE NOW"}:null;N={W:"div",aS:["iv-card","iv-card-video"],X:[{W:"a",N:"iv-click-target",L:{href:U.url?.Z()||""},X:[$n(U.kg,U.videoDuration?{W:"span",N:"iv-card-video-duration",Hv:U.videoDuration}:void 0),{W:"div",N:"iv-card-content",X:[J4(U),iA("h2","iv-card-primary-link",U.title),t4(U),N]}]}]};N=new g.d(N);RD(M,g.JY("iv-click-target",N.element),
U,U.url);U=N;break;default:return null}return U},OEG=function(M,U){if(!g.h1(M.C.getRootNode(),"ytp-cards-teaser-shown")){if(M.Z!==U){var N=g.is(),m=M.Z?M.Z.AX.lH:M.lH;
N&&m&&g.qV(N,[m]);M.Z=U;gF(M)}(N=M.isInitialized&&M.BV().style.display=="none")||(N=M.context.C.getPlayerState(),m=N===0&&M.context.C.getCurrentTime()===0,N=!(N===1||N===3||m));N||U.AX.teaserDurationMs&&M.C.gG(!0,{teaserText:U.AX.teaserText,durationMs:U.AX.teaserDurationMs,onClickCommand:U.AX.onClickCommand,lf:U.AX.lf??null});M.hz.isActive()||((!M.O||!M.Sw.isActive()&&M.Wv)&&mnu(M,U),M.hz.start(910+U.AX.teaserDurationMs))}},w$n=function(M){return M.Z?M.Z.AX.type==="productListing":M.C.G("enable_wn_infocards")?
!!M.cards?.length&&g.Ju(M.cards,U=>U.AX.type==="productListing"):g.Ju(M.cards,U=>U.AX.type==="productListing")},mnu=function(M,U){M.Y.PV?(U=new DG([0,
M.K.scrollTop],[0,U.bj.offsetTop],600,hZG),M.context.O.listen(U,"animate",N=>{M.K.scrollTop=N.y}),M.context.O.listen(U,"finish",N=>{M.K.scrollTop=N.y}),U.play()):(M.Y.kN(!0),M.K.scrollTop=U.bj.offsetTop,M.Y.kN(!1))},v9=function(M){return M.Z&&M.Z.AX?M.Z.AX:M.cards[0]&&M.cards[0].AX?M.cards[0].AX:null},cZ7=function(M){var U=M.annotation.data;
"start_ms"in U&&"end_ms"in U&&M.addCueRange(Number(U.start_ms),Number(U.end_ms),M.annotation.id,()=>{M.show()},()=>{M.hide()})},SSu=function(M,U){var N=Z$H(U).width;
g.I8(U,N);N=new nH(U,[N,U.offsetTop],[N-N,U.offsetTop],200,nEO);g.D(M,N);M.context.O.listen(N,"begin",()=>{g.gW(U,!0)});
N.play()},YW=function(M,U,N){N.stopPropagation();
yZu(M);E7J(M,U);M.Z.focus()},Lfj=function(M){var U=M.annotation.data;
if(M.annotation.style==="cta")var N=6;else if(M.annotation.style==="video"||M.annotation.style==="playlist")N=7;M.A=U.collapsedelay_ms||M.A;var m=["iv-promo","iv-promo-inactive"];M.BV().setAttribute("aria-hidden","true");M.BV().setAttribute("aria-label","Promotion");M.BV().tabIndex=0;var O=M.annotation.wV(),v=U.image_url;if(v){var Y=M.createElement({W:"div",aS:["iv-promo-img","iv-click-target"]});v=M.createElement({W:"img",L:{src:v,"aria-hidden":"true"}});Y.appendChild(v);U.video_duration&&!U.is_live?
(v=M.createElement({W:"span",N:"iv-promo-video-duration",Hv:U.video_duration}),Y.appendChild(v)):U.playlist_length&&(v=M.createElement({W:"span",N:"iv-promo-playlist-length",Hv:U.playlist_length.toString()}),Y.appendChild(v));O&&fH(M,Y,O,M.annotation.id,U.session_data,void 0,N)}O?(v=M.createElement({W:"a",N:"iv-promo-txt"}),g.$_(v,O.Z()),M.Z=v):M.Z=M.createElement({W:"div",N:"iv-promo-txt"});switch(M.annotation.style){case "cta":case "website":var w=M.createElement({W:"p",X:[{W:"strong",Hv:U.text_line_1}]});
var l=M.createElement({W:"p",X:[{W:"span",N:"iv-promo-link",Hv:U.text_line_2}]});if(v=U.text_line_3){m.push("iv-promo-website-card-cta-redesign");var c=M.createElement({W:"button",aS:["iv-promo-round-expand-icon","ytp-button"]});v=M.createElement({W:"button",aS:["iv-button","iv-promo-button"],X:[{W:"span",N:"iv-button-content",Hv:v}]});var S=M.createElement({W:"div",N:"iv-promo-button-container"});S.appendChild(v);O&&fH(M,M.BV(),O,M.annotation.id,U.session_data,void 0,N)}g.Gu(M.Z,"iv-click-target");
O&&fH(M,M.Z,O,M.annotation.id,U.session_data,void 0,N);break;case "playlist":case "video":w=M.createElement({W:"p",X:[{W:"span",Hv:U.text_line_1}]}),l=M.createElement({W:"p",X:[{W:"strong",Hv:U.text_line_2}]}),U.is_live&&(w=l,l=M.createElement({W:"span",aS:["yt-badge","iv-promo-badge-live"],Hv:"LIVE NOW"})),g.Gu(M.Z,"iv-click-target"),O&&fH(M,M.Z,O,M.annotation.id,U.session_data,void 0,N),m.push("iv-promo-video")}w&&M.Z.appendChild(w);l&&M.Z.appendChild(l);M.V.appendChild(M.Z);S&&M.V.appendChild(S);
N=M.createElement({W:"div",N:"iv-promo-actions"});M.K=M.createElement({W:"button",aS:["iv-promo-expand","ytp-button"]});M.K.title="Expand";M.context.Z.listen(M.K,"click",y=>{YW(M,5E3,y)});
N.appendChild(M.K);g.gW(M.K,!1);M.context.Z.listen(M.BV(),"mouseover",M.Sw,M);M.context.Z.listen(M.BV(),"mouseout",M.u0,M);M.context.Z.listen(M.BV(),"touchend",y=>{YW(M,5E3,y)});
M.O=M.createElement({W:"button",aS:["iv-promo-close","ytp-button"]});M.O.title="Close";M.context.Z.listen(M.O,"click",M.annotation.style==="cta"&&U.text_line_3?M.ZQ:M.OM,M);N.appendChild(M.O);g.j7(M.BV(),m);Y&&(g.wr(M.BV(),Y),c&&Y.appendChild(c));g.wr(M.BV(),M.V);g.wr(M.BV(),N)},oZ=function(M){M.S&&(g.EJ.clearTimeout(M.S),M.S=null)},yZu=function(M){M.B.stop();
M.isCollapsed&&(g.ru(M.BV(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),M.isCollapsed=!1,M.Z&&M.Z.removeAttribute("aria-hidden"),g.gW(M.K,!1),g.gW(M.O,!0))},E7J=function(M,U){M.S||(M.S=g.TO(function(){oZ(this);
esa(this)},U,M))},esa=function(M){M.isCollapsed||M.D||M.S||(g.Gu(M.BV(),"iv-promo-collapsed"),M.isCollapsed=!0,M.B.start())},lkQ=function(M,U,N){U&&(N?wF(M,U.map(m=>g.Ev(m,N))):wF(M,U))},wF=function(M,U,N,m){var O=1,v=void 0,Y=-1;
if(N){let w=!1;v=()=>{O--;O||w||(clearTimeout(Y),w=!0,N())};
Y=setTimeout(()=>{w=!0;N()},1E3)}for(let w of U||[])O++,g.E0(w,v);
m&&(O++,m!==0&&M.C.sendVideoStatsEngageEvent(m,v))},AZJ=function(M){return M==="annotation-editor"||M==="live-dashboard"},Wf7=function(M){M.S&&(M.player.removeEventListener("videodatachange",M.S),M.S=null)},PpD=function(M){M=M.createElement({W:"div",
aS:["annotation","annotation-type-custom"]});g.gW(M,!1);return M},c9=function(M,U){var N=!1,m=U.getElementsByTagName("annotations");
if(m&&!(m.length<1)&&(m=m[0].getAttribute("itct"))){var O=g.is();if(O){var v=g.$Z();v&&g.YA(g.Ll)(void 0,O,v,[g.us(m)])}}U=U.getElementsByTagName("annotation");for(m=0;m<U.length;m++){var Y=CpN(M,U[m]);O=null;try{a:{if(!Y){O=null;break a}var w=Y.id;v=/.+/;let L=typeof w==="string"&&v!=null&&w!=null&&w.match(v)?w:"",C=ID(Y.type,p$F),q=ID(Y.style,ZED),r=XGF(Y.data),k=r.length!==0?JSON.parse(r):{};b:{var l=Y.action;v=JW4;if(l==null){var c=null;break b}if(g.pt(l)){Y=[];for(let b of l){let I=v(b);I&&Y.push(I)}c=
Y;break b}let Q=v(l);c=Q?[Q]:[]}v=c;O=L&&C?new akG(L,C,q,v,k):null}}catch(L){}if(O)if(O.type==="branding"||O.type==="promotion"){v=M;Y=O;var S=PpD(v),y=null;switch(Y.type){case "branding":if(v.player.J().dh)break;v.player.G("web_player_overlay_positioned_layout")?(S.setAttribute("data-overlay-order","11"),v.player.Gu(S,4,!0)):v.K.element.appendChild(S);y=new FfJ(S,lN(v),Y);break;case "promotion":g.tE(v.player,S,4),y=new B$j(S,lN(v),Y)}y&&y.b0();y&&(g.D(M,y),M.A[O.id]=y)}else if(O.type==="card"||O.type===
"drawer"){M.Z||(M.Z=qSO(M),g.D(M,M.Z));if(O.type==="card"){S=M.Z;var E=(N=O)&&N.data&&N.data.card_type;O=N.data;if(E)switch(v=O.tracking||{},v={xY:v.impression,click:v.click,close:v.close,Lc:v.teaser_impression,Wk:v.teaser_click},Y=O.tracking_params||{},y=null,E){case "collaborator":N={id:N.id,timestamp:O.timestamp||0,type:O.card_type,teaserText:O.teaser_text,teaserDurationMs:O.teaser_duration_ms,startMs:O.start_ms,autoOpen:O.auto_open||!1,sessionData:O.session_data||{},sponsored:O.sponsored||!1,
W8:v,YW:Y.card?g.us(Y.card):null,pV:Y.teaser?g.us(Y.teaser):null,lH:Y.icon?g.us(Y.icon):null,channelId:O.channel_id,customMessage:O.custom_message?O.custom_message:null,profileImageUrl:O.image_url,title:O.title,metaInfo:O.meta_info,url:s9({pause_on_navigation:O.pause_on_navigation,target:O.target||"new",value:O.url}),onClickCommand:null};Uq(S,N);break;case "playlist":N={id:N.id,timestamp:O.timestamp||0,type:O.card_type,teaserText:O.teaser_text,teaserDurationMs:O.teaser_duration_ms,startMs:O.start_ms,
autoOpen:O.auto_open||!1,sessionData:O.session_data||{},sponsored:O.sponsored||!1,W8:v,YW:Y.card?g.us(Y.card):null,pV:Y.teaser?g.us(Y.teaser):null,lH:Y.icon?g.us(Y.icon):null,kg:O.image_url,playlistVideoCount:O.playlist_video_count,customMessage:O.custom_message?O.custom_message:null,title:O.title,metaInfo:O.meta_info,url:s9({pause_on_navigation:O.pause_on_navigation,target:O.target||"new",value:O.url}),onClickCommand:null};Uq(S,N);break;case "productListing":O.signin_url&&(y=s9({target:"current",
value:O.signin_url}));E=[];let L=O.offers||[];for(let C=0;C<L.length;C++)E.push(new DnN(g.EV(L[C].merchant),g.EV(L[C].price)));N={id:N.id,timestamp:O.timestamp||0,type:O.card_type,teaserText:O.teaser_text,teaserDurationMs:O.teaser_duration_ms,startMs:O.start_ms,autoOpen:O.auto_open||!1,sessionData:O.session_data||{},sponsored:O.sponsored||!1,W8:v,YW:Y.card?g.us(Y.card):null,pV:Y.teaser?g.us(Y.teaser):null,lH:Y.icon?g.us(Y.icon):null,imageUrl:O.image_url,displayDomain:O.display_domain?O.display_domain:
null,showLinkIcon:!!O.show_link_icon,zN:O.button_icon_url?O.button_icon_url:null,title:O.title,customMessage:O.custom_message?O.custom_message:null,url:s9({pause_on_navigation:O.pause_on_navigation,target:O.target||"new",value:O.url}),dtQ:y,Q80:O.signin_title?O.signin_title:void 0,Mew:O.signin_message?O.signin_message:void 0,offers:E,onClickCommand:null};Uq(S,N);break;case "simple":N={id:N.id,timestamp:O.timestamp||0,type:O.card_type,teaserText:O.teaser_text,teaserDurationMs:O.teaser_duration_ms,
startMs:O.start_ms,autoOpen:O.auto_open||!1,sessionData:O.session_data||{},sponsored:O.sponsored||!1,W8:v,YW:Y.card?g.us(Y.card):null,pV:Y.teaser?g.us(Y.teaser):null,lH:Y.icon?g.us(Y.icon):null,imageUrl:O.image_url,displayDomain:O.display_domain?O.display_domain:null,showLinkIcon:!!O.show_link_icon,zN:O.button_icon_url?O.button_icon_url:null,title:O.title,customMessage:O.custom_message?O.custom_message:null,url:s9({pause_on_navigation:O.pause_on_navigation,target:O.target||"new",value:O.url}),onClickCommand:null};
Uq(S,N);break;case "video":N={id:N.id,timestamp:O.timestamp||0,type:O.card_type,teaserText:O.teaser_text,teaserDurationMs:O.teaser_duration_ms,startMs:O.start_ms,autoOpen:O.auto_open||!1,sessionData:O.session_data||{},sponsored:O.sponsored||!1,W8:v,YW:Y.card?g.us(Y.card):null,pV:Y.teaser?g.us(Y.teaser):null,lH:Y.icon?g.us(Y.icon):null,kg:O.image_url,videoDuration:O.video_duration||null,customMessage:O.custom_message?O.custom_message:null,title:O.title,metaInfo:O.meta_info,isLiveNow:!!O.is_live_now,
url:s9({pause_on_navigation:O.pause_on_navigation,target:O.target||"new",value:O.url}),onClickCommand:null},Uq(S,N)}}else v7F(M.Z,O);N=!0}}N&&(ZG(M.player),M.Y())},zsD=function(M){var U=M.player.J();
M=M.player.getVideoData();return(U.annotationsLoadPolicy||M.annotationsLoadPolicy)===1&&!M.U6||U.Wv.get(M.videoId)||M.hY()||g.yp(M)?!0:!1},n77=function(M,U){U=!U.isCued()&&!U.Z(1024);
M.K.kN(U);M.O.kN(U)},T$n=function(M,U){var N=U.videoId,m=v=>{var Y=M.loadNumber;
M.V=null;M.loaded&&M.loadNumber===Y&&M.player.getVideoData().videoId===N&&(v=g.CS(v)&&v.responseXML?v.responseXML:null)&&(c9(M,v),g.Gu(M.player.getRootNode(),"iv-module-loaded"))};
g.g_()&&(m=hsO(M,m));var O={format:"XML",onFinish:m,onError:()=>{M.V=null},
urlParams:{}};U.isPharma&&(O.urlParams.pharma="1");O.method="POST";O.withCredentials=!0;(m=M.player.J().Wv.get(N))&&GoN(O,m);m=m&&m.RV;if(!U.mu||m)M.S=()=>{if(!M.ZQ)M.onVideoDataChange(O);var v=M.player.getVideoData();v?.JX()&&!M.OM&&jHH(M,v)},M.player.addEventListener("videodatachange",M.S)},SS=function(M,U){var N=!1;
M.Z||(M.Z=qSO(M),g.D(M,M.Z));for(var m of U.cards||[])m.cardRenderer&&(YSn(M.Z,m.cardRenderer),N=!0);N&&(M.player.getVideoData()?.JX()||(N=M.Z,m=U.headerText?g.Kl(U.headerText):"",g.Ea(N.uZ,m),N.D&&N.D.setAttribute("data-tooltip-title",m),N.context.videoData.eventId&&(N.eventId=N.context.videoData.eventId),N.ML=U.trackingParams?g.us(U.trackingParams):null,N.V=U.closeButton.infoCardIconRenderer.trackingParams?g.us(U.closeButton.infoCardIconRenderer.trackingParams):null,N.lH=U.icon.infoCardIconRenderer.trackingParams?
g.us(U.icon.infoCardIconRenderer.trackingParams):null,M.Y()),ZG(M.player))},jHH=function(M,U){if(U=U.getWatchNextResponse()?.cards?.cardCollectionRenderer)M.OM=!0,SS(M,U),U.headerText&&M.iR&&(U=g.Kl(U.headerText),M.iR.setAttribute("data-tooltip-title",U))},hsO=function(M,U){return(...N)=>{M.GS()||M.b0.push(g.e7.jW(()=>{U(...N)}))}},GoN=function(M,U){M.method="POST";
M.postParams=M.postParams||{};U.RV&&(M.postParams.ic_coll=U.RV);U.iN&&(M.postParams.ic_track=U.iN)},CpN=function(M,U){var N={};
for(var m of U.attributes)N[m.name]=m.nodeValue;for(m=0;m<U.childNodes.length;m++){let v=U.childNodes[m];if(!g.Z3(v)||v.nodeType!=1)continue;var O=void 0;if(N[v.tagName])O=N[v.tagName];else if(v.tagName==="data"){v.childNodes.length>0&&(O=v.childNodes[0].nodeValue,N[v.tagName]=typeof O==="string"?O.trim():O);continue}else O=[],N[v.tagName]=O;v&&v.tagName==="TEXT"?v.childNodes.length===1&&v.childNodes[0].nodeType===3?O.push(v.childNodes[0].nodeValue):O.push(""):v&&O.push(CpN(M,v))}return N},lN=function(M){if(!M.D){let U=
new rZu(M);
g.D(M,U);let N=new g.Uv(M);g.D(M,N);M.D=new KfN(U,N,M.player.J(),M.player.getVideoData(),M.logger,M.player,M.dh)}return M.D},HEa=function(M){var U=M.player.getVideoData();
if(U.SR){var N=M.player.J().Wv.get(U.videoId);if(N){var m={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(O,v,Y)=>{O=M.loadNumber;v=U.videoId;M.loaded&&M.loadNumber===O&&M.player.getVideoData().videoId===v&&(Y=g.CS(Y)&&Y.responseXML?Y.responseXML:null)&&c9(M,Y)}};
g.g_()&&(m.onFinish=hsO(M,m.onFinish));m.postParams={ic_only:"1"};GoN(m,N);M.ZQ=!0;g.hn(U.SR,m)}}},qSO=function(M){var U=new g.d({W:"div"});
g.gW(U.element,!1);var N=new koG(M.player,U.element,lN(M));g.D(N,U);U.IS(M.K.element);N.b0();return N},xna=function(M,U,N,m,O){if(!M.player.J().dh){var v=[];
U.navigationEndpoint&&g.X(U.navigationEndpoint,g.CW)&&g.X(U.navigationEndpoint,g.CW).browseId&&v.push(new i$7("openUrl","click",new I2J(`/channel/${g.X(U.navigationEndpoint,g.CW).browseId}`,"new",!0,!0)));var Y=U.watermark.thumbnails[0];m={channel_name:U.channelName,end_ms:U.endTimeMs,image_height:Y.height,image_type:1,image_url:Y.url,image_width:Y.width,is_mobile:!1,session_data:{annotation_id:N,ei:O,feature:"iv",itct:U.trackingParams,src_vid:m},start_ms:U.startTimeMs};if(U.subscribeButton&&g.X(U.subscribeButton,
g.Im)){m.channel_id=g.X(U.subscribeButton,g.Im).channelId;U=g.X(U.subscribeButton,g.Im);Y=O=null;U.subscribed?(U.subscriberCountWithUnsubscribeText&&(O=g.Kl(U.subscriberCountWithUnsubscribeText)),U.subscriberCountText&&(Y=g.Kl(U.subscriberCountText))):(U.subscriberCountText&&(O=g.Kl(U.subscriberCountText)),U.subscriberCountWithSubscribeText&&(Y=g.Kl(U.subscriberCountWithSubscribeText)));let w=g.X(U.signInEndpoint?.commandMetadata,g.a0)?.url||"";U={subscribeText:g.Kl(U.unsubscribedButtonText),subscribeCount:O||
"",unsubscribeText:g.Kl(U.subscribedButtonText),unsubscribeCount:Y||"",enabled:U.enabled||!1,classic:!1,subscribed:U.subscribed||!1,feature:"iv",signInUrl:w};m.standalone_subscribe_button_data=U}v=new akG(N,"branding","branding",v,m);m=PpD(M);M.player.G("web_player_overlay_positioned_layout")?(m.setAttribute("data-overlay-order","11"),M.player.Gu(m,4,!0)):M.K.element.appendChild(m);v=new FfJ(m,lN(M),v);v.b0();g.D(v,v);M.A[N]=v}};
g.Ac.prototype.gG=g.m0(43,function(M,U){var N=g.ez(this.WV());N&&N.gG(M,U)});
var Fj={},BD=null;g.j9(DG,g.Hk);g.B=DG.prototype;g.B.getDuration=function(){return this.duration};
g.B.play=function(M){if(M||this.Z==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;q3(this);this.startTime=M=g.zA();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.S=this.startTime;this.progress||this.xF();this.Ln("play");this.isPaused()&&this.Ln("resume");this.Z=1;var U=g.Fc(this);U in Fj||(Fj[U]=this);Be7();qma(this,M);return!0};
g.B.stop=function(M){q3(this);this.Z=0;M&&(this.progress=1);D1i(this,this.progress);this.onStop();this.Pm()};
g.B.pause=function(){this.isPlaying()&&(q3(this),this.Z=-1,this.Ln("pause"))};
g.B.zS=function(){this.Z==0||this.stop(!1);this.Ln("destroy");DG.kq.zS.call(this)};
g.B.destroy=function(){this.dispose()};
g.B.K5=function(){this.Ln("animate")};
g.B.Ln=function(M){this.dispatchEvent(new zZa(M,this))};
g.j9(zZa,g.Tf);g.j9(zX,DG);zX.prototype.O=function(){};
zX.prototype.K5=function(){this.O();zX.kq.K5.call(this)};
zX.prototype.Pm=function(){this.O();zX.kq.Pm.call(this)};
zX.prototype.xF=function(){this.O();zX.kq.xF.call(this)};
g.j9(nH,zX);nH.prototype.O=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var rZu=class extends g.zc{constructor(M){super();this.K=M||window;this.Z=[]}listen(M,U,N,m){N=(0,g.Bj)(N,m||this.K);M=g.z3(M,U,N);this.Z.push(M);return M}Xe(M,U,N,m){N=(0,g.Bj)(N,m||this.K);M=a2Q(M,U,N);this.Z.push(M);return M}Ds(M){g.nJ(M);g.UO(this.Z,M)}removeAll(){g.nJ(this.Z);this.Z.length=0}zS(){this.removeAll();super.zS()}};var IkQ=class extends g.Qz{constructor(M){super(M);this.S=this.endscreen=null;this.K={};this.A={};this.B=this.O=null;this.D=[];this.Z=null;this.OM=!0;this.V=0;M=M.J();this.Y=g.eP(M)||M.Sw==="profilepage";this.events=new g.Zv(this);g.D(this,this.events);this.events.U(this.player,g.uV("creatorendscreen"),this.onCueRangeEnter);this.events.U(this.player,g.Ix("creatorendscreen"),this.onCueRangeExit);this.events.U(this.player,"resize",this.eb);this.events.U(window,"focus",this.ZQ);this.load();var U=g.YY("STYLE");
(g.i1("HEAD")[0]||document.body).appendChild(U);this.addOnDisposeCallback(()=>{g.SG(U)});
U.sheet&&(U.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),U.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!rA(this)){var M=g.hoA(this.player.getVideoData());M?(M=jx(M,ju7(this)),KH(this,M,!1)):H$u(this)}}unload(){KH(this,null);this.S&&(this.S.abort(),this.S=null);super.unload()}Ev(M,U){return rA(this)?M==="loadCustomEndscreenRenderer"?(M=jx(U,"new"),KH(this,M),!0):null:null}getOptions(){return rA(this)?["loadCustomEndscreenRenderer"]:[]}eb(){if(this.endscreen&&this.endscreen.elements){var M=this.player.getVideoContentRect();if(M&&M.width!==0&&M.height!==0){var U=this.player.getPlayerSize();
if(U&&U.width!==0&&U.height!==0){var N=M.width/M.height;var m=0;var O=-1;for(var v=0;v<QHu.length;v++){var Y=Math.abs(U.width-QHu[v]);if(O===-1||m>=Y)O=v,m=Y}m=bED[O];this.O&&g.KK(this.O.element,"outline-width",Math.max(U.width,U.height)+"px");for(U=0;U<this.endscreen.elements.length;++U){v=this.endscreen.elements[U].id;O=this.K[v];Y=this.A[v];if(!O||!Y)continue;let l=Y.width*N/Y.aspectRatio;var w=Math.round(Y.width*M.width);v=Math.round(l*M.height);let c=M.left+Math.round(Y.left*M.width),S=M.top+
Math.round(Y.top*M.height);g.dr(O.element,w,v);g.I8(O.element,c,S);g.ru(O.element,X$Q);w>256||v>256?g.Gu(O.element,"ytp-ce-large-round"):w>96||v>96?g.Gu(O.element,"ytp-ce-medium-round"):g.Gu(O.element,"ytp-ce-small-round");g.ru(O.element,uTH);w=Y.left+Y.width/2;Y=Y.top+l/2;g.Gu(O.element,w<=.5&&Y<=.5?"ytp-ce-top-left-quad":w>.5&&Y<=.5?"ytp-ce-top-right-quad":w<=.5&&Y>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ru(O.element,bED);g.Gu(O.element,m);(O=g.tY(document,"div","ytp-ce-expanding-overlay-body",
O.element)[0])&&g.KK(O,"height",`${v}px`)}}}}}onCueRangeEnter(M){if(this.endscreen)if(M.getId()==="ytp-ce-in-endscreen")Xj(this,this.endscreen.impressionUrls),(M=g.is())&&this.endscreen.visualElement&&g.F8(M,this.endscreen.visualElement),this.Z&&(g.Gu(this.Z,"ytp-ce-element-show"),this.Z.removeAttribute("aria-hidden"),this.player.bA()?g.Gu(this.Z,"ytp-ce-hide-button-lower"):g.Tu(this.Z,"ytp-ce-hide-button-lower"));else{M=M.getId().substring(15);var U=this.K[M],N=this.A[M];g.Gu(U.element,"ytp-ce-element-show");
U.element.removeAttribute("aria-hidden");U=this.player.getRootNode();g.Gu(U,"ytp-ce-shown");Xj(this,N.impressionUrls);(U=g.is())&&g.F8(U,N.visualElement);this.player.J().OM&&g.zS(this.player,"endscreenelementshown",M)}}onCueRangeExit(M){if(M.getId()==="ytp-ce-in-endscreen")this.Z&&(g.Tu(this.Z,"ytp-ce-element-show"),this.Z.setAttribute("aria-hidden","true"));else{M=M.getId().substring(15);var U=this.K[M];g.Tu(U.element,"ytp-ce-element-show");U.element.setAttribute("aria-hidden","true");U=this.player.getRootNode();
g.Tu(U,"ytp-ce-shown");this.player.J().OM&&g.zS(this.player,"endscreenelementhidden",M)}}ZQ(M){M.target===window&&(new g.Fy(()=>{for(let U of Object.values(this.K))g.ru(U.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}kN(M){for(let U of Object.values(this.K))M?U.element.setAttribute("hidden",""):U.element.removeAttribute("hidden")}FX(M){this.Z&&this.player.getRootNode().removeChild(this.Z);
M&&(g.Gu(M,"ytp-ce-hide-button-container"),this.Z=M,g.tE(this.player,this.Z,4))}},QHu=[346,426,470,506,570,640,853,1280,1920],bED="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),uTH=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],X$Q=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var I2J=class{constructor(M,U,N,m){this.value=M;this.target=U;this.showLinkIcon=N;this.K=m}Z(){return this.value?this.value:null}},uia={aY:"current",yO:"new"};var i$7=class{constructor(M,U,N){this.type=M;this.trigger=U;this.url=N}},suJ={CLOSE:"close",k5:"openUrl",SUBSCRIBE:"subscribe"},$1J={E9:"click",CLOSE:"close",Tq:"hidden",KrS:"rollOut",OoS:"rollOver",dLz:"shown"};var akG=class{constructor(M,U,N,m,O){this.id=M;this.type=U;this.style=N;this.data=O;this.action=m||[]}wV(){var M=tDN(this,U=>U.type==="openUrl"&&U.url!=null);
return M?M.url:null}},ZED={ny:"anchored",p6:"branding",CHANNEL:"channel",IY:"cta",r9:"highlightText",Uh:"label",PLAYLIST:"playlist",POPUP:"popup",N6M:"speech",SUBSCRIBE:"subscribe",rzM:"title",VIDEO:"video",ILL:"website"},p$F={p6:"branding",X7:"card",Tr:"drawer",Li:"highlight",bi:"marker",M2:"promotion",TEXT:"text",elT:"widget"};var sHu=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
$nn=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var iEJ=class{constructor(M,U){this.context=M;this.Z=U}};var DnN=class{constructor(M,U){this.merchant=M;this.price=U}};var JZG=class extends g.zc{constructor(M,U){super();this.element=M;this.context=U;this.po=!1;this.Jz=new Map;this.r6=new Map;this.context.C.addEventListener(g.uV("annotations_module"),N=>{(N=this.Jz.get(N))&&N.apply(this)});
this.context.C.addEventListener(g.Ix("annotations_module"),N=>{(N=this.r6.get(N))&&N.apply(this)})}addCueRange(M,U,N,m,O){M=new g.OH(M,U,{id:N,
namespace:"annotations_module"});m&&this.Jz.set(M,m);O&&this.r6.set(M,O);this.context.C.ek([M],1)}b0(){this.context.K.subscribe("resize",this.d6,this)}BV(){return this.element}xf(M,U,N,m,O,v){if(this.po)return!1;v&&(v.stopPropagation(),v.preventDefault());this.navigate(M,N,m,O);return!1}show(){}hide(){}destroy(){g.SG(this.BV())}d6(){}navigate(M,U,N,m){var O=M.Z();if(O){var v=d1Q(O,M.target),Y=()=>{M.K&&this.context.C.pauseVideo();var w=this.context.videoData.nP||!1,l=g.yD(O||"");w&&l&&(l.v||l.list)?
this.context.C.UE(l.v,U,l.list,!1):g.B0(O||"",v==="current"?"_top":void 0,U)};
v==="new"&&(Y(),Y=null);wF(this.context.logger,N,Y,m);f2a(O)||(N=g.is(),m=U.itct,N&&m&&g.Df(N,g.us(m)))}}zS(){this.Jz.clear();this.r6.clear();super.zS()}createElement(M){M=new g.d(M);g.D(this,M);return M.element}};var koG=class extends JZG{constructor(M,U,N){super(U,N);this.C=M;this.eventId=null;this.zb=this.Wv=this.ye=this.O=this.isInitialized=!1;this.cards=[];this.EM=this.D=this.sM=this.B=this.DQ=this.Z=null;this.OM=[];this.ZQ=this.V=this.lH=this.ML=null;this.A=0;this.Sw=new g.Fy(()=>{},N.j.Hg?4E3:3E3);
g.D(this,this.Sw);this.hz=new g.Fy(()=>{});
g.D(this,this.hz);this.u0=new iEJ(N,(m,O,v,Y,w,l)=>{fH(this,m,O,v,Y,w,l)});
this.Y=new g.d({W:"div",N:"iv-drawer",L:{id:"iv-drawer"},X:[{W:"div",N:"iv-drawer-header",L:{"aria-role":"heading"},X:[{W:"span",N:"iv-drawer-header-text"},{W:"button",aS:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{W:"div",N:"iv-drawer-content"}]});g.D(this,this.Y);this.S=this.Y.element;this.jw=new g.sQ(this.Y,330);g.D(this,this.jw);this.uZ=g.Rw("iv-drawer-header-text",this.S);this.K=g.Rw("iv-drawer-content",this.S);this.addCueRange(0,N.videoData.lengthSeconds*
1E3,"",()=>{this.ye&&Ma(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.ye=this.O)&&Na(this)});
this.VT=new g.Zv(this);g.D(this,this.VT);this.C.addEventListener("videodatachange",this.eU.bind(this))}eU(){this.ZQ&&Uq(this,this.ZQ)}isAvailable(){var M;if(M=!!this.cards.length)(M=this.C.getRootNode())?(M=g.VA(M),M=173<M.width&&173<M.height):M=!1;return M}d6(){var M=this.isAvailable();g.gW(this.BV(),M);g.KO(this.context.C.getRootNode(),g.z2.IV_DRAWER_ENABLED,M);ZG(this.C)}destroy(){this.C.gG(!1);try{this.C.getRootNode().removeChild(this.S)}catch(M){}g.hA(this.OM);this.VT.K();this.DQ&&this.DQ.dispose();
this.B&&this.B.dispose();super.destroy()}wa(){this.context.Z.listen(g.Rw("iv-drawer-close-button",this.S),"click",this.Ve,this);this.context.Z.listen(this.K,"touchend",()=>{this.Sw.start()});
this.context.Z.listen(this.K,"scroll",this.gK,this);this.context.K.subscribe("onHideControls",()=>{this.Wv=!0});
this.context.K.subscribe("onShowControls",()=>{this.Wv=!1});
this.context.K.subscribe("onVideoAreaChange",()=>{this.Wv=g.h1(this.C.getRootNode(),"ytp-autohide")});
this.OM.push(g.n0("iv-button-shown",this.lZ,this));this.OM.push(g.n0("iv-button-hidden",this.DL,this));N$O(this)}findLastIndex(M){if(this.cards.length===0)return 0;var U=g.ft(this.cards,N=>M.AX.startMs>N.AX.startMs||M.AX.startMs===N.AX.startMs&&M.AX.timestamp>=N.AX.timestamp?!0:!1);
return U===-1?0:U+1}Ve(){if(this.O){wF(this.context.logger,v9(this).W8.close);var M=g.is();M&&this.V&&g.Df(M,this.V);Na(this)}}gK(){g.KO(this.S,"iv-drawer-scrolled",this.K.scrollTop>0)}lZ(){var M=g.is(),U=v9(this);U=U?U.lH:this.lH;M&&U&&g.Bw(M,[U])}DL(){var M=g.is(),U=v9(this);U=U?U.lH:this.lH;M&&U&&g.qV(M,[U])}rK(){var M=v9(this);wF(this.context.logger,M.W8.Lc);var U=g.is();if(U&&M)if(this.C.G("web_infocards_teaser_show_logging_fix")){let N=[];M.pV&&N.push(M.pV);M.lH&&N.push(M.lH);N.length>0&&g.Bw(U,
N)}else g.Bw(U,[M.pV,M.lH])}iZ(){var M=g.is(),U=v9(this);M&&U&&g.qV(M,[U.pV])}Mh(M){var U=v9(this),N=g.is();this.Z?M?(M=this.context.logger,wF(M,U.W8.Wk),M.C.sendVideoStatsEngageEvent(4,void 0),N&&U.pV&&g.Df(N,U.pV)):(M=this.context.logger,wF(M,U.W8.Wk),M.C.sendVideoStatsEngageEvent(4,void 0),N&&U.lH&&g.Df(N,U.lH)):(M=this.context.logger,wF(M,U.W8.Wk),M.C.sendVideoStatsEngageEvent(4,void 0),N&&this.lH&&g.Df(N,this.lH))}};var t54=class extends JZG{constructor(M,U,N){super(M,U);this.annotation=N;this.isActive=!1}b0(){super.b0();cZ7(this)}show(){super.show();var M=g.is(),U=this.annotation.data;M&&U&&(U=U.session_data)&&g.Bw(M,[g.us(U.itct)])}hide(){super.hide();var M=g.is(),U=this.annotation.data;M&&U&&(U=U.session_data)&&g.qV(M,[g.us(U.itct)])}};var FfJ=class extends t54{constructor(M,U,N){super(M,U,N);this.Z=null;this.K=!1}show(){if(!this.isActive){super.show();if(!this.K){g.Gu(this.BV(),"iv-branding");let M=this.annotation.data;this.Z=this.createElement({W:"img",aS:["branding-img","iv-click-target"],L:{"aria-label":"Channel watermark",src:M.image_url,width:M.image_width,height:M.image_height}});g.gW(this.Z,!1);let U=this.createElement({W:"button",aS:["branding-img-container","ytp-button"]});U.appendChild(this.Z);this.BV().appendChild(U);
let N=this.annotation.wV();N&&fH(this,U,N,this.annotation.id,M.session_data);this.K=!0}g.gW(this.BV(),!0);this.isActive=!0;if(this.Z){try{SSu(this,this.Z)}catch{}g.Gu(this.context.C.getRootNode(),"ytp-branding-shown");this.context.C.getRootNode().style.setProperty("--branding-image-width",`${this.Z.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.gW(this.BV(),!1),this.isActive=!1,g.Tu(this.context.C.getRootNode(),"ytp-branding-shown"))}destroy(){g.Tu(this.context.C.getRootNode(),
"ytp-branding-shown");super.destroy()}};var KfN=class{constructor(M,U,N,m,O,v,Y){this.Z=M;this.O=U;this.j=N;this.videoData=m;this.logger=O;this.C=v;this.K=Y}};var B$j=class extends t54{constructor(M,U,N){super(M,U,N);this.D=this.isCollapsed=this.Y=!1;this.A=5E3;this.K=this.O=this.Z=this.S=null;this.V=this.createElement({W:"div",aS:["iv-promo-contents"]});this.B=new g.Fy(()=>{this.Z.setAttribute("aria-hidden","true");g.gW(this.O,!1);g.gW(this.K,!0)},700,this);
g.D(this,this.B)}show(){this.isActive||(super.show(),this.Y||(Lfj(this),this.Y=!0),g.gW(this.BV(),!0),g.TO(function(){g.Tu(this.BV(),"iv-promo-inactive")},100,this),this.BV().removeAttribute("aria-hidden"),this.isActive=!0,oZ(this),yZu(this),E7J(this,this.A))}hide(){this.isActive&&(g.Gu(this.BV(),"iv-promo-inactive"),this.isActive=!1,this.BV().setAttribute("aria-hidden","true"))}xf(M,U,N,m,O,v){return this.isCollapsed?!1:super.xf(M,U,N,m,O,v)}Sw(M){this.D=!0;
YW(this,500,M)}u0(){this.D=!1;esa(this)}OM(M){M.stopPropagation();this.hide()}ZQ(M){M.stopPropagation();oZ(this);this.isCollapsed=!0;g.Gu(this.BV(),"iv-promo-collapsed-no-delay");this.B.start()}destroy(){this.B.dispose();super.destroy()}};var Rsj=class{constructor(M){this.C=M}};g.l0("annotations_module",class extends g.Qz{constructor(M){super(M);this.OM=this.ZQ=!1;this.loadNumber=0;this.A={};this.logger=new Rsj(this.player);this.B=new g.Zv(this);this.V=this.S=null;this.events=new g.Zv(this);this.iR=this.D=this.Z=null;this.b0=[];g.D(this,this.B);this.B.U(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.B.U(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.B.U(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.B.U(this.player,"resize",N=>{this.publish("resize",N)});
this.B.U(this.player,"presentingplayerstatechange",N=>{this.publish("presentingplayerstatechange",N)});
this.subscribe("presentingplayerstatechange",this.Sw,this);this.subscribe("resize",this.Y,this);this.player.J().Wv.subscribe("vast_info_card_add",this.u0,this);g.D(this,this.events);this.d6=this.createElement({W:"div",N:"video-custom-annotations"});this.K=new g.d({W:"div",aS:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.K);g.tE(this.player,this.K.element,4);this.K.hide();this.O=new g.d({W:"div",aS:["ytp-iv-video-content"]});g.D(this,this.O);M=this.createElement({W:"div",N:"video-annotations"});
M.appendChild(this.d6);this.O.element.appendChild(M);this.Ip()?this.load():this.player.G("web_fix_annotations")&&(this.S=()=>{this.loaded||this.GS()||!this.Ip()||(Wf7(this),this.load())},this.player.addEventListener("videodatachange",this.S));
var U=this.createElement({W:"style"});(g.i1("HEAD")[0]||document.body).appendChild(U);this.addOnDisposeCallback(()=>{g.SG(U)});
if(M=U.sheet){for(let N of sHu)M.insertRule(N,0);for(let N of $nn)M.insertRule(N,0)}}Ev(M,U){if(!AZJ(this.player.J().playerStyle))return null;switch(M){case "loadCustomAnnotationsXml":return(M=g.fT(U))&&c9(this,M),!0;case "removeCustomAnnotationById":return U&&this.Z&&(Vr(this.Z,U),ZG(this.player)),!0}return null}getOptions(){return AZJ(this.player.J().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}Ip(){var M=this.player.getVideoData(),U=M.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return M.nP||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.G("web_fix_annotations")?zsD(this)?U?.isWatermarkEnforced===!0?!0:U?.isAnnotationsEnabled??!1:!1:zsD(this)}Y(){if(this.O){var M=this.player.no().getVideoContentRect(!0);g.dr(this.O.element,M.width,M.height);g.I8(this.O.element,M.left,M.top)}if(this.Z){var U=this.player.jd();M=this.Z;U=U.width;g.KO(M.S,"iv-drawer-small",U<=426);g.KO(M.S,"iv-drawer-big",U>=1280)}}Sw(M){n77(this,M.state);M.state.Z(2)&&(this.bA()&&this.kW()&&this.player.getPresentingPlayerType()!==
2&&this.JJ(!1),this.gG(!1))}load(){super.load();n77(this,this.player.getPlayerStateObject());this.loadNumber++;var M=this.player.getVideoData();T$n(this,M);g.tE(this.player,this.O.element,4);this.Y();var U=g.yp(M),N=M.hY();if(this.player.G("web_fix_annotations")){if(U&&(U.featuredChannel&&xna(this,U.featuredChannel,U.annotationId||"branding",M.videoId||null,M.eventId||null),U=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,U?.isWatermarkEnforced&&!U?.isAnnotationsEnabled))return;
N&&SS(this,N)}else N&&SS(this,N),U&&U.featuredChannel&&xna(this,U.featuredChannel,U.annotationId||"branding",M.videoId||null,M.eventId||null);this.iR=g.Rw("ytp-cards-button",this.player.getRootNode());M.JX()&&jHH(this,M)}onVideoDataChange(){}unload(){this.player.sa("annotations_module");for(let M of Object.keys(this.A))this.A[M].destroy();this.D=null;this.Z&&(this.Z.destroy(),this.Z=null,ZG(this.player));this.ZQ=!1;this.V&&(this.V.abort(),this.V=null);this.OM=!1;this.A={};this.K.hide();super.unload();
this.O.detach();Wf7(this)}u0(M){M===this.player.getVideoData().videoId&&(this.loaded?HEa(this):this.load())}bA(){return this.Z?.isAvailable()||this.OM}kW(){return!!this.Z&&this.Z.O}JJ(M,U=!1,N){this.bA();this.Z&&(M?N?Ma(this.Z,N,U):Ma(this.Z,"YOUTUBE_DRAWER_AUTO_OPEN",U):Na(this.Z))}gG(M,U){this.player.publish(M?"cardsteasershow":"cardsteaserhide",U)}zS(){this.player.J().Wv.unsubscribe("vast_info_card_add",this.u0,this);g.Tu(this.player.getRootNode(),g.z2.IV_DRAWER_OPEN);var M=this.b0,U=g.e7;for(let N=
0,m=M.length;N<m;N++)U.n0(M[N]);this.b0.length=0;super.zS()}createElement(M){M=new g.d(M);g.D(this,M);return M.element}});g.l0("creatorendscreen",IkQ);})(_yt_player);
