(function(g){var window=this;'use strict';var dn7=async function(M,U,N){M.K=g.hn(U,N)},yw=function(M){M.isActive()||M.start()},V5u=function(M,U){var N=new g.iP;
N.languageCode=M.languageCode;N.languageName=M.languageName;N.name=M.name;N.displayName=M.displayName;N.kind=M.kind;N.isDefault=!1;N.Z=M.Z;N.isTranslateable=M.isTranslateable;N.vssId=M.vssId;N.url=M.url;N.translationLanguage=U;M.xtags&&(N.xtags=M.xtags);M.captionId&&(N.captionId=M.captionId);return N},Eq=function(M,U){return U?M.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},gvO=function(M){return g.qN(M)||M.G("web_enable_caption_language_preference_stickiness")},Myj=async function(M,U){M=
M+"|"+U;
U=await g.QI();if(!U)throw g.Le("gct");return(await g.e8(U)).get("captions",M)},U24=function(M,U,N){Myj(M,U).then(m=>{m&&N(m.trackData,new g.iP(m.metadata))})},LA=function(M){if(!Ni7.test(M))throw Error("'"+M+"' is not a valid hex color");
M.length==4&&(M=M.replace(m24,"#$1$1$2$2$3$3"));M=M.toLowerCase();M=parseInt(M.slice(1),16);return[M>>16,M>>8&255,M&255]},OwG=function(){var M={},U="suggest_correction"in g.nW?g.nW.suggest_correction:"Edit caption";
U=U||"";for(let N in M){let m=()=>String(M[N]);
U=U.replace(new RegExp("\\$\\{"+N+"\\}","gi"),m);U=U.replace(new RegExp("\\$"+N,"gi"),m)}return U},eS=function(){return g.H8("yt-player-caption-display-settings")},vvH=function(M,U){var N=g.q4(M.segments,U);
N>=0||N<0&&(-N-1)%2===1||(N=-N-1,N>0&&U-M.segments[N-1]===1&&N<M.segments.length&&M.segments[N]-U===1?(g.M4(M.segments,N),g.M4(M.segments,N-1)):N>0&&U-M.segments[N-1]===1?M.segments[N-1]=U:N<M.segments.length&&M.segments[N]-U===1?M.segments[N]=U:(g.cJ(M.segments,N,0,U),g.cJ(M.segments,N+1,0,U)))},YjJ=function(M){return M.Z&&M.Z.B?M.Z.B+M.player.oy()<M.player.getCurrentTime():!1},ovi=function(M,U){if(M.policy.Fu&&M.player.q$()){var N=g.Uz(U,M.policy,{});
N.set("pot",M.player.q$());N=N.wV()}else N=g.Uz(U,M.policy,{}).wV();var m={format:"RAW",withCredentials:!0};if(M.policy.d6){m.method="POST";let Y=U.S;Y&&Object.keys(Y).length>0?m.postBody=g.Fb(Y,g.Xx):m.postBody=(0,g.QT)([120,0])}M.B&&(m.responseType="arraybuffer");var O=++M.b0,v=(0,g.u)();M.K=g.rQ(N,m,3,100,-1,Y=>{Y.errorCode==="net.timeout"&&M.player.FJ("capnt",{rn:O++})}).then(Y=>{if(M.policy.JR&&O%100===1){var w=(0,g.u)();
M.player.FJ("caprsp",{rn:O,ms:w-v,kb:(Y.xhr.responseText.length/1024).toFixed()})}a:{Y=Y.xhr;M.GS();if(M.O){var l=!(M.B?Y.response:Y.responseText)||Y.status>=400;if(w=g.Lag(Y)){Y=g.Uz(M.O,M.policy,{});M.O.mL(Y,w);ovi(M,M.O);break a}l?M.player.FJ("capfail",{status:Y.status}):(g.Rn("fcb_r",(0,g.u)(),M.player.getVideoData()?.Y||""),w=M.O.ZL[0],l=w.fo,M.D!=null&&M.A!==l&&(M.B?M.D(Y.response,(w.segmentStartTime+M.player.oy())*1E3):M.D(Y.responseText,(w.segmentStartTime+M.player.oy())*1E3),M.A=l))}M.O=
null;M.K=null}}).e4(Y=>{M.O=null;
M.K=null;M.player.FJ("capfail",{rn:O,status:Y.xhr?.status})});
M.O=U;vvH(M.S,M.O.ZL[0].fo)},w34=function(M,U){return U!=null&&U in M.K.Z?M.K.Z[U]:null},lrQ=function(M,U,N){var m=[];
for(let O in M.K.Z){if(!M.K.Z.hasOwnProperty(O))continue;let v=M.K.Z[O];if(g.yW(v,N||null)){let Y=v.info.captionTrack;Y&&Y.languageCode===U&&m.push(v)}}return m.length?m[0]:null},coJ=function(M,U){var N=[];
for(let O in M.K.Z){if(!M.K.Z.hasOwnProperty(O))continue;var m=M.K.Z[O];if(g.yW(m,U||null)){let v=m.info.id,Y=v,w=`.${v}`,l="",c="";if(m=m.info.captionTrack)v=m.languageCode,Y=m.displayName,w=m.vssId,l=m.kind,c=m.id;N.push(new g.iP({id:O,languageCode:v,languageName:Y,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:l,captionId:c}))}}return N},SjF=function(M,U,N,m){var O=U/360*16;
U>=M&&(M=640,m>N*1.3&&(M=480),O=N/M*16);return O},yoi=function(M){var U=1+.25*(M.fontSizeIncrement||0);
if(M.offset===0||M.offset===2)U*=.8;return U},EvJ=function(M,U){var N="vertical-rl";
M.Z.MP===1&&(N="vertical-lr");g.Q_&&(N=N==="vertical-lr"?"tb-lr":"tb-rl");g.KK(U,"-o-writing-mode",N);g.KK(U,"-webkit-writing-mode",N);g.KK(U,"writing-mode",N);g.KK(U,"text-orientation","upright");g.Gu(U,"ytp-vertical-caption");M.K.params.Lm===3&&(g.KK(U,"text-orientation",""),g.KK(U,"transform","rotate(180deg)"))},LGD=function(M,U){var N={},m=U.background?U.background:M.Z.q9.background;
if(U.backgroundOpacity!=null||U.background){var O=U.backgroundOpacity!=null?U.backgroundOpacity:M.Z.q9.backgroundOpacity;m=LA(m);N.background="rgba("+m[0]+","+m[1]+","+m[2]+","+O+")";M.DQ&&(N["box-decoration-break"]="clone",N["border-radius"]=`${M.Jz*.375}px`)}if(U.fontSizeIncrement!=null||U.offset!=null)N["font-size"]=`${M.r6*yoi(U)}px`;m=1;O=U.color||M.Z.q9.color;if(U.color||U.textOpacity!=null)O=LA(O),m=U.textOpacity==null?M.Z.q9.textOpacity:U.textOpacity,O="rgba("+O[0]+","+O[1]+","+O[2]+","+m+
")",N.color=O,N.fill=O;var v=U.charEdgeStyle;v===0&&(v=void 0);if(v){O=`rgba(34, 34, 34, ${m})`;let l=`rgba(204, 204, 204, ${m})`;U.Fa&&(l=O=U.Fa);let c=M.r6/16/2,S=Math.max(c,1);var Y=Math.max(2*c,1),w=Math.max(3*c,1);let y=Math.max(5*c,1);m=[];switch(v){case 4:for(;w<=y;w+=c)m.push(`${Y}px ${Y}px ${w}px ${O}`);break;case 1:Y=window.devicePixelRatio>=2?.5:1;for(v=S;v<=w;v+=Y)m.push(`${v}px ${v}px ${O}`);break;case 2:m.push(`${S}px ${S}px ${l}`);m.push(`-${S}px -${S}px ${O}`);break;case 3:for(w=0;w<
5;w++)m.push(`0 0 ${Y}px ${O}`)}N["text-shadow"]=m.join(", ")}O="";switch(U.fontFamily){case 1:O='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:O='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:O='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:O='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:O='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:O=g.dQ()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:O='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}O&&(N["font-family"]=O);O=U.offset;O==null&&(O=M.Z.q9.offset);switch(O){case 0:N["vertical-align"]="sub";break;case 2:N["vertical-align"]="super"}U.fontFamily===7&&(N["font-variant"]="small-caps");U.bold&&(N["font-weight"]="bold");U.italic&&(N["font-style"]="italic");U.underline&&
(N["text-decoration"]="underline");U.aC&&(N.visibility="hidden");U.yj===1&&M.S&&(N["text-combine-upright"]="all",N["text-orientation"]="mixed",O=g.jP||g.St,M.K.params.Lm===3?N.transform=O?"rotate(90deg)":"rotate(180deg)":O&&(N.transform="rotate(-90deg)"));if(U.textEmphasis===1||U.textEmphasis===2||U.textEmphasis===3||U.textEmphasis===4||U.textEmphasis===5)if(g.jP)N["font-weight"]="bold";else switch(N["text-emphasis-style"]="filled circle",N["text-emphasis-color"]="currentcolor",N["webkit-text-emphasis"]=
"filled circle",U.textEmphasis){case 4:case 3:N["text-emphasis-position"]="under left";N["webkit-text-emphasis-position"]="under left";break;case 5:case 2:N["text-emphasis-position"]="over right",N["webkit-text-emphasis-position"]="over right"}return N},eOG=function(M,U){if(M.jw&&U.length===0)return 0;
M=1;for(let N=0;N<U.length;N++){let m=U[N];typeof m.text==="string"&&(M+=m.text.split("\n").length-1,m.append||N===0||M++)}return M},Av=function(M){M=M.split("px");
return M.length>0?(M=Number(M[0]))?M:0:0},P9F=function(M,U,N){M.ML=M.ML||!!N;
var m={};Object.assign(m,M.Z.q9);Object.assign(m,N||U.Z);Object.assign(m,M.dh.q9);(N=!M.B)&&Aoi(M);var O=M.sM&&M.Wv&&g.fi(m,M.Wv)?M.sM:WGH(M,m),v=typeof U.text==="string",Y=v?U.text.split("\n"):[U.text];for(let l=0;l<Y.length;l++){var w=l>0||!U.append;let c=Y[l];w&&!N?(Aoi(M),O=WGH(M,m)):w&&N&&(N=!1);c&&(O.appendChild(v?g.o8(c):c),v||c.tagName!=="RUBY"||c.childElementCount!==4||g.jP||!g.QA(c.children[2],"text-emphasis")||(w=M.S?"padding-right":"padding-top",g.QA(c.children[2],"text-emphasis-position")&&
(w=M.S?"padding-left":"padding-bottom"),g.Ua?g.KK(O,w,"1em"):g.KK(O,w,"0.5em")))}M.Wv=m;M.sM=O;M.V.push(U)},Aoi=function(M){if(M.B){var U=M.B;
if(M.DQ){var N=M.Z.textAlign;N===0?(U=U.firstElementChild)&&g.KK(U,{"border-bottom-left-radius":"0"}):N===1&&(U=U.lastElementChild)&&g.KK(U,{"border-bottom-right-radius":"0"})}}M.B=g.YY("SPAN");g.KK(M.B,{display:"block"});g.Gu(M.B,"caption-visual-line");M.O.appendChild(M.B)},WGH=function(M,U){var N=g.YY("SPAN");
g.KK(N,{display:"inline-block","white-space":"pre-wrap"});g.KK(N,LGD(M,U));N.classList.add("ytp-caption-segment");M.B.appendChild(N);M.DQ&&M.O.children.length>1&&(M=M.Z.textAlign,M===0?N.previousElementSibling||g.KK(N,{"border-top-left-radius":"0"}):M===1&&g.KK(N,{"border-top-right-radius":"0"}));N.previousElementSibling&&(g.KK(N.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.KK(N,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return N},
p3N=function(M,U,N){if(M===255&&U===255||!M&&!U)return{sx:M,
Pi:U,result:0};M=C9j[M];U=C9j[U];if(M&128){var m;if(m=!(U&128))m=U,m=N.fg()&&N.Pi===m;if(m)return{sx:M,Pi:U,result:1}}else if(U&128&&1<=M&&M<=31)return{sx:M,Pi:U,result:2};return{sx:M,Pi:U,result:3}},arj=function(M,U,N,m){U===255&&N===255||!U&&!N?(++M.O===45&&M.reset(),M.S.K.clear(),M.B.K.clear()):(M.O=0,Zwn(M.S,U,N,m))},FGj=function(M,U){M.Z.sort((N,m)=>{var O=N.time-m.time;
return O===0?N.order-m.order:O});
for(let N of M.Z)M.time=N.time,N.type===0?arj(M,N.pF,N.ef,U):N.type===1&&M.K&496&&Zwn(M.B,N.pF,N.ef,U);M.Z.length=0},nvQ=function(M,U){switch(M){case 0:return BiG[(U&127)-32];
case 1:return qju[U&15];case 2:return D2J[U&31];case 3:return zOO[U&31]}return 0},W9=function(M,U){if(M.style.type===3){var N=0,m=0,O=M.B.time+0,v="",Y="",w=O;
for(var l=1;l<=15;++l){var c=!1;for(var S=m?m:1;S<=32;++S){var y=M.O[l][S];if(y.Z!==0){N===0&&(N=l,m=S);c=String.fromCharCode(y.Z);var E=y.timestamp;E<O&&(O=E);y.timestamp=w;Y&&(v+=Y,Y="");v+=c;c=!0}if((y.Z===0||S===32)&&c){Y="\n";break}else if(m&&!c)break}if(N&&!c)break}v&&U.S(N,m,O,w,v)}else for(m=N=0,v=O=M.B.time+0,Y=1;Y<=15;++Y)for(w="",l=1;l<=32;++l)if(S=M.O[Y][l],y=S.Z,y!==0&&(N===0&&(N=Y,m=l),c=String.fromCharCode(y),E=S.timestamp,E<=O&&(O=E),w+=c,S.reset()),l===32||y===0)w&&U.S(N,m,O,v,w),
O=v,w="",m=N=0},P9=function(M){return M.O[M.row][M.K]},CA=function(M,U,N){U>=2&&M.K>1&&(--M.K,P9(M).Z=0);
var m=P9(M);m.timestamp=M.B.time+0;m.Z=nvQ(U,N);M.K<32&&M.K++},hOi=function(M,U,N,m){for(let Y=0;Y<m;Y++)for(let w=0;w<=32;w++){var O=M.O[U+Y][w],v=M.O[N+Y][w];
O.Z=v.Z;O.timestamp=v.timestamp}},pA=function(M,U,N){for(let m=0;m<N;m++)for(let O=0;O<=32;O++)M.O[U+m][O].reset()},Zo=function(M){M.row=M.Z>0?M.Z:1;
M.K=1;pA(M,0,15)},GcJ=function(M){M.style.set(1);
M.Z=M.S;M.Z.Z=0;M.Z.style=M.style;M.O.mode=1<<M.Z.S},aZ=function(M,U,N){var m=M.K,O=!1;
switch(M.style.get()){case 4:case 1:case 2:M.style.get()===4&&m.Z>0||(W9(m,N),Zo(M.K),Zo(M.S),m.row=15,m.Z=U,O=!0)}M.style.set(3);M.Z=m;M.Z.style=M.style;M.O.mode=1<<m.S;O?m.K=1:m.Z!==U&&(m.Z>U?(W9(m,N),pA(m,m.row-m.Z,U)):m.row<U&&(U=m.Z),m.Z=U)},jOH=function(M){M.style.set(4);
M.Z=M.text;M.Z.style=M.style;M.O.mode=1<<M.Z.S},Zwn=function(M,U,N,m){M.K.update();
U=p3N(U,N,M.K);switch(U.result){case 0:return;case 1:case 2:return}var O=U.sx;U=U.Pi;if(32<=O||!O)M.Z.mode&M.Z.K&&(N=O,N&128&&(N=127),U&128&&(U=127),M=M.S.Z,N&96&&CA(M,0,N),U&96&&CA(M,0,U),N!==0&&U!==0&&M.style.type===3&&W9(M,m));else if(O&16)a:if(!M.K.matches(O,U)&&(N=M.K,N.sx=O,N.Pi=U,N.state=2,N=O&8?M.A:M.O,M.S=N,M.Z.mode=1<<(M.B<<2)+(N.B<<1)+(N.style.type===4?1:0),(M.Z.mode|1<<(M.B<<2)+(N.B<<1)+(N.style.type!==4?1:0))&M.Z.K))if(U&64){m=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(O&7)<<1|U>>5&1];
M=U&16?((U&14)>>1)*4:0;U=N.Z;switch(N.style.get()){case 4:m=U.row;break;case 3:if(m!==U.row){if(m<U.Z&&(m=U.Z,m===U.row))break;var v=1+U.row-U.Z;let Y=1+m-U.Z;hOi(U,Y,v,U.Z);N=v;O=U.Z;Y<v?(v=Y+O-v,v>0&&(N+=v,O-=v)):(v=v+O-Y,v>0&&(O-=v));pA(U,N,O)}}U.row=m;U.K=M+1}else switch(O&7){case 1:switch(U&112){case 32:CA(N.Z,0,32);break a;case 48:U===57?(m=N.Z,P9(m).Z=0,m.K<32&&m.K++):CA(N.Z,1,U&15)}break;case 2:U&32&&CA(N.Z,2,U&31);break;case 3:U&32&&CA(N.Z,3,U&31);break;case 4:case 5:if(32<=U&&U<=47)switch(U){case 32:GcJ(N);
break;case 33:m=N.Z;m.K>1&&(--m.K,P9(m).Z=0);break;case 36:m=N.Z;M=P9(m);for(U=0;U<=15;U++)for(N=0;N<=32;N++)if(m.O[U][N]===M){for(;N<=32;N++)m.O[U][N].reset();break}break;case 37:aZ(N,2,m);break;case 38:aZ(N,3,m);break;case 39:aZ(N,4,m);break;case 40:CA(N.Z,0,32);break;case 41:m=N;m.style.set(2);m.Z=m.K;m.Z.Z=0;m.Z.style=m.style;m.O.mode=1<<m.Z.S;break;case 42:m=N;M=m.text;M.Z=15;M.style.set(4);Zo(M);jOH(m);break;case 43:jOH(N);break;case 44:M=N;U=M.K;switch(M.style.get()){case 1:case 2:case 3:W9(U,
m)}pA(U,0,15);break;case 45:b:{U=N;M=U.Z;switch(U.style.get()){default:case 2:case 1:break b;case 4:if(M.row<15){++M.row;M.K=1;break b}break;case 3:}M.Z<2&&(M.Z=2,M.row<M.Z&&(M.row=M.Z));U=M.row-M.Z+1;W9(M,m);hOi(M,U,U+1,M.Z-1);pA(M,M.row,1)}break;case 46:pA(N.S,0,15);break;case 47:M=N,W9(M.K,m),M.S.updateTime(M.O.time+0),m=M.S,M.S=M.K,M.K=m,GcJ(M)}break;case 7:switch(U){case 33:case 34:case 35:m=N.Z,(m.K+=U&3)>32&&(m.K=32)}}},roG=function(M,U,N,m,O,v,Y){var w=v[0],l=Y[w.getAttribute("p")];
if(l.iH===1){var c=v[1],S=v[2];v=v[3];w.getAttribute("t");c.getAttribute("t");S.getAttribute("t");v.getAttribute("t");w.getAttribute("p");c.getAttribute("p");v.getAttribute("p");Y=Y[S.getAttribute("p")];w=TiQ(w.textContent,c.textContent,S.textContent,v.textContent,Y);return new FN(M,U,O,N,w,m,l)}switch(l.iH){case 9:case 10:l.textEmphasis=1;break;case 11:l.textEmphasis=2;break;case 12:l.textEmphasis=3;break;case 13:l.textEmphasis=4;break;case 14:l.textEmphasis=5}return new FN(M,U,O,N,w.textContent||
"",m,l)},TiQ=function(M,U,N,m,O){var v=g.dQ(),Y=v?g.YY("DIV"):g.YY("RUBY"),w=g.YY("SPAN");
w.textContent=M;Y.appendChild(w);M=v?g.YY("DIV"):g.YY("RP");M.textContent=U;Y.appendChild(M);U=v?g.YY("DIV"):g.YY("RT");U.textContent=N;Y.appendChild(U);N=O.iH;if(N===10||N===11||N===12||N===13||N===14)if(g.KK(U,"text-emphasis-style","filled circle"),g.KK(U,"text-emphasis-color","currentcolor"),g.KK(U,"webkit-text-emphasis","filled circle"),O.iH===11||O.iH===13)g.KK(U,"webkit-text-emphasis-position","under left"),g.KK(U,"text-emphasis-position","under left");N=!0;if(O.iH===4||O.iH===7||O.iH===12||
O.iH===14)g.KK(Y,"ruby-position","over"),g.KK(Y,"-webkit-ruby-position","before");else if(O.iH===5||O.iH===6||O.iH===11||O.iH===13)g.KK(Y,"ruby-position","under"),g.KK(Y,"-webkit-ruby-position","after"),N=!1;O=v?g.YY("DIV"):g.YY("RP");O.textContent=m;Y.appendChild(O);v&&(m=N,g.KK(Y,{display:"inline-block",position:"relative"}),v=Y.firstElementChild.nextElementSibling,g.KK(v,"display","none"),v=v.nextElementSibling,g.KK(v,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.KK(Y.lastElementChild,"display","none"),m?(g.KK(Y,"padding-top","0.6em"),g.KK(v,"top","0")):(g.KK(Y,"padding-bottom","0.6em"),g.KK(v,"bottom","0")));return Y},KGi=function(M){var U="_"+B9++;
return new qa(0,0x8000000000000,0,U,M)},Do=function(M,U){M=M.getAttribute(U);
if(M!=null)return Number(M)},zM=function(M,U){M=M.getAttribute(U);
if(M!=null)return M==="1"},nA=function(M,U){M=Do(M,U);
return M!==void 0?M:null},GM=function(M,U){M=M.getAttribute(U);
if(M!=null)return hv.test(M),M},Hwn=function(M,U){var N={},m=U.getAttribute("ws");
Object.assign(N,m?M.Y[m]:M.S);M=nA(U,"mh");M!=null&&(N.YK=M);M=nA(U,"ju");M!=null&&(N.textAlign=M);M=nA(U,"pd");M!=null&&(N.Lm=M);M=nA(U,"sd");M!=null&&(N.MP=M);M=GM(U,"wfc");M!=null&&(N.windowColor=M);U=Do(U,"wfo");U!==void 0&&(N.windowOpacity=U/255);return N},kcu=function(M,U){var N={},m=U.getAttribute("wp");
m&&Object.assign(N,M.D[m]);M=nA(U,"ap");M!=null&&(N.Xb=M);M=Do(U,"cc");M!=null&&(N.Bi=M);M=Do(U,"ah");M!=null&&(N.oI=M);M=Do(U,"rc");M!=null&&(N.dH=M);U=Do(U,"av");U!=null&&(N.Wl=U);return N},x2O=function(M,U,N,m){var O={};
Object.assign(O,kcu(M,U));Object.assign(O,Hwn(M,U));m?g.fi(O,M.S)?(m=M.B,O=M.S):m="_"+B9++:m=U.getAttribute("id")||"_"+B9++;M=Do(U,"t")+N;U=Do(U,"d")||0x8000000000000;if(O.Lm===2||O.Lm===3)N=O.dH,O.dH=O.Bi,O.Bi=N;return new qa(M,U,0,m,O)},jS=function(M){M=g.nF(Math.round(M),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-M.length)+M},QOj=function(M,U,N,m,O){m===0&&(m=0x8000000000000);
var v={};U.wpWinPosId&&Object.assign(v,M.S.get(U.wpWinPosId));U.wsWinStyleId&&Object.assign(v,M.B.get(U.wsWinStyleId));M=U.rcRowCount;M!==void 0&&(v.dH=M);U=U.ccColCount;U!==void 0&&(v.Bi=U);if(v.Lm===2||v.Lm===3)U=v.dH,v.dH=v.Bi,v.Bi=U;return new qa(N,m,0,O,v)},TM=function(M){var U=M.byteOffset;
M.byteOffset+=1;return M.Z.getUint8(U)},rF=function(M){var U=M.byteOffset;
M.byteOffset+=4;return M.Z.getUint32(U)},uU4=function(M){if(typeof M==="string")return!1;
M=new bwJ(M,0);return X37(M)},X37=function(M){if(!(M.byteOffset<M.Z.byteLength)||rF(M)!==1380139777)return!1;
M.version=TM(M);if(M.version>1)return!1;TM(M);TM(M);TM(M);return!0},Irn=function(M,U){if(!U)return"";
M.S&&M.K.params.MP!==1&&(U*=-1);return`translate${M.S?"X":"Y"}(${U}px)`},sON=function(M){M.Sw=Array.from(M.element.getElementsByClassName("caption-visual-line"));
for(var U=M.K.params.dH,N=0,m=0,O=M.Sw.length-1;N<U&&O>-1;){var v=M.Sw[O];m+=M.S?v.offsetWidth:v.offsetHeight;N++;O--}M.ZQ=m;U=Math;N=U.max;isNaN(M.d6)&&((m=M.Z.Bi)?(O=g.YY("SPAN"),g.Ea(O,"\u2013".repeat(m)),g.KK(O,LGD(M,M.Z.q9)),M.O.appendChild(O),M.d6=O.offsetWidth,M.O.removeChild(O)):M.d6=0);m=M.O;M.b0=N.call(U,M.d6,M.gK,(M.S?m.offsetHeight:m.offsetWidth)+1)},$2H=function(M,U){sON(M);
var N=M.Sw.reduce((m,O)=>(M.S?O.offsetWidth:O.offsetHeight)+m,0);
N=M.ZQ-N;if(N!==M.VT){let m=N>0&&M.VT===0,O=N<M.VT;U||isNaN(N)||m||!O||(g.Gu(M.element,"ytp-rollup-mode"),M.U(M.element,"transitionend",M.hz));g.KK(M.O,"transform",Irn(M,N));M.VT=N}sON(M)},JoD=function(M,U,N,m){var {formatId:O,
fo:v,startTimeMs:Y,durationMs:w}=M.ZX(U),l={formatId:O,startTimeMs:Y,durationMs:w,dX:v,tX:v},c=iw7(M.VZ,l.startTimeMs),S=c>=0?M.VZ[c]:null,y=S?S.startTimeMs+S.durationMs:0,E=l.startTimeMs+l.durationMs;!S||l.startTimeMs-y>M.S?M.VZ.splice(c+1,0,l):(S.durationMs=Math.max(y,E)-S.startTimeMs,S.tX=Math.max(S.tX,l.tX));m(M.VZ);m=g.wt(U);M=M.B;m=m.buffer.slice(m.byteOffset,m.byteLength+m.byteOffset);U=U.info.S;M.b0?M.D==null?g.Oc(M.logger,350058965,"Null loaded track meta data at captions data received"):
N.Db(m,M.D,U*1E3):g.Oc(M.logger,350058965,"Null Representation at captions data received")},frJ=function(M,U){M.K=(N,m)=>{if(M.C.J().experiments.cv("html5_sabr_live_support_subfragmented_captions"))(M.Z?M.Z=M.Z.B(N):(M.Z=N,tyQ(M.Z)),M.Z)?N.info.lK&&(ROD(M.Z),JoD(M,M.Z,U,m),M.Z=null):g.Oc(M.logger,350058965,"Empty slice");
else if(N.info.lK){var O=N;if(M.Fy.length>0){for(O=M.Fy.shift();M.Fy.length>0;)O=O?.B(M.Fy.shift());O=O?.B(N)}O?(tyQ(O),ROD(O),JoD(M,O,U,m)):g.Oc(M.logger,350058965,"Empty slice")}else M.Fy.push(N)};
M.C.addEventListener("sabrCaptionsDataLoaded",M.K)},iw7=function(M,U){M=g.q4(M,{startTimeMs:U},(N,m)=>N.startTimeMs-m.startTimeMs);
return M>=0?M:-M-2},tyQ=function(M){try{var U=g.Sm(M)*1E3}catch(N){U=M.info.segmentStartTime*1E3}U<0&&(U=M.info.segmentStartTime*1E3);
M.info.segmentStartTime=U/1E3;M.info.S=U/1E3},ROD=function(M){try{var U=g.kKg(M)*1E3}catch(N){U=M.info.O*1E3}U<0&&(U=M.info.O*1E3);
M.info.O=U/1E3;M.info.D=U/1E3},d2u=function(M,U){if(!g.Gg4(M)||M.Z!=null&&g.Sz(U,M.Z)&&M.Z.Z.rawcc!=null)return!1;
U=!!M.Z&&M.Z.isManifestless&&Object.values(M.Z.Z).some(N=>g.yW(N,"386"));
M=!!M.Z&&!M.Z.isManifestless&&g.Kad(M.Z);return U||M},VyF=function(M,U,N){var m=[];
for(let O in M.K.Z){if(!M.K.Z.hasOwnProperty(O))continue;let v=M.K.Z[O];if(g.yW(v,N||null)){let Y=v.info.captionTrack;Y&&Y.languageCode===U&&m.push(v)}}return m.length?m[0]:null},gMj=function(M,U){var N=[];
for(let O in M.K.Z){if(!M.K.Z.hasOwnProperty(O))continue;var m=M.K.Z[O];if(g.yW(m,U||null)){let v=m.info.id,Y=v,w=`.${v}`,l="",c="";if(m=m.info.captionTrack)v=m.languageCode,Y=m.displayName,w=m.vssId,l=m.kind,c=m.id;N.push(new g.iP({id:O,languageCode:v,languageName:Y,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:l,captionId:c}))}}return N},UiO=function(M){var U=MU4.length;
if(M.byteLength<U)return!1;M=new Uint8Array(M,0,U);for(let N=0;N<U;N++)if(MU4[N]!==M[N])return!1;return!0},KA=function(M){M=M.split(":");
var U=0;for(let N of M)U=U*60+Number(N);return U*1E3},NYQ=function(M,U,N,m){m=Object.assign({YK:0},m);
return new qa(M,U,N,"_"+B9++,m)},miD=function(M,U,N,m,O,v,Y,w,l){switch(Y.tagName){case "b":w.bold=!0;
break;case "i":w.italic=!0;break;case "u":w.underline=!0}for(let S=0;S<Y.childNodes.length;S++){var c=Y.childNodes[S];if(c.nodeType===3)c=new FN(U,N,m,O.id,c.nodeValue,v||S>0,g.JH(w)?void 0:w),l.push(c),O.Z.push(c);else{let y={};Object.assign(y,w);miD(M,U,N,m,O,!0,c,y,l)}}},vM7=function(M,U,N){if(typeof U==="string"||uU4(U))return[{trackData:U,
RN:N}];if(typeof U==="string"&&U.substring(0,6)==="WEBVTT"||typeof U!=="string"&&UiO(U))return[{trackData:U,RN:N}];var m=new DataView(U);if(m.byteLength<=8||m.getUint32(4)!==1718909296)return[];var O=g.tvu(m);if(M.wK&&O){var v=g.Qjj(O),Y=g.bc0(O);O=O.segmentNumber;v&&O&&M.wK.mO(O,v,Y)}M=g.Ln(m,1835295092);if(!M||!M.length||!M[0].size)return[];v=[];for(Y=0;Y<M.length;Y++)O=M[Y],O=new Uint8Array(U,O.dataOffset,O.size-(O.dataOffset-O.offset)),O=g.Yx(O),v.push({trackData:O,RN:N+Y*1E3});O4J(m,v,N);return v=
v.filter(w=>!!w.trackData)},oMu=function(M,U,N){M.Z||(M.Z=new YEa);
M=M.Z.O(U,N);Math.random()<.01&&g.tC(Error("Deprecated subtitles format in web player: WebVTT"));return M},O4J=function(M,U,N){var m=g.lK(M,0,1836476516),O=9E4;
m&&(O=g.c1(m)||9E4);m=0;var v=g.Ln(M,1836019558);for(let w=0;w<v.length;w++){var Y=v[w];w<U.length&&(Y=g.lK(M,Y.dataOffset,1953653094))&&(Y=g.lK(M,Y.dataOffset,1952867444))&&(Y=g.E$(Y)/O*1E3,w===0&&(m=Y),U[w].RN=Y-m+N||N*w*1E3)}},wgN=function(M){var U={};
if(M=g.T2(M))U.lang=M,g.XYc.test(M)&&(U.Lm=1);return U},H9=function(M){return M.O==="HLS"&&M.zb?!0:M.sM&&M.zb&&M.O!=="LIVE"&&M.O!=="SABR_LIVE"},lFa=function(M){return!M.S&&M.sM&&M.jw&&(M.O==="LIVE"||M.O==="SABR_LIVE")},kW=function(M,U,N=!1){var m=M.j.G("enable_player_captions_new_style_defaults")?cXJ:SEO,O=m.q9;
M.B={};Object.assign(M.B,m);M.B.q9={};Object.assign(M.B.q9,O);M.A={q9:{}};var v=U.backgroundOverride?M.A:M.B,Y=U.background||O.background;hv.test(Y);v.q9.background=Y;v=U.colorOverride?M.A:M.B;Y=U.color||O.color;hv.test(Y);v.q9.color=Y;v=U.windowColorOverride?M.A:M.B;Y=U.windowColor||m.windowColor;hv.test(Y);v.windowColor=Y;v=U.backgroundOpacityOverride?M.A:M.B;Y=U.backgroundOpacity;Y==null&&(Y=O.backgroundOpacity);v.q9.backgroundOpacity=Y;v=U.fontSizeIncrementOverride?M.A:M.B;Y=U.fontSizeIncrement;
Y==null&&(Y=O.fontSizeIncrement);v.q9.fontSizeIncrement=Y;Y=U.fontStyleOverride?M.A:M.B;v=U.fontStyle;v==null&&(v=O.bold&&O.italic?3:O.bold?1:O.italic?2:0);Y=Y.q9;switch(v){case 1:Y.bold=!0;delete Y.italic;break;case 2:delete Y.bold;Y.italic=!0;break;case 3:Y.bold=!0;Y.italic=!0;break;default:delete Y.bold,delete Y.italic}v=U.textOpacityOverride?M.A:M.B;Y=U.textOpacity;Y==null&&(Y=O.textOpacity);v.q9.textOpacity=Y;v=U.windowOpacityOverride?M.A:M.B;Y=U.windowOpacity;Y==null&&(Y=m.windowOpacity);v.windowOpacity=
Y;m=U.charEdgeStyleOverride?M.A:M.B;v=U.charEdgeStyle;v==null&&(v=O.charEdgeStyle);m.q9.charEdgeStyle=v;m=U.fontFamilyOverride?M.A:M.B;v=U.fontFamily;v==null&&(v=O.fontFamily);m.q9.fontFamily=v;M.loaded&&M.EM();N&&g.KJ("yt-player-caption-display-settings",U,2592E3)},xW=function(M,U,N){U&&!M.OM?(U=KGi({Lm:0,
lang:"en"}),M.OM=[U,new FN(U.start,U.end-U.start,0,U.id,N??"Captions look like this")],M.player.ek(M.OM)):!U&&M.OM&&(yXN(M,M.OM),M.OM=null)},Lsu=function(M){if(M.j.G("enable_player_captions_persistence_state_machine")){var U=g.H8("yt-player-caption-persistence");
if(U==null){let N=g.JC().yT(65);if(N===!0)U=!1;else{let m=g.qN(M.j)?Qw(M):EMN(M);m!=null?U=!!m:N===!1&&(U=!0)}U!==void 0&&bN(M,U)}return U}},Qw=function(M){if(!M.C.isInline())return g.H8("yt-player-sticky-caption")},EMN=function(M){if(!M.storage)return null;
try{var U=M.storage.get("module-enabled")}catch(N){M.storage.remove("module-enabled")}return U},XN=function(M){if(M.j.G("enable_player_captions_persistence_state_machine"))return Lsu(M);
var U=void 0,N=g.JC().yT(65);if(g.qN(M.j)&&N!=null){if(Qw(M)!=null)return!1;U=!N}return U},eki=function(M){if(M.j.FZ===1||M.videoData.by===1||g.Y6(M.videoData,"yt:cc")==="alwayson")return!0;
if(M.videoData.captionTracks.length)var U=M.getAudioTrack().K;if(M.j.G("enable_player_captions_persistence_state_machine")){var N=Lsu(M);if(N!==void 0)return!!N}else if(M.j.FZ===2&&(g.qN(M.j)?N=Qw(M):N=EMN(M),N!=null))return!!N;N=Eq(M.player.getAudioTrack(),g.qN(M.j));var m=g.Y6(M.videoData,"yt:cc");if(XN(M)===void 0){if(N==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return m?m==="on":!0;if(N==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return m==="on"}else return m==="on";return U==="ON"||g.Y6(M.videoData,
"yt:cc")==="on"},uN=function(M,U=!1){if(M.K&&!U||!M.videoData.captionTracks.length)return!1;
M=M.getAudioTrack();return!!M.Z||M.K==="FORCED_ON"},AXj=function(M,U){if(M.K){var N=M.C.T$().BV().textTracks,m=null;
M.O==="HLS"?m=M.K.getId():m=M.K.toString();for(let v=0;v<N.length;v++){var O=N[v];O.id===m&&(U?O.mode!=="showing"&&(O.mode="showing",O=M.K,M.QG(O,!!O,IZ(M)?"g":M.V?"m":"s")):O.mode==="showing"&&(O.mode="disabled"))}}},IZ=function(M){var U=sq(M);
return!!U&&M.K===U},Ws7=function(M,U){if(M.O==="HLS")return!1;
g.Lf(M.videoData)&&(U=!0);U||(U=M.O==="TTS"?!1:M.O==="INNERTUBE"?!1:!0);return U||M.j.G("web_watch_disable_account_level_captions_settings")&&g.qN(M.j)?!0:!!g.JC().yT(66)},sq=function(M){return M.Y&&M.Y.Z},$W=function(M,U){if(!M.Z)return null;
if(M.Y&&M.Y.S)return M.Y.S;U=Ws7(M,U);U=g.IA(M.Z.Z,U);var N=null;if(gvO(M.j)){var m=M.C.isInline()?void 0:g.H8("yt-player-caption-sticky-language");var O=[m,M.videoData.captionsLanguagePreference,M.j.captionsLanguagePreference,g.Y6(M.videoData,"yt:cc_default_lang")];let w=!1;for(let l=0;l<O.length;l++){let c=O[l];if(c){w=!0;for(var v=0;v<U.length;v++)if(g.T2(U[v])===c)return U[v];for(v=0;v<U.length;v++)if(g.T2(U[v]).split("-")[0]===c.split("-")[0])return U[v]}}if(w&&M.Z&&(O=M.Z.Y,O.length))for(var Y of O)if(Y.languageCode===
m){N=Y;break}}else for(Y=[M.videoData.captionsLanguagePreference,M.j.captionsLanguagePreference,g.Y6(M.videoData,"yt:cc_default_lang")],m=0;m<Y.length;m++)for(O=0;O<U.length;O++)if(g.T2(U[O])===Y[m])return U[O];Y=null;M.Y&&M.Y.O&&(Y=M.Y.O);Y||(Y=U.find(w=>w.isDefault)||null);
Y||(Y=U[0]||sq(M));Y&&N&&g.T2(Y).split("-")[0]!==N.languageCode.split("-")[0]&&(Y=V5u(Y,N));return Y},RZ=function(M,U,N){M.loaded&&M.unload();
N!=null&&(M.V=N,M.V&&(M.j.G("enable_player_captions_persistence_state_machine")?bN(M,!!U):g.qN(M.j)?iN(M,!!U):Jv(M,!!U)));U!==null||uN(M,!0)||M.QG(U,!!U,M.V?"m":"s");M.K=U;uN(M)&&(M.K=sq(M));tv(M,M.K??void 0);M.load()},bN=function(M,U){M.j.G("enable_player_captions_persistence_state_machine")&&g.KJ("yt-player-caption-persistence",U,3122064E3)},iN=function(M,U){M.C.isInline()||g.KJ("yt-player-sticky-caption",U,2592E3)},Jv=function(M,U){if(M.storage)try{M.storage.set("module-enabled",U)}catch(N){}},
tv=function(M,U){M.j.G("html5_modify_caption_vss_logging")&&(M.videoData.k8=U)},Cbi=function(M,U){var N=M.u0[U.id];
N&&N.K!==U&&(N.dispose(),delete M.u0[U.id],N=null);N||(N=PbF(M,U))&&(M.u0[U.id]=N)},pgJ=function(M,U){var N=U.windowId;
M.DQ[N]||(M.DQ[N]=[]);M.DQ[N].push(U)},PbF=function(M,U){var N=Z4j(M);
if(!N)return null;var m=M.K?g.T2(M.K):null;m&&g.XYc.test(m)&&(U.params.Lm=1);var O=M.hz.getPlayerSize();m=O.height*M.b0.height;O=O.width*M.b0.width;M.j.playerStyle!=="google-live"||M.B.isDefault||Object.assign(U.params,M.B);switch(U.params.YK!=null?U.params.YK:U.Z.length>1?1:0){case 1:return new aFn(U,M.B,M.A,N.width,N.height,O,m,M.j.experiments,M.Jz.bind(M),M.C);case 2:return new Fsu(U,M.B,M.A,N.width,N.height,O,m,M.j.experiments,M.Jz.bind(M),M.C);default:return new fA(U,M.B,M.A,N.width,N.height,
O,m,M.j.experiments,M.Jz.bind(M),M.C)}},Z4j=function(M){var U=M.hz.getVideoContentRect(!0).height,N=M.hz.getVideoContentRect(!0).width;
if(!U||!N)return null;U*=M.b0.height;N*=M.b0.width;return{width:N,height:U}},yXN=function(M,U){M.player.hv(U);
for(let N of U)g.UO(M.d6,N);yw(M.ML)},BY4=function(M,U){if(!M.Z)return{};
if(U){g.JH(U)||M.o8(U.vss_id,"m");if(M.S&&M.O!=="HLS"||!g.Z3(U))return;if(g.JH(U)){RZ(M,null,!0);return}let m;var N=g.IA(M.Z.Z,!0);for(let O=0;O<N.length;O++){let v=N[O];v.languageCode!==U.languageCode||m&&(v.languageName!==U.languageName||(v.captionId||"")!==(U.captionId||"")||g.G2(v)!==U.displayName)||(m=U.translationLanguage?V5u(v,U.translationLanguage):v)}M.qd(U.position);!m||m===M.K&&M.loaded||(U=g.ql(),N=g.T2(m),U.length&&N===U[U.length-1]||(U.push(N),g.KJ("yt-player-caption-language-preferences",
U)),gvO(M.j)&&!M.C.isInline()&&g.KJ("yt-player-caption-sticky-language",N,2592E3),RZ(M,m,!0))}else return M.loaded&&M.K&&!IZ(M)?g.jw(M.K):{};return""};
g.gA.prototype.mO=g.m0(68,function(M,U,N){this.K.set(M,{vj:U,ev:N})});
g.M3.prototype.mO=g.m0(67,function(M,U,N){this.b0.mO(M,U,N)});
g.bh.prototype.ZQ=g.m0(66,function(){return!1});
g.bh.prototype.S=g.m0(65,function(){});
g.XE.prototype.S=g.m0(64,function(M,U,N){this.GS();U=this.A(M,U);var m=this.vv.J().G("html5_report_captions_ctmp_qoe"),O=(0,g.u)();this.O();dn7(this,U,{format:"RAW",onSuccess:v=>{this.K=null;if(m){var Y=(v.responseText.length/1024).toFixed();let w=(0,g.u)();this.videoData.FJ("capresp",{ms:w-O,kb:Y})}Y=v.getResponseHeader&&v.getResponseHeader("Content-Length")?Number(v.getResponseHeader("Content-Length")):0;N.Db(v.responseText,M,void 0,void 0,Y)},
onError:m?v=>{this.videoData.FJ("capfail",{status:v?.status??0})}:void 0,
withCredentials:!0})});
g.uh.prototype.S=g.m0(63,function(M,U,N){this.GS();U=this.A(M,U);this.O();this.K=g.hn(U,{format:"RAW",onSuccess:m=>{this.K=null;var O=m.getResponseHeader&&m.getResponseHeader("Content-Length")?Number(m.getResponseHeader("Content-Length")):0;N.Db(m.responseText,M,void 0,void 0,O)},
withCredentials:!0})});
g.FA.prototype.V=g.m0(62,function(){this.mediaElement.V()});
g.CL.prototype.V=g.m0(61,function(){var M=g.tY(document,"track",void 0,this.Z);for(let U=0;U<M.length;U++)g.SG(M[U])});
g.FA.prototype.ML=g.m0(60,function(){return this.mediaElement.ML()});
g.CL.prototype.ML=g.m0(59,function(){return!(!this.Z.textTracks||!this.Z.textTracks.addEventListener)});
g.FA.prototype.d6=g.m0(58,function(){return this.mediaElement.d6()});
g.CL.prototype.d6=g.m0(57,function(){return!!this.Z.textTracks});
g.FA.prototype.OM=g.m0(56,function(M){this.mediaElement.OM(M)});
g.CL.prototype.OM=g.m0(55,function(M){for(let U=0;U<M.length;U++)this.Z.appendChild(M[U])});
g.Ac.prototype.o8=g.m0(42,function(M,U){this.app.kf().o8(M,U)});
g.uT.prototype.o8=g.m0(41,function(M,U){this.Ko.o8(M,U)});
g.jQ.prototype.o8=g.m0(40,function(M,U){M=[M,U];g.eu(this,g.Py(this.provider),"cfi",M)});
g.rS.prototype.o8=g.m0(39,function(M,U){this.qoe&&this.qoe.o8(M,U)});
g.fg.prototype.o8=g.m0(38,function(M,U){this.tK.o8(M,U)});
g.Rv.prototype.o8=g.m0(37,function(){});
g.Ac.prototype.QG=g.m0(36,function(M,U,N){this.app.kf().QG(M,U,N)});
g.uT.prototype.QG=g.m0(35,function(M,U,N){this.Ko.QG(M,U,N)});
g.jQ.prototype.QG=g.m0(34,function(M,U,N){if(this.sM!==M||this.uZ!==U)U=U==="rawcc"?"":U,N=[M,U,this.sM,N],g.eu(this,g.Py(this.provider),"cfs",N),this.sM=M,this.uZ=U});
g.rS.prototype.QG=g.m0(33,function(M,U,N){this.qoe&&this.qoe.QG(M,U,N)});
g.fg.prototype.QG=g.m0(32,function(M,U,N){this.tK.QG(M,U,N)});
g.Rv.prototype.QG=g.m0(31,function(){});
g.vc.prototype.I9=g.m0(10,function(M){return(M=this.O(M))?M.Z:0});
g.ov.prototype.I9=g.m0(9,function(){return 0});
g.iP.prototype.K=g.m0(8,function(){return this.vssId});
var m24=/#(.)(.)(.)/,Ni7=/^#(?:[0-9a-f]{3}){1,2}$/i,qEj={en:"English"},Dij=class extends g.bh{constructor(M){super(M);this.K=new Set}B(M){var U=this.vv.T$();if(U&&U.BV()){U=U.BV().textTracks;for(let N of U)N.kind==="subtitles"&&!this.K.has(N.language)&&N.language&&(g.cv(this.Z,new g.iP({languageCode:N.language,languageName:N.language,kind:N.kind,id:N.id,displayName:qEj[N.label]||N.label,vss_id:`.${N.language}`})),this.K.add(N.language))}g.IA(this.Z).length>0&&M.w1()}},zkF=class{constructor(){this.segments=
[]}contains(M){M=g.q4(this.segments,M);return M>=0||M<0&&(-M-1)%2===1}length(){return this.segments.length/2}},nMO=class extends g.zc{constructor(M,U,N,m,O,v){super();this.policy=M;this.player=U;this.QT=N;this.D=m;this.B=O;this.ZQ=v;this.S=new zkF;this.A=-1;this.K=this.O=this.Z=null;this.b0=0;this.V=new g.Fy(this.OM,1E3,this);this.events=new g.Zv(this);g.D(this,this.V);g.D(this,this.events);this.events.U(U,"SEEK_COMPLETE",this.Y);this.Y();this.OM()}zS(){super.zS();this.K&&this.K.cancel()}Y(){this.seekTo(this.player.getCurrentTime())}seekTo(M){M-=
this.player.oy();var U=this.Z;this.Z=g.Qk(this.QT.A(M).ZL);U!==this.Z&&this.ZQ&&this.ZQ()}reset(){this.S=new zkF;this.A=-1;this.K&&(this.K.cancel(),this.K=null)}OM(){this.GS();var M;if(M=this.Z!=null)M=this.Z,M=M.QT.S(M);if(M&&!this.K&&!(this.Z&&this.Z.segmentStartTime-this.player.getCurrentTime()>30)){M=this.Z;M=M.QT.ML(M);let O=M.ZL[0];if(this.player.getVideoData()?.enableServerStitchedDai){var U=this.player.qb();if(U){var N=O.QT.info.id;let v=O.fo;var m=M.ZL[0].S;if(this.policy.d6){if(U=g.JNg(U,
m,v,N,3))M.S=U}else if(N=U.ub(m,v,N,3))if(m=2,U.Uw.has(v)?m=0:g.Jj(U,v)&&(m=1),U=m,U===0)N&&(M.Z=new g.EO(N));else if(U===2){this.V.start();YjJ(this)&&this.seekTo(this.player.getCurrentTime());return}}}O.QT.index.ez(O.fo)?(this.S.contains(M.ZL[0].fo)||ovi(this,M),this.Z=g.Qk(M.ZL)):YjJ(this)&&this.seekTo(this.player.getCurrentTime())}this.V.start()}},hkQ=class extends g.bh{constructor(M,U){super(U);this.K=M;this.C=U;this.D=null;this.OM=!1;this.logger=new g.mp("caps");this.b0=g.Sz(this.C,this.K)}S(M,
U,N){this.O();U=w34(this,M.getId());U||(U=M.languageCode,U=this.K.isManifestless?lrQ(this,U,"386"):lrQ(this,U));if(U){var m=(U.index.I9(U.index.tQ())-U.index.getStartTime(U.index.tQ()))*1E3,O=new g.vjJ(this.C.J());this.D=new nMO(O,this.C,U,(v,Y)=>{N.Db(v,M,Y,m)},this.b0||g.Lj(U.info),()=>{this.D&&this.D.reset();
this.OM=!0})}}ZQ(){var M=this.OM;
this.OM=!1;return M}B(M){var U=this.C.J().G("html5_fallback_if_rawcc_missing");var N=this.K.Z.rawcc!=null;if(!this.b0||!N&&U)U=this.K.isManifestless?coJ(this,"386"):coJ(this);else{if(!N){g.Oc(this.logger,386248249,"rawcc used but unavailable");return}U=[new g.iP({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.iP({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let m of U)g.cv(this.Z,
m);M.w1()}O(){this.D&&(this.D.dispose(),this.D=null)}A(){return""}},hv=/^#(?:[0-9a-f]{3}){1,2}$/i;var GwF=["left","right","center","justify"];var FN=class extends g.OH{constructor(M,U,N,m,O,v=!1,Y=null){super(M,M+U,{priority:N,namespace:"captions"});this.windowId=m;this.text=O;this.append=v;this.Z=Y}toString(){return super.toString()}};var fA=class extends g.d{constructor(M,U,N,m,O,v,Y,w,l,c){var S=c.isInline()&&!0,y={};Object.assign(y,U);Object.assign(y,M.params);Object.assign(y,N);var E={};Object.assign(E,U.q9);M.params.q9&&Object.assign(E,M.params.q9);Object.assign(E,N.q9);S&&(y.windowOpacity=.6,E.backgroundOpacity=0);y.q9=E;var L=y.Lm===1,C=[{W:"span",N:"captions-text",L:{style:"word-wrap: normal; display: block;"}}],q=w.cv("caption_edit_on_hover")&&c.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
q&&C.unshift({W:"button",N:"caption-edit",L:{tabindex:"0","aria-label":OwG()},X:[{W:"svg",L:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},X:[{W:"path",L:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({W:"div",N:"caption-window",L:{id:`caption-window-${M.id}`,dir:L?"rtl":"ltr",tabindex:"0",lang:y.lang},X:C});this.experiments=
w;this.V=[];this.ML=!1;this.K=M;this.Wv=this.sM=null;this.Kg=v;this.m$=Y;this.B=null;this.maxWidth=v*.96;this.maxHeight=Y*.96;this.Z=y;this.dh=N;this.u0=U;this.O=this.Bv("captions-text");M=this.O.style;this.DQ=w.cv("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in M||"WebkitBoxDecorationBreak"in M);this.r6=SjF(m,O,v,Y);this.B$=l;q&&(this.A=this.Bv("caption-edit"),this.U(this.A,"click",()=>{this.B$()}));
this.type=0;this.Jz=this.r6*yoi(E);this.Mh=S;this.jw=w.cv("enable_centered_caption_for_tvfilm_video")&&c.getVideoData().isTvfilmVideo;this.Y=c.J().l0().Z.yT(g.aCk);m=new g.$4(this.element,!0);g.D(this,m);m.subscribe("dragstart",this.qe,this);m.subscribe("dragmove",this.A6,this);m.subscribe("dragend",this.aP,this);this.EM=this.po=this.zb=this.uZ=0;m="";this.Z.windowOpacity&&(m=LA(this.Z.windowColor),m="rgba("+m[0]+","+m[1]+","+m[2]+","+this.Z.windowOpacity+")");O={"background-color":m,display:this.Z.isVisible===
!1?"none":"","text-align":GwF[this.Z.textAlign]};this.DQ&&(O["border-radius"]=m?`${this.Jz*.375}px`:"");(this.S=this.K.params.Lm===2||this.K.params.Lm===3)&&EvJ(this,this.element);g.KK(this.element,O);S&&this.element.parentElement?.style.setProperty("--caption-window-color",m);switch(this.Z.Xb){case 0:case 1:case 2:g.Gu(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Gu(this.element,"ytp-caption-window-bottom")}}qe(M,U){this.po=M;this.EM=U;var N=g.fK(this.element,this.element.parentElement);
this.uZ=M-N.x;this.zb=U-N.y}A6(M,U){if(M!==this.po||U!==this.EM){g.h1(this.element,"ytp-dragging")||g.Gu(this.element,"ytp-dragging");var N=g.VA(this.element);M=M-this.uZ-.02*this.Kg;var m=U-this.zb-.02*this.m$,O=(M+N.width/2)/this.maxWidth*3;O=Math.floor(g.nF(O,0,2));var v=(m+N.height/2)/this.maxHeight*3;v=Math.floor(g.nF(v,0,2));U=O+v*3;M=(M+O/2*N.width)/this.maxWidth;M=g.nF(M,0,1)*100;N=(m+v/2*N.height)/this.maxHeight;N=g.nF(N,0,1)*100;this.K.params.Xb=U;this.K.params.Wl=N;this.K.params.oI=M;this.K.params.isDefault=
!1;this.Z.Xb=U;this.Z.Wl=N;this.Z.oI=M;this.Z.isDefault=!1;this.u0.Xb=U;this.u0.Wl=N;this.u0.oI=M;this.u0.isDefault=!1;this.DL()}}aP(){g.Tu(this.element,"ytp-dragging")}DL(){this.D(this.V)}D(M){var U=this.Mh?0:Math.min(this.Ve(),this.maxWidth),N=this.rK(),m=this.Mh;if(m){var O=getComputedStyle(this.O.parentNode);O=Av(O.borderLeftWidth)+Av(O.borderRightWidth)+Av(O.paddingLeft)+Av(O.paddingRight)}else O=0;var v=O;O="";this.K.params.Lm===3&&(O="rotate(180deg)");var Y=m?`calc(96% - ${v}px)`:"96%";g.KK(this.element,
{top:0,left:0,right:"",bottom:"",width:U?`${U}px`:"",height:N?`${N}px`:"","max-width":Y,"max-height":Y,margin:"",transform:""});this.xf(M);O={transform:O,top:"",left:"",width:U?`${U}px`:"",height:N?`${N}px`:"","max-width":"","max-height":""};Y=this.Z.Xb;var w=this.Z.oI,l=this.Z.Wl;this.jw&&Y!=null&&(w=50,Y=Math.floor(Y/3)*3+1);w=w*.96+2;switch(Y){case 0:case 3:case 6:(m=this.Z.q9.fontSizeIncrement)&&m>0&&this.Z.Lm!==2&&this.Z.Lm!==3&&(w=Math.max(w/(1+m*2),2));O.left=`${w}%`;break;case 1:case 4:case 7:O.left=
`${w}%`;w=0;this.Y||(w=this.O.offsetWidth);U||w?(U=U||w+1,O.width=`${U}px`,O["margin-left"]=m?`${U/-2-v/2}px`:`${U/-2}px`):(this.Y&&(O.width="max-content"),O.transform+=" translateX(-50%)");break;case 2:case 5:case 8:O.right=`${100-w}%`}m=l*.96+2;switch(Y){case 0:case 1:case 2:O.top=`${m}%`;break;case 3:case 4:case 5:O.top=`${m}%`;m=0;this.Y||(m=this.element.clientHeight);(N=N||m)?(O.height=`${N}px`,O["margin-top"]=`${N/-2}px`):O.transform+=" translateY(-50%)";break;case 6:case 7:case 8:O.bottom=
`${100-m}%`}g.KK(this.element,O);this.A&&(this.Y?N=this.Jz:(M=eOG(this,M),N=this.jw?M>0?this.O.offsetHeight/M:0:this.O.offsetHeight/M),this.A.style.height=`${N}px`,this.A.style.width=`${N}px`,this.element.style.paddingLeft=`${N+5}px`,this.element.style.paddingRight=`${N+5}px`,this.Y||(M=Number(this.element.style.marginLeft.replace("px",""))-N-5,N=Number(this.element.style.marginRight.replace("px",""))-N-5,this.element.style.marginLeft=`${M}px`,this.element.style.marginRight=`${N}px`))}xf(M){if(this.type===
0&&this.K.params.dH!==void 0&&this.experiments.cv("web_enable_popon_asr_captions")){var U=M,N=this.K.params.dH;if(U.length===0||N<=0)M=[];else{M=[];for(let O=U.length-1;O>=0;O--){var m=U[O];M.unshift(m);let v=eOG(this,M);if(v>N){M.shift();typeof m.text==="string"&&(U=m.text.split("\n"),N=v-N,U.length-N>0&&(m=new FN(m.start,m.end-m.start,m.priority||0,m.windowId,U.slice(N).join("\n"),m.append,m.Z),M.unshift(m)));break}}}}for(m=0;m<M.length&&M[m]===this.V[m];m++);if(this.ML||this.V.length>m)m=0,this.ML=
!1,this.V=[],this.B=this.Wv=this.sM=null,g.lq(this.O);for(;m<M.length;m++)P9F(this,M[m])}Ve(){return 0}rK(){return 0}toString(){return super.toString()}};var TYH=class{constructor(){this.O=this.time=this.mode=this.K=0;this.S=new j4J(this);this.B=new j4J(this);this.Z=[];this.clear()}clear(){this.O=this.time=this.mode=0;this.Z=[];this.reset()}reset(){this.mode=0;this.S.reset(0);this.B.reset(1)}},C9j=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],rXJ=class{constructor(){this.type=0}set(M){this.type=M}get(){return this.type}},Ksn=class{constructor(){this.state=this.Pi=this.sx=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}fg(){return this.state!==0}matches(M,U){return this.fg()&&M===this.sx&&U===this.Pi}},H4i=class{constructor(){this.timestamp=this.Z=0}reset(){this.timestamp=
this.Z=0}},dF=class{constructor(M){this.B=M;this.O=[];this.Z=this.K=this.row=0;this.style=new rXJ;this.S=0;for(M=0;M<=15;M++){this.O[M]=[];for(let U=0;U<=32;U++)this.O[M][U]=new H4i}}updateTime(M){for(let U=1;U<=15;++U)for(let N=1;N<=32;++N)this.O[U][N].timestamp=M}debugString(){var M="\n";for(let U=1;U<=15;++U){for(let N=1;N<=32;++N){let m=this.O[U][N];M=m.Z===0?M+"_":M+String.fromCharCode(m.Z)}M+="\n"}return M}reset(M){for(let U=0;U<=15;U++)for(let N=0;N<=32;N++)this.O[U][N].reset();this.S=M;this.Z=
0;this.K=this.row=1}},BiG=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],qju=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],D2J=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],zOO=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],kwO=class{constructor(M){this.O=M;this.B=0;this.style=new rXJ;this.A=new dF(this.O);this.V=new dF(this.O);this.text=new dF(this.O);this.K=this.A;this.S=this.V;this.Z=this.K}reset(M,U){this.B=U;this.style.set(2);this.K=this.A;this.S=this.V;this.Z=this.K;var N=(M<<2)+(U<<1);this.A.reset(N);this.V.reset(N);this.text.reset((M<<
2)+(U<<1)+1)}},j4J=class{constructor(M){this.Z=M;this.B=0;this.O=new kwO(this.Z);this.A=new kwO(this.Z);this.K=new Ksn;this.S=this.O}reset(M){this.B=M;this.K.clear();this.S=this.O;this.O.reset(M,0);this.A.reset(M,1)}};var xiN=class{S(){}};var Vw=class extends g.zc{reset(){}};var qa=class extends g.OH{constructor(M,U,N,m,O){super(M,M+U,{priority:N,namespace:"captions"});this.id=m;this.params=O;this.Z=[]}toString(){return super.toString()}},B9=0;var Q4G=class extends Vw{constructor(M){super();this.S=M;this.pens={};this.D={};this.Y={};this.B="_"+B9++;this.V={};this.K=this.Z=null;this.A=!0}reset(){this.V={};this.K=this.Z=null;this.A=!0}O(M,U){M=M.firstChild;M.getAttribute("format");U=U||0;Number.isFinite(U);M=Array.from(M.childNodes);for(var N of M)if(N.nodeType===1)switch(N.tagName){case "head":var m=N;break;case "body":var O=N}if(m){m=Array.from(m.childNodes);for(var v of m)if(v.nodeType===1)switch(v.tagName){case "pen":N=v.getAttribute("id");
m=this.pens;M={};var Y=v.getAttribute("p");Y&&Object.assign(M,this.pens[Y]);Y=zM(v,"b");Y!=null&&(M.bold=Y);Y=zM(v,"i");Y!=null&&(M.italic=Y);Y=zM(v,"u");Y!=null&&(M.underline=Y);Y=nA(v,"et");Y!=null&&(M.charEdgeStyle=Y);Y=nA(v,"of");Y!=null&&(M.offset=Y);Y=GM(v,"bc");Y!=null&&(M.background=Y);Y=GM(v,"ec");Y!=null&&(M.Fa=Y);Y=GM(v,"fc");Y!=null&&(M.color=Y);Y=nA(v,"fs");Y!=null&&Y!==0&&(M.fontFamily=Y);Y=Do(v,"sz");Y!==void 0&&(M.fontSizeIncrement=Y/100-1);Y=Do(v,"bo");Y!==void 0&&(M.backgroundOpacity=
Y/255);Y=Do(v,"fo");Y!==void 0&&(M.textOpacity=Y/255);Y=nA(v,"rb");Y!=null&&Y!==10&&Y!==0&&(M.iH=Y>10?Y-1:Y);Y=nA(v,"hg");Y!=null&&(M.yj=Y);m[N]=M;break;case "ws":m=v.getAttribute("id");this.Y[m]=Hwn(this,v);break;case "wp":m=v.getAttribute("id"),this.D[m]=kcu(this,v)}}if(O){v=[];O=Array.from(O.childNodes);for(q of O)if(q.nodeType===1)switch(q.tagName){case "w":this.Z=x2O(this,q,U,!1);(O=this.V[this.Z.id])&&O.end>this.Z.start&&(O.end=this.Z.start);this.V[this.Z.id]=this.Z;v.push(this.Z);break;case "p":var w=
q;M=U;O=[];m=w.getAttribute("w")||this.B;N=!!zM(w,"a");M=(Do(w,"t")||0)+M;Y=Do(w,"d")||5E3;N||(!this.A&&this.K&&this.K.windowId===m&&this.K.end>M&&(this.K.end=M),this.K&&this.K.text==="\n"&&(this.K.text=""));let r=N?6:5;var l=w.getAttribute("p");l=l?this.pens[l]:null;let k=Array.from(w.childNodes);k.length&&(this.A=w.getAttribute("d")!=null);for(w=0;w<k.length;w++){var c=k[w],S=void 0;w>0&&(N=!0);let Q;c.nodeType===1&&(Q=c);if(Q&&Q.tagName==="s"){if((c=(c=Q.getAttribute("p"))?this.pens[c]:null)&&
c.iH&&(c.iH===1?(c=k.slice(w,w+4),c.length===4&&(S=roG(M,Y,m,N,r,c,this.pens),w+=3)):S=roG(M,Y,m,N,r,[Q],this.pens)),!S){var y=Q;S=M;c=Y;var E=m,L=N;let b=y.textContent?y.textContent:"";var C=y.getAttribute("p");C=C?this.pens[C]:null;y=Do(y,"t")||0;S=new FN(S+y,c-y,r,E,b,L,C)}}else S=new FN(M,Y,r,m,c.textContent||"",N,l);O.push(S);this.K=S}if(O.length>0){O[0].windowId===this.B&&(this.Z=x2O(this,q,U,!0),v.push(this.Z));for(let Q of O)Q.windowId=this.Z.id,this.Z.Z.push(Q),v.push(Q)}}var q=v}else q=
[];return q}};var b4i=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Xgu=class extends Vw{constructor(M){super();this.A=M;this.Z=new Map;this.S=new Map;this.B=new Map;this.K=new Map}reset(){this.K.clear()}O(M,U){M=JSON.parse(M);if(!M)return[];if(M.pens){var N=M.pens,m=0;for(var O of N){N={};var v=O.pParentId;v&&Object.assign(N,this.Z.get(v));O.bAttr&&(N.bold=!0);O.iAttr&&(N.italic=!0);O.uAttr&&(N.underline=!0);v=O.ofOffset;v!=null&&(N.offset=v);O.szPenSize!==void 0&&(N.fontSizeIncrement=O.szPenSize/100-1);
v=O.etEdgeType;v!=null&&(N.charEdgeStyle=v);O.ecEdgeColor!==void 0&&(N.Fa=jS(O.ecEdgeColor));v=O.fsFontStyle;v!=null&&v!==0&&(N.fontFamily=v);O.fcForeColor!==void 0&&(N.color=jS(O.fcForeColor));O.foForeAlpha!==void 0&&(N.textOpacity=O.foForeAlpha/255);O.bcBackColor!==void 0&&(N.background=jS(O.bcBackColor));O.boBackAlpha!==void 0&&(N.backgroundOpacity=O.boBackAlpha/255);(v=O.rbRuby)&&v!==10&&(N.iH=v>10?v-1:v,N.textEmphasis=b4i.get(N.iH));O.hgHorizGroup&&(N.yj=O.hgHorizGroup);this.Z.set(m++,N)}}if(M.wsWinStyles){m=
M.wsWinStyles;O=0;for(var Y of m)m={},(N=Y.wsParentId)?Object.assign(m,this.B.get(N)):Object.assign(m,this.A),Y.mhModeHint!==void 0&&(m.YK=Y.mhModeHint),Y.juJustifCode!==void 0&&(m.textAlign=Y.juJustifCode),Y.pdPrintDir!==void 0&&(m.Lm=Y.pdPrintDir),Y.sdScrollDir!==void 0&&(m.MP=Y.sdScrollDir),Y.wfcWinFillColor!==void 0&&(m.windowColor=jS(Y.wfcWinFillColor)),Y.wfoWinFillAlpha!==void 0&&(m.windowOpacity=Y.wfoWinFillAlpha/255),this.B.set(O++,m)}if(M.wpWinPositions){O=M.wpWinPositions;Y=0;for(var w of O)O=
{},(m=w.wpParentId)&&Object.assign(O,this.S.get(m)),w.ahHorPos!==void 0&&(O.oI=w.ahHorPos),w.apPoint!==void 0&&(O.Xb=w.apPoint),w.avVerPos!==void 0&&(O.Wl=w.avVerPos),w.ccCols!==void 0&&(O.Bi=w.ccCols),w.rcRows!==void 0&&(O.dH=w.rcRows),this.S.set(Y++,O)}if(M.events){M=M.events;w=[];for(let I of M)if(Y=(I.tStartMs||0)+U,O=I.dDurationMs||0,I.id)m=String(I.id),M=QOj(this,I,Y,O,m),w.push(M),this.K.set(m,M);else{I.wWinId?m=I.wWinId.toString():(m="_"+B9++,M=QOj(this,I,Y,O,m),w.push(M),this.K.set(m,M));
M=w;var l=I;O===0&&(O=5E3);N=this.K.get(m);let MO=(v=!!l.aAppend)?6:5,e9=l.segs,D3=null;l.pPenId&&(D3=this.Z.get(l.pPenId));for(l=0;l<e9.length;l++){var c=e9[l],S=c.utf8;if(S){var y=c.tOffsetMs||0;let Kt=null;c.pPenId&&(Kt=this.Z.get(c.pPenId));if((N.params.YK!=null?N.params.YK:N.Z.length>1?1:0)===2&&v&&S==="\n")continue;c=null;var E=[],L;if(L=Kt&&Kt.iH===1)a:{L=e9;var C=l;if(C+3>=L.length||!L[C+1].pPenId||!L[C+2].pPenId||!L[C+3].pPenId){L=!1;break a}var q=L[C+1].pPenId;(q=this.Z.get(q))&&q.iH&&q.iH===
2?(q=L[C+2].pPenId,q=this.Z.get(q),!q||!q.iH||q.iH<3?L=!1:(q=L[C+3].pPenId,L=(q=this.Z.get(q))&&q.iH&&q.iH===2?!0:!1)):L=!1}if(L)y=e9[l+1].utf8,c=e9[l+3].utf8,L=e9[l+2].utf8,C=this.Z.get(e9[l+2].pPenId),S=TiQ(S,y,L,c,C),c=new FN(Y,O,MO,m,S,v,Kt),l+=3;else{if(S.indexOf("<")>-1){E=Kt;L=D3;C=Y;q=O;var r=y,k=MO,Q=v;let sJ=[];var b=g.fT(`<html>${S}</html>`);if(!b.getElementsByTagName("parsererror").length&&b.firstChild?.childNodes.length)for(let d0 of b.firstChild.childNodes){b=d0.textContent?.replace(/\n/g,
"")??"";if(d0.nodeType===3&&(!b||b.match(/^ *$/)!=null))continue;let n7={};Object.assign(n7,E||L);switch(d0?.tagName){case "b":n7.bold=!0;break;case "i":n7.italic=!0;break;case "u":n7.underline=!0}sJ.push(new FN(C+r,q-r,k,N.id,b,Q,n7))}E=sJ}E.length||(E=[new FN(Y+y,O-y,MO,N.id,S,v,Kt||D3)])}if(E.length)for(let sJ of E)M.push(sJ),N.Z.push(sJ);else c&&(M.push(c),N.Z.push(c))}v=!0}}U=w}else U=[];return U}};var uaF=class extends g.bh{constructor(M,U,N){super(M);this.videoData=U;this.audioTrack=N;this.Y=U.PF}S(M,U,N){U24(this.videoData.videoId,M.vssId,N.Db)}B(M){if(this.audioTrack)for(let U of this.audioTrack.captionTracks)g.cv(this.Z,U);M.w1()}};var aFn=class extends fA{constructor(M,U,N,m,O,v,Y,w,l,c){super(M,U,N,m,O,v,Y,w,l,c);this.type=1}xf(M){var U=this.K.Z;super.xf(M);for(M=M.length;M<U.length;M++){let O=U[M],v;if(m&&O.Z===N)v=m;else{v={};Object.assign(v,O.Z);Object.assign(v,IFO);var N=O.Z;var m=v}P9F(this,O,v)}}},IFO={aC:!0};var bwJ=class extends xiN{constructor(M,U){super();this.trackData=M;this.A=U;this.version=this.B=this.O=this.byteOffset=0;this.K=[];this.Z=new DataView(this.trackData)}S(M,U,N,m,O){if(N<m){let v="_"+B9++;N=N/1E3-this.A;m=m/1E3-this.A;M=new qa(N,m-N,5,v,{textAlign:0,Xb:0,oI:U*2.5,Wl:M*5.33});O=new FN(N,m-N,5,v,O);this.K.push(M);this.K.push(O)}}},s4i=class extends Vw{constructor(M,U){super();this.K=M;this.S=U;this.track=this.S.languageName==="CC3"?4:0;this.Z=new TYH;this.Z.K=1<<this.track}O(M){M=new bwJ(M,
this.K);if(X37(M)){for(;M.byteOffset<M.Z.byteLength;)for(M.version===0?M.O=rF(M)*(1E3/45):M.version===1&&(M.O=rF(M)*4294967296+rF(M)),M.B=TM(M);M.B>0;M.B--){var U=TM(M);let N=TM(M),m=TM(M);U&4&&(U&3)===this.track&&(this.track===0||this.track===1)&&(U=this.Z,U.Z.push({time:M.O,type:this.track,pF:N,ef:m,order:U.Z.length}))}FGj(this.Z,M);return M.K}return[]}reset(){this.Z.clear()}};var Fsu=class extends fA{constructor(M,U,N,m,O,v,Y,w,l,c){super(M,U,N,m,O,v,Y,w,l,c);this.type=2;this.Sw=[];this.b0=this.ZQ=this.VT=0;this.d6=NaN;this.gK=0;this.iZ=null;this.lZ=new g.Fy(this.hz,433,this);this.A&&(c.createClientVe(this.A,this,167342),this.U(this.A,"click",()=>{c.logClick(this.A)}),M=new g.$4(this.element,!0),g.D(this,M),M.subscribe("hoverstart",()=>{c.logVisibility(this.A,!0)},this));
g.Gu(this.element,"ytp-caption-window-rollup");g.D(this,this.lZ);g.KK(this.element,"overflow","hidden")}DL(){g.qH(this.lZ)}hz(){this.element.removeEventListener("transitionend",this.hz,!1);g.Tu(this.element,"ytp-rollup-mode");this.D(this.iZ,!0)}rK(){return this.S?this.b0:this.ZQ}Ve(){return this.S?this.ZQ:this.b0}D(M,U){this.iZ=M;if(this.K.params.dH){var N=0;for(let m=0;m<this.V.length&&N<M.length;m++)this.V[m]===M[N]&&N++;N>0&&N<M.length&&(M=this.V.concat(M.slice(N)));this.gK=this.b0;this.ZQ=this.b0=
0;super.D(M);$2H(this,U)}super.D(M)}};var $ij=class{constructor(M,U,N,m){this.C=M;this.B=U;this.logger=N;this.AK=m;this.VZ=[];this.Z=null;this.O=[];this.Fy=[];this.K=null;this.jb={igo:()=>this.K,
ZH:()=>this.VZ,
uqo:O=>{this.O=O},
EXJ:()=>this.O};
M=g.Cs(this.C.J().experiments,"html5_override_micro_discontinuities_threshold_ms");this.S=M>0?M:10}unload(){this.K!=null&&(this.C.removeEventListener("sabrCaptionsDataLoaded",this.K),this.K=null);this.VZ=[];this.Z=null;this.O=[];this.C.publish("sabrCaptionsBufferedRangesUpdated",this.VZ)}ZX(M){return{formatId:g.A6(M.info.QT.info,this.AK),fo:M.info.fo+(this.AK?0:1),startTimeMs:M.info.S*1E3,durationMs:M.info.D*1E3}}};var i4F=class extends g.bh{constructor(M,U){super(U);this.K=M;this.C=U;this.logger=new g.mp("caps");this.D=this.b0=null;this.OM=new $ij(this.C,this,this.logger,this.K.AK)}S(M,U,N){this.O();U=M.getId();U=U!=null&&U in this.K.Z?this.K.Z[U]:null;U||(U=M.languageCode,U=this.K.isManifestless?VyF(this,U,"386"):VyF(this,U));U&&(this.D=M,this.b0=U,frJ(this.OM,N),this.C.publish("sabrCaptionsTrackChanged",g.A6(U.info,this.K.AK)))}B(M){var U=this.K.isManifestless?gMj(this,"386"):gMj(this);for(let N of U)g.cv(this.Z,
N);M.w1()}O(){this.D&&(this.D=this.b0=null,this.OM.unload(),this.C.publish("sabrCaptionsTrackChanged",null))}A(){return""}};var MU4="WEBVTT".split("").map(M=>M.charCodeAt(0)),YEa=class extends Vw{constructor(){super()}O(M,U){M instanceof ArrayBuffer&&(M=g.Yx(new Uint8Array(M)));
var N=[];M=M.split(JX7);for(let C=1;C<M.length;C++){var m=M[C],O=U;if(m!==""&&!tUu.test(m)){var v=g9.exec(m);if(v&&v.length>=4){var Y=KA(v[1]),w=KA(v[2])-Y;Y+=O;var l=(v=v[3])?v.split(" "):[];v={};var c=null;var S="";var y=null,E="";for(let q of l){l=q.split(":");if(l.length!==2)continue;var L=l[1];switch(l[0]){case "line":l=L.split(",");l[0].endsWith("%")&&(c=l[0],v.Wl=Number.parseInt(c,10),l.length===2&&(S=l[1].trim()));break;case "position":l=L.split(",");y=l[0];v.oI=Number.parseInt(y,10);l.length===
2&&(E=l[1].trim());break;case "align":switch(L){case "start":v.textAlign=0;break;case "middle":v.textAlign=2;break;case "end":v.textAlign=1}}}c||S||(S="end");if(!y)switch(v.textAlign){case 0:v.oI=0;break;case 1:v.oI=100;break;case 2:v.oI=50}if(v.textAlign!=null){c=0;switch(S){case "center":c+=3;break;case "end":c+=6;break;default:c+=0}switch(E){case "line-left":c+=0;break;case "center":c+=1;break;case "line-right":c+=2;break;default:switch(v.textAlign){case 0:c+=0;break;case 2:c+=1;break;case 1:c+=
2}}S=c<0||c>8?7:c;v.Xb=S}m=m.substring(g9.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");E=v;v={};if(m.indexOf("<")<0&&m.indexOf("&")<0)O=NYQ(Y,w,5,E),Y=new FN(Y,w,5,O.id,m,!1,g.JH(v)?void 0:v),N.push(O),N.push(Y),O.Z.push(Y);else for(S=m.split(RkJ),S.length===1?(m=5,E=NYQ(Y,w,m,E)):(c=m=6,E=Object.assign({Bi:32},E),E=new qa(Y,w,c,"_"+B9++,E)),N.push(E),c=Y,y=0;y<S.length;y++)if(l=S[y],y%2===0){L=g.fT(`<html>${l}</html>`);let q;L.getElementsByTagName("parsererror").length?(q=L.createElement("span"),
q.appendChild(L.createTextNode(l))):q=L.firstChild;miD(this,c,w-(c-Y),m,E,y>0,q,v,N)}else c=KA(l)+O}g9.lastIndex=0}}return N}},tUu=/^NOTE/,JX7=/(?:\r\n|\r|\n){2,}/,g9=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),RkJ=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var fF4=class extends g.zc{constructor(M,U){super();this.C=M;this.j=U;this.Z=null;this.wK=this.C.qb();this.logger=new g.mp("caps")}clear(){this.Z&&this.Z.dispose();this.Z=null}reset(){this.Z&&this.Z.reset()}zS(){super.zS();this.clear()}};var SEO={windowColor:"#080808",windowOpacity:0,textAlign:2,Xb:7,oI:50,Wl:100,isDefault:!0,q9:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},cXJ={windowColor:"#080808",windowOpacity:0,textAlign:0,Xb:7,oI:50,Wl:100,isDefault:!0,q9:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.l0("captions",class extends g.Qz{constructor(M){super(M);this.C=M;this.d6=[];this.u0={};this.DQ={};this.V=!1;this.O="NONE";this.Z=this.Y=this.OM=this.VT=this.r6=null;this.po={w1:()=>{this.w1()},
Db:(m,O,v,Y,w=0)=>{var l=Number(this.videoData.J().l0().Z.yT(g.rkk)??0);w>0&&l>0&&this.videoData.lengthSeconds>0&&w/this.videoData.lengthSeconds>l?this.C.FJ("tts",{dropcap:w}):this.Db(m,O,v,Y)}};
this.K=null;this.uZ="";this.j=this.C.J();this.videoData=this.C.getVideoData();this.hz=this.C.no();this.B={q9:{}};this.A={q9:{}};this.videoData.ye()?this.O="OFFLINE":g.rrj(this.videoData,this.C)?this.O="HLS":d2u(this.videoData,this.C)?this.O="SABR_LIVE":g.KwJ(this.videoData,this.C)?this.O="LIVE":this.videoData.captionTracks.length?this.O="INNERTUBE":this.videoData.zb&&(this.O="TTS");this.sM=this.j.controlsType==="3";this.xf=new fF4(this.C,this.j);this.Sw=new g.Zv(this);this.D=new g.d({W:"div",N:"ytp-caption-window-container",
L:{id:"ytp-caption-window-container"}});this.b0={top:0,right:0,bottom:0,left:0,width:1,height:1};var U=null,N=g.wh("yt-html5-player-modules::subtitlesModuleData");N&&(U=new g.V_(N));this.storage=U;U=M.T$();this.zb=!!U?.d6();this.jw=!!U?.ML();this.S=H9(this);this.ZQ=lFa(this);g.D(this,this.xf);this.S?this.Wv=this.ML=null:(this.ML=new g.aX(this.Mh,void 0,this),g.D(this,this.ML),this.Wv=new g.Fy(this.lZ,2E3,this),g.D(this,this.Wv));g.D(this,this.Sw);g.tE(this.player,this.D.element,4);g.D(this,this.D);
this.S||this.Sw.U(M,"resize",this.EM);U=g.LZ(this.j)&&!g.FV()&&!this.C.isFullscreen();N=this.j.l0().Z.yT(g.gtk)&&g.Os(this.j)&&g.r_;(this.ye=(U||N)&&!this.S&&!this.ZQ)&&this.Sw.U(M,U?"resize":"fullscreentoggled",this.Ve);this.Sw.U(M,"onPlaybackAudioChange",this.rK);this.Sw.U(M,g.uV("captions"),m=>{this.onCueRangeEnter(m)});
this.Sw.U(M,g.Ix("captions"),m=>{this.onCueRangeExit(m)});
kW(this,eS()||{});g.jB(this.player,"onCaptionsModuleAvailable");this.O==="HLS"&&this.S&&(M=this.C.T$().BV(),this.jw&&this.Sw.U(M.textTracks,"addtrack",this.gK))}zS(){if(this.S||this.ZQ){let M=this.C.T$();M&&!M.GS()&&M.V()}else xW(this,!1);super.zS()}q8(){return this.j.G("html5_honor_caption_availabilities_in_audio_track")&&this.O!=="LIVE"&&this.O!=="SABR_LIVE"}Ip(){if(this.sM)return this.S||this.ZQ;if(this.O==="HLS")return this.S;var M=this.getAudioTrack();if(this.q8()){if(!M.captionTracks.length)return!1;
if(!this.Z)return!0}M=Eq(M,g.qN(this.j));return M==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:M==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?uN(this):XN(this)||uN(this)?!0:eki(this)}load(){super.load();this.Y=this.getAudioTrack();if(this.Z)this.K&&(this.xf.clear(),this.S?AXj(this,!0):this.player.getPresentingPlayerType()!==3&&this.Z.S(this.K,"json3",this.po),this.O!=="HLS"&&this.S||this.ZQ||IZ(this)||g.jB(this.player,"captionschanged",g.jw(this.K)));else{let M;this.O==="OFFLINE"?M=new uaF(this.player,this.videoData,
this.getAudioTrack()):this.O==="SABR_LIVE"?M=new i4F(this.videoData.Z,this.player):this.O==="HLS"?M=new Dij(this.player):this.O==="LIVE"?M=new hkQ(this.videoData.Z,this.player):this.O==="INNERTUBE"?M=new g.XE(this.player,this.videoData,this.getAudioTrack()):M=new g.uh(this.player,this.videoData.zb,this.videoData.videoId,g.riA(this.videoData),this.videoData.Yq,this.videoData.eventId);this.Z=M;g.D(this,this.Z);this.Z.B(this.po)}}unload(){this.S&&this.K?AXj(this,!1):(this.Wv&&this.Wv.rJ(),this.player.sa("captions"),
this.d6=[],this.Z&&this.Z.O(),this.xf.clear(),this.OM&&this.player.ek(this.OM),this.EM());super.unload();this.player.gH();g.jB(this.player,"captionschanged",{})}create(){this.Ip()&&this.load();var M;a:{if(this.j.G("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(M=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let U of M)if(U.kind==="asr"&&U.languageCode===
"en"){M=!0;break a}M=!1}M&&this.C.publish("showpromotooltip",this.D.element)}w1(){var M=Eq(this.player.getAudioTrack(),g.qN(this.j));var U=M==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?$W(this,this.V):M==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&uN(this)?sq(this):XN(this)||this.V||eki(this)?$W(this,this.V):uN(this)?sq(this):null;if(this.O!=="HLS"&&this.S||this.ZQ){let N=g.IA(this.Z.Z,!0);M=[];for(let m=0;m<N.length;m++){let O=N[m],v=g.YY("TRACK");v.setAttribute("kind","subtitles");v.setAttribute("label",
g.G2(O));v.setAttribute("srclang",g.T2(O));v.setAttribute("id",O.toString());this.ZQ||v.setAttribute("src",this.Z.A(O,"vtt"));O===U&&v.setAttribute("default","1");M.push(v)}U=this.C.T$();U.OM(M);M=U.BV();this.jw&&this.Sw.U(M.textTracks,"change",this.DL)}else!this.K&&U&&RZ(this,U),g.jB(this.player,"onCaptionsTrackListChanged"),g.TS(this.player,"onApiChange")}getTrackById(M){var U=g.IA(this.Z.Z,!0);for(let N=0;N<U.length;N++)if(U[N].toString()===M)return U[N];return null}DL(){var M=this.C.T$().BV().textTracks,
U=null;for(let N=0;N<M.length;N++)M[N].mode==="showing"&&(U=this.getTrackById(M[N].id));(this.loaded?this.K:null)!==U&&RZ(this,U,!0)}gK(){this.Z?.B(this.po)}pk(){!this.K&&this.S||this.unload()}Db(M,U,N,m){if(M){tv(this,this.K??void 0);this.Z.ZQ()&&(this.d6=[],this.C.sa("captions"),yw(this.ML),this.xf.reset());a:{var O=this.xf;m=m||0;N=vM7(O,M,N||0);M=[];try{for(let k of N){let Q=k.trackData,b=k.RN,I=O.j.G("safari_live_drm_captions_fix");if(typeof Q!=="string"){N=M;var v=N.concat;if(I&&UiO(Q))var Y=
oMu(O,Q,b);else{var w=O,l=U,c=Q,S=b,y=m;if(!uU4(c))throw Error("Invalid binary caption track data");w.Z||(w.Z=new s4i(y,l));Y=w.Z.O(c,S)}var E=v.call(N,Y)}else{if(Q.substring(0,6)==="WEBVTT")var L=M.concat(oMu(O,Q,b));else{N=M;var C=N.concat;b:{l=O;w=U;if(Q[0]==="{")try{l.Z||(l.Z=new Xgu(wgN(w)));var q=l.Z.O(Q,b);break b}catch(D3){g.MV(D3);q=[];break b}let MO=g.fT(Q);if(!MO||!MO.firstChild){let D3=Error("Invalid caption track data");D3.params=Q;throw D3;}if(MO.firstChild.tagName==="timedtext"){if(Number(MO.firstChild.getAttribute("format"))===
3){c=MO;l.Z||(l.Z=new Q4G(wgN(w)));q=l.Z.O(c,b);break b}let D3=Error("Unsupported subtitles format in web player (Format2)");D3.params=Q;throw D3;}if(MO.firstChild.tagName==="transcript"){let D3=Error("Unsupported subtitles format in web player (Format1)");D3.params=Q;throw D3;}let e9=Error("Invalid caption track data");e9.params=Q;throw e9;}L=C.call(N,q)}E=L}M=E}var r=M;break a}catch(k){g.Oc(O.logger,187101178,`Captions parsing failed: ${k.message}. `);O.clear();r=[];break a}r=void 0}this.j.G("html5_sabr_live_support_subfragmented_captions")&&
this.Z instanceof i4F&&(U=this.Z.OM,O=[],r.length>0&&(O=r.slice(U.O.length)),U.O=!U.Z||U.Z.info.lK?[]:r,r=O);U=this.j.l0().Z.yT(g.uOd);r.length>0&&(!U||this.uZ!==this.K?.K())&&(O=this.K,this.QG(O,!!O,IZ(this)?"g":this.V?"m":"s"),U&&(this.uZ=this.K?.K()||""));this.player.ek(r,void 0,this.O==="LIVE"||this.O==="SABR_LIVE");!this.V||this.ZQ||IZ(this)||g.nx(this.j)||g.Es(this.j)||g.P0(this.j)||this.j.Sw==="shortspage"||this.player.isInline()||(this.Wv.rJ(),r=KGi({Xb:0,oI:5,Wl:5,dH:2,textAlign:0,Lm:0,lang:"en"}),
this.VT=[r],U=["Click "," for settings"],this.r6||(O=new g.ky(g.fl()),g.D(this,O),this.r6=O.element),O=r.end-r.start,(E=g.G2(this.K))&&this.VT.push(new FN(r.start,O,0,r.id,E)),this.VT.push(new FN(r.start,O,0,r.id,U[0]),new FN(r.start,O,0,r.id,this.r6,!0),new FN(r.start,O,0,r.id,U[1],!0)),this.player.ek(this.VT),g.Bk(this.Wv));!this.V||this.ZQ||IZ(this)||(this.j.G("enable_player_captions_persistence_state_machine")?bN(this,!0):g.qN(this.j)?iN(this,!0):Jv(this,!0),this.Y&&(this.Y.S=this.K),this.player.gH());
this.V=!1}}onCueRangeEnter(M){this.d6.push(M);yw(this.ML)}onCueRangeExit(M){g.UO(this.d6,M);this.Z instanceof hkQ&&this.Z.b0&&this.player.hv([M]);yw(this.ML)}getCaptionWindowContainerId(){return this.D.element.id}lZ(){yXN(this,this.VT);this.VT=null}Mh(){if(!this.ye||!this.S){this.ML.stop();g.tH(this.DQ);this.d6.sort(g.Xp);var M=this.d6;if(this.OM){let U=g.Xc(M,function(N){return this.OM.indexOf(N)===-1},this);
U.length&&(M=U)}for(let U of M)U instanceof qa?Cbi(this,U):pgJ(this,U);for(let [U,N]of Object.entries(this.u0)){let m=U,O=N;this.DQ[m]?(O.element.parentNode||(O instanceof Fsu||O instanceof aFn||g.HJ(this.u0,(v,Y)=>{Y!==m&&v.K.params.Xb===O.K.params.Xb&&v.K.params.oI===O.K.params.oI&&v.K.params.Wl===O.K.params.Wl&&(v.dispose(),delete this.u0[Y]);return Y===m},this),this.D.element.appendChild(O.element)),O.D(this.DQ[m])):(O.dispose(),delete this.u0[m])}}}hL(){kW(this,{},!0);
g.jB(this.player,"captionssettingschanged")}b7(){var M=this.j.G("enable_player_captions_new_style_defaults")?cXJ:SEO,U=M.q9;M={background:U.background,backgroundOpacity:U.backgroundOpacity,charEdgeStyle:U.charEdgeStyle,color:U.color,fontFamily:U.fontFamily,fontSizeIncrement:U.fontSizeIncrement,fontStyle:U.bold&&U.italic?3:U.bold?1:U.italic?2:0,textOpacity:U.textOpacity,windowColor:M.windowColor,windowOpacity:M.windowOpacity};U=eS()||{};U.background!=null&&(M.background=U.background);U.backgroundOverride!=
null&&(M.backgroundOverride=U.backgroundOverride);U.backgroundOpacity!=null&&(M.backgroundOpacity=U.backgroundOpacity);U.backgroundOpacityOverride!=null&&(M.backgroundOpacityOverride=U.backgroundOpacityOverride);U.charEdgeStyle!=null&&(M.charEdgeStyle=U.charEdgeStyle);U.charEdgeStyleOverride!=null&&(M.charEdgeStyleOverride=U.charEdgeStyleOverride);U.color!=null&&(M.color=U.color);U.colorOverride!=null&&(M.colorOverride=U.colorOverride);U.fontFamily!=null&&(M.fontFamily=U.fontFamily);U.fontFamilyOverride!=
null&&(M.fontFamilyOverride=U.fontFamilyOverride);U.fontSizeIncrement!=null&&(M.fontSizeIncrement=U.fontSizeIncrement);U.fontSizeIncrementOverride!=null&&(M.fontSizeIncrementOverride=U.fontSizeIncrementOverride);U.fontStyle!=null&&(M.fontStyle=U.fontStyle);U.fontStyleOverride!=null&&(M.fontStyleOverride=U.fontStyleOverride);U.textOpacity!=null&&(M.textOpacity=U.textOpacity);U.textOpacityOverride!=null&&(M.textOpacityOverride=U.textOpacityOverride);U.windowColor!=null&&(M.windowColor=U.windowColor);
U.windowColorOverride!=null&&(M.windowColorOverride=U.windowColorOverride);U.windowOpacity!=null&&(M.windowOpacity=U.windowOpacity);U.windowOpacityOverride!=null&&(M.windowOpacityOverride=U.windowOpacityOverride);return M}d_(M,U){var N={};Object.assign(N,eS());Object.assign(N,M);kW(this,N,U);g.jB(this.player,"captionssettingschanged")}EM(){!this.S&&this.loaded&&(g.Tn(this.u0,function(M,U){M.dispose();delete this.u0[U]},this),this.Mh())}Ev(M,U){switch(M){case "fontSize":if(isNaN(U))break;
M=g.nF(U,-2,4);this.d_({fontSizeIncrement:M});return M;case "reload":U&&!this.S&&RZ(this,this.K,!0);break;case "stickyLoading":U!==void 0&&this.j.OM&&(this.j.G("enable_player_captions_persistence_state_machine")?bN(this,!(!U||!U.userInitiated)):g.qN(this.j)?iN(this,!!U):Jv(this,!!U));break;case "track":return BY4(this,U);case "tracklist":return this.Z?g.ug(g.IA(this.Z.Z,!(!U||!U.includeAsr)),N=>g.jw(N)):[];
case "translationLanguages":return this.Z?this.Z.Y.map(N=>Object.assign({},N)):[];
case "sampleSubtitles":this.S||U===void 0||xW(this,!!U);break;case "sampleSubtitlesCustomized":this.S||xW(this,!!U,U);break;case "recommendedTranslationLanguages":return g.ql();case "defaultTranslationSourceTrackIndices":return this.Z?this.Z.u0:[]}}getOptions(){var M="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.j.OM&&M.push("stickyLoading");return M}o3(){var M=this.K;if(this.C.ly("captions")){if(this.j.G("html5_modify_caption_vss_logging"))return(M=this.videoData.k8??
null)?{cc:g.c0A(M)}:{};if(M){let U=M.vssId;M.translationLanguage&&U&&(U=`t${U}.${g.T2(M)}`);return{cc:U}}}return{}}Lk(M){this.isSubtitlesOn()?(this.j.G("enable_player_captions_persistence_state_machine")&&M?bN(this,!1):g.qN(this.j)?iN(this,!1):Jv(this,!1),tv(this),RZ(this,null,!0)):this.qy(M)}qy(M){var U=IZ(this)||!this.K?$W(this,!0):this.K;U&&this.o8(U.vssId,"m");this.isSubtitlesOn()||RZ(this,U,this.j.G("enable_player_captions_persistence_state_machine")?M:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.K&&!IZ(this)}rK(){var M=IZ(this);uN(this,M)?RZ(this,this.getAudioTrack().Z,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.q8()&&(this.V=!1,this.K=null,this.Z&&(this.Z.dispose(),this.Z=null)),this.Ip()&&(M?RZ(this,$W(this,!1),!1):this.load()))}qd(M){M&&(this.b0={top:M.top,right:M.right,bottom:M.bottom,left:M.left,width:1-M.left-M.right,height:1-M.top-M.bottom},this.D.element.style.top=`${this.b0.top*100}%`,this.D.element.style.left=`${this.b0.left*100}%`,this.D.element.style.width=
`${this.b0.width*100}%`,this.D.element.style.height=`${this.b0.height*100}%`,this.D.element.style.position="absolute",M=Z4j(this))&&(this.D.element.style.width=`${M.width}px`,this.D.element.style.height=`${M.height}px`)}onVideoDataChange(M,U){M==="newdata"&&(this.videoData=U,this.loaded&&this.unload(),this.V=!1,this.K=null,this.Z&&(this.Z.dispose(),this.Z=null,g.jB(this.player,"captionschanged",{})),this.Ip()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}Ve(){if(this.j.l0().Z.yT(g.gtk)){if(this.loaded&&
this.unload(),this.sM=this.C.isFullscreen()||this.j.controlsType==="3",this.S=H9(this),this.ZQ=lFa(this),this.S||this.ZQ){var M=this.C.T$();M&&!M.GS()&&M.V();this.w1()}}else(M=this.C.T$())&&!M.GS()&&M.V(),this.C.isFullscreen()?(this.S=this.sM=!0,this.loaded&&this.w1()):(this.sM=this.j.controlsType==="3",this.S=H9(this));RZ(this,this.K)}Jz(){var M=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;M&&g.zS(this.player,"innertubeCommand",M)}QG(M,U,N){var m=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,O="";M&&(O=M.vssId,O=O.replace(m,""));var v="";if(M&&M.getId()&&this.j.l0().Z.yT(g.uOd))if(v=M.getId()||"",v.includes(";"))v=v.split(";").map(w=>w.replace(m,"")).join(";");
else{v=v.replace(m,"");var Y="";M.getXtags()&&(Y=M.getXtags(),Y=Y.replace(m,""),v=v.concat(`;${Y}`))}else M&&M.getId()&&(v=M.getId()||""),Y="",M&&M.getXtags()&&(Y=M.getXtags(),Y=Y.replace(m,""),v=v.concat(`;${Y}`));this.O==="HLS"&&(v="");this.C.QG(U?O:"",U?v:"",N)}o8(M,U){M=(M||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");M.length>0&&this.C.o8(M,U)}});})(_yt_player);
