(function(g){var window=this;'use strict';var Cin=function(M,U){g.zS(M,"onAutonavCoundownStarted",U)},piJ=function(M){return M.isBackground()&&M.f0()},ZdG=function(M,U){U=U.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
M.ZQ=U?.navigationEndpoint;U=U?.trackingParams;M.playButton&&U&&M.C.setTrackingParams(M.playButton.element,U)},c2=function(M){var U=w9(M),N=Math,m=N.min;
var O=M.V?Date.now()-M.V:0;N=m.call(N,O,U);lv(M,Math.ceil((U-N)/1E3));U-N<=500&&M.Z()?M.select(!0):M.Z()&&M.D.start()},Sk=function(M){var U=M.C.jd(!0,M.C.isFullscreen());
g.KO(M.container.element,"ytp-autonav-endscreen-small-mode",M.yK(U));g.KO(M.container.element,"ytp-autonav-endscreen-is-premium",!!M.suggestion&&!!M.suggestion.P4);g.KO(M.C.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!M.C.GW());g.KO(M.C.getRootNode(),"countdown-running",M.Z());g.KO(M.container.element,"ytp-player-content",M.C.GW());M.C.G("web_post_play_autonav_embiggening")||g.KK(M.overlay.element,{width:`${U.width}px`});if(M.C.G("web_post_play_autonav_embiggening")){var N=M.C.getRootNode().getBoundingClientRect();
U=Math.min(720,N.width*.5);var m=U*.5625;N=N.height-36-60;m>N&&(m=N,U=16/9*m);g.KK(M.K.Bv("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${m}px`,width:`${U}px`});g.KK(M.container.element,{width:`${U}px`})}M.Z()||(M.C.GW()?lv(M,Math.round(w9(M)/1E3)):lv(M),U=!!M.suggestion&&!!M.suggestion.AD,m=M.C.getVideoData(),m=m?.autonavState===1&&m?.aP&&M.C.GW()?!1:M.C.GW()||!(M.suggestion&&M.suggestion.AD),g.KO(M.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!m&&U),g.KO(M.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",m&&!U),M.A.kN(M.C.GW()))},lv=function(M,U=-1){M=M.K.Bv("ytp-autonav-endscreen-upnext-header");
g.lq(M);if(U>=0){U=String(U);let N="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],m="Up next in $SECONDS".indexOf(N);if(m>=0){M.appendChild(g.o8("Up next in $SECONDS".slice(0,m)));let O=g.YY("span");g.nO(O,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ea(O,U);M.appendChild(O);M.appendChild(g.o8("Up next in $SECONDS".slice(m+N.length)));return}}g.Ea(M,"Up next")},w9=function(M){return M.C.isFullscreen()?(M=M.C.getVideoData()?.sN,M===-1||M===void 0?8E3:M):M.C.gD()>=0?M.C.gD():
g.Cs(M.C.J().experiments,"autoplay_time")||1E4},yE=function(M,U){U=aHF(M,U);
var N=Math,m=N.min;var O=(0,g.u)()-M.V;N=m.call(N,O,U);U=U===0?1:Math.min(N/U,1);M.d6.setAttribute("stroke-dashoffset",`${-211*(U+1)}`);U>=1&&M.Z()&&!M.isCasting()?M.select(!0):M.Z()&&M.K.start()},aHF=function(M,U){return U?U:M.api.isFullscreen()?(M=M.api.getVideoData()?.sN,M===-1||M===void 0?8E3:M):M.api.gD()>=0?M.api.gD():g.Cs(M.api.J().experiments,"autoplay_time")||1E4},Eh=function(M){return g.Ry(M.player)&&M.D()&&!M.S},LM=function(M){var U=M.GW();
U!==M.Y&&(M.Y=U,M.player.publish("autonavvisibility"))},ek=function(M){return g.Ry(M.player)&&M.D()&&!M.B},A8=function(M){var U=M.GW();
U!==M.b0&&(M.b0=U,M.player.publish("autonavvisibility"))},FNj=function(M){M=M.J();
return M.B$&&!M.disableOrganicUi},BlD=function(M){var U=M.player.getVideoData();
if(!U||M.Z===U.Mh)return!1;M.Z=U.Mh;return!0},qWF=function(M){M.player.sa("endscreen");
var U=M.player.getVideoData();U=new g.OH(Math.max((U.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var N=new g.OH(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});M.player.ek([U,N])};
g.Ac.prototype.gD=g.m0(16,function(){return this.app.gD()});
g.N3.prototype.gD=g.m0(15,function(){return this.getVideoData().vc});
g.eQ.prototype.vR=g.m0(14,function(M){this.yP().vR(M)});
g.N8.prototype.vR=g.m0(13,function(M){this.LT!==M&&(this.LT=M,this.E2())});
var W2=class extends g.d{constructor(M){super({W:"div",N:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.ZQ=void 0;this.V=0;M.G("web_post_play_autonav_embiggening")&&g.Gu(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.d({W:"div",N:"ytp-autonav-endscreen-countdown-container"});g.D(this,this.container);this.container.IS(this.element);var U=M.J(),N=U.S;this.C=M;this.suggestion=null;this.onVideoDataChange("newdata",this.C.getVideoData());this.U(M,"videodatachange",
this.onVideoDataChange);this.K=new g.d({W:"div",N:"ytp-autonav-endscreen-upnext-container",L:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{W:"div",N:"ytp-autonav-endscreen-topbar-container",X:[{W:"div",N:"ytp-autonav-endscreen-upnext-header"},{W:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",Hv:"{{autoplayAlternativeHeader}}"}]},{W:"a",N:"ytp-autonav-endscreen-link-container",
L:{href:"{{url}}",target:N?U.ZQ:""},X:[{W:"div",N:"ytp-autonav-endscreen-upnext-thumbnail",L:{style:"{{background}}"},X:[{W:"div",L:{"aria-label":"{{timestamp}}"},aS:["ytp-autonav-timestamp"],Hv:"{{duration}}"},{W:"div",aS:["ytp-autonav-live-stamp"],Hv:"Live"},{W:"div",aS:["ytp-autonav-upcoming-stamp"],Hv:"Upcoming"}]},{W:"div",N:"ytp-autonav-endscreen-video-info",X:[{W:"div",N:"ytp-autonav-endscreen-premium-badge"},{W:"div",N:"ytp-autonav-endscreen-upnext-title",Hv:"{{title}}"},{W:"div",N:"ytp-autonav-endscreen-upnext-author",
Hv:"{{author}}"},{W:"div",N:"ytp-autonav-view-and-date",Hv:"{{views_and_publish_time}}"},{W:"div",N:"ytp-autonav-author-and-view",Hv:"{{author_and_views}}"}]}]}]});g.D(this,this.K);this.K.IS(this.container.element);N||this.U(this.K.Bv("ytp-autonav-endscreen-link-container"),"click",this.Sw);this.C.createClientVe(this.container.element,this,115127);this.C.createClientVe(this.K.Bv("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.d({W:"button",N:"ytp-autonav-endscreen-upnext-header-close-button",
L:{"aria-label":"Cancel autoplay"}});g.D(this,this.closeButton);M.G("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.u0,this),this.C.createClientVe(this.closeButton.element,this,115129),this.K.Bv("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.d({W:"div",N:"ytp-autonav-overlay"});g.D(this,this.overlay);this.overlay.IS(this.container.element);this.A=new g.d({W:"div",N:"ytp-autonav-endscreen-button-container"});g.D(this,
this.A);this.A.IS(this.container.element);this.cancelButton=new g.d({W:"button",aS:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],L:{"aria-label":"Cancel autoplay"},Hv:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.IS(this.A.element);this.cancelButton.listen("click",this.u0,this);this.C.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.d({W:"a",aS:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],L:{href:"{{url}}",role:"button","aria-label":"Play next video"},Hv:"Play Now"});g.D(this,this.playButton);this.playButton.IS(this.A.element);this.playButton.listen("click",this.Sw,this);this.C.createServerVe(this.playButton.element,this.playButton,!0);(U=this.C.getVideoData())&&ZdG(this,U);this.D=new g.Fy(()=>{c2(this)},500);
g.D(this,this.D);this.b0();this.U(M,"autonavvisibility",this.b0)}Y(M){this.suggestion!==M&&(this.suggestion=M,g.f2(this.K,M),this.playButton.updateValue("url",this.suggestion.TA()),Sk(this))}Z(){return this.V>0}B(){this.Z()||(this.V=Date.now(),c2(this),Cin(this.C,w9(this)),g.KO(this.C.getRootNode(),"countdown-running",this.Z()))}S(){this.O();c2(this);var M=this.K.Bv("ytp-autonav-endscreen-upnext-header");M&&g.Ea(M,"Up next")}O(){this.Z()&&(this.D.stop(),this.V=0)}select(M=!1){this.C.nextVideo(!1,
M);this.O()}Sw(M){g.wg(M,this.C)&&(M.currentTarget===this.playButton.element?this.C.logClick(this.playButton.element):M.currentTarget===this.K.Bv("ytp-autonav-endscreen-link-container")&&(M=this.K.Bv("ytp-autonav-endscreen-link-container"),this.C.logVisibility(M,!0),this.C.logClick(M)),this.ZQ?(g.zS(this.C,"innertubeCommand",this.ZQ),this.O()):this.select())}u0(){this.C.logClick(this.cancelButton.element);g.uZ(this.C,!0);this.cancelCommand&&g.zS(this.C,"innertubeCommand",this.cancelCommand)}onVideoDataChange(M,
U){ZdG(this,U);this.cancelCommand=U.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}b0(){var M=this.C.GW();this.PV!==M&&this.kN(M);Sk(this);this.C.logVisibility(this.container.element,M);this.C.logVisibility(this.cancelButton.element,M);this.C.logVisibility(this.K.Bv("ytp-autonav-endscreen-link-container"),M);this.C.logVisibility(this.playButton.element,M)}yK(M){return M.width<400||M.height<459}};var P2=class extends g.d{constructor(M,U){super({W:"div",aS:["html5-endscreen","ytp-player-content",U||"base-endscreen"]});this.created=!1;this.player=M}create(){this.created=!0}destroy(){this.created=!1}D(){return!1}GW(){return!1}ZQ(){return!1}};var DgJ=class extends g.d{constructor(M){super({W:"div",aS:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},X:[{W:"div",N:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{W:"span",N:"ytp-upnext-top",X:[{W:"span",N:"ytp-upnext-header",Hv:"Up Next"},{W:"span",N:"ytp-upnext-title",Hv:"{{title}}"},{W:"span",N:"ytp-upnext-author",Hv:"{{author}}"}]},{W:"a",N:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},X:[{W:"svg",L:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},X:[{W:"circle",N:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{W:"circle",N:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{W:"path",N:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{W:"span",N:"ytp-upnext-bottom",X:[{W:"span",N:"ytp-upnext-cancel"},
{W:"span",N:"ytp-upnext-paused",Hv:"Autoplay is paused"}]}]});this.api=M;this.cancelButton=null;this.d6=this.Bv("ytp-svg-autoplay-ring");this.D=this.notification=this.K=this.suggestion=null;this.ZQ=new g.Fy(this.A,5E3,this);this.V=0;var U=this.Bv("ytp-upnext-cancel");this.cancelButton=new g.d({W:"button",aS:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},Hv:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.listen("click",this.u0,this);this.cancelButton.IS(U);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.D(this,this.ZQ);this.api.createClientVe(this.element,this,18788);U=this.Bv("ytp-upnext-autoplay-icon");this.U(U,"click",this.Sw);this.api.createClientVe(U,this,115130);this.b0();this.U(M,"autonavvisibility",this.b0);this.U(M,"mdxnowautoplaying",this.ML);this.U(M,"mdxautoplaycanceled",this.sM);g.KO(this.element,"ytp-upnext-mobile",this.api.J().O)}A(){this.notification&&(this.ZQ.stop(),this.Ds(this.D),this.D=null,this.notification.close(),
this.notification=null)}Y(M){this.suggestion=M;g.f2(this,M,"hqdefault.jpg")}b0(){this.kN(this.api.GW());this.api.logVisibility(this.element,this.api.GW());this.api.logVisibility(this.Bv("ytp-upnext-autoplay-icon"),this.api.GW());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.GW())}Wv(){window.focus();this.A()}B(M){this.Z()||(g.GH("a11y-announce",`Up Next ${this.suggestion.title}`),this.V=(0,g.u)(),this.K=new g.Fy(()=>{yE(this,M)},25),yE(this,M),Cin(this.api,aHF(this,
M)));
g.Tu(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}Z(){return!!this.K}isCasting(){return this.api.getPresentingPlayerType()===3}S(){this.O();this.V=(0,g.u)();yE(this);g.Gu(this.element,"ytp-upnext-autoplay-paused")}O(){this.Z()&&(this.K.dispose(),this.K=null)}select(M=!1){if(this.api.J().G("autonav_notifications")&&M&&window.Notification&&typeof document.hasFocus==="function"){let U=Notification.permission;U==="default"?Notification.requestPermission():U!=="granted"||document.hasFocus()||
(this.A(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.C3()}),this.D=this.U(this.notification,"click",this.Wv),this.ZQ.start())}this.O();this.api.nextVideo(!1,M)}Sw(M){!g.yA(this.cancelButton.element,M.target)&&g.wg(M,this.api)&&(this.api.GW()&&this.api.logClick(this.Bv("ytp-upnext-autoplay-icon")),this.select())}u0(){this.api.GW()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.uZ(this.api,!0)}ML(M){this.isCasting();this.show();
this.B(M)}sM(){this.isCasting();this.O();this.hide()}zS(){this.O();this.A();super.zS()}};var zGJ=class extends P2{constructor(M){super(M,"videowall-endscreen");this.C=M;this.stills=[];this.S=this.videoData=null;this.B=this.Y=!1;this.b0=null;g.Gu(this.element,"modern-videowall-endscreen");this.K=new g.Zv(this);g.D(this,this.K);this.A=new g.Fy(()=>{g.Gu(this.element,"ytp-show-tiles")},0);
g.D(this,this.A);this.table=new g.ky({W:"div",N:"ytp-modern-endscreen-content"});g.D(this,this.table);this.table.IS(this.element);M.getVideoData().Mh?this.Z=new W2(M):this.Z=new DgJ(M);g.D(this,this.Z);g.tE(this.player,this.Z.element,4);M.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var M=this.player.getVideoData();M&&(this.videoData=M);this.O();this.K.U(this.player,"appresize",this.O);this.K.U(this.player,"onVideoAreaChange",this.O);this.K.U(this.player,"videodatachange",
this.onVideoDataChange);this.K.U(this.player,"autonavchange",this.V);this.K.U(this.player,"onAutonavCancelled",this.u0);M=this.videoData.autonavState;M!==this.b0&&this.V(M,!1);this.K.U(this.element,"transitionend",this.Sw)}destroy(){this.K.K();g.Dr(this.stills);this.stills=[];super.destroy();g.Tu(this.element,"ytp-show-tiles");this.A.stop();this.b0=this.videoData.autonavState}D(){return this.videoData?.aP||this.videoData.autonavState!==1}show(){var M=this.PV;super.show();g.Tu(this.element,"ytp-show-tiles");
this.player.J().O?g.qH(this.A):this.A.start();(this.B||this.S&&this.S!==this.videoData.clientPlaybackNonce)&&g.uZ(this.player,!1);Eh(this)?(LM(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||piJ(this.player.zu())&&this.player.G("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.B():this.videoData.autonavState===3&&this.Z.S()):(g.uZ(this.player,!0),LM(this));M!==this.PV&&this.player.logVisibility(this.element,!0)}hide(){var M=this.PV;super.hide();this.Z.S();LM(this);
M!==this.PV&&this.player.logVisibility(this.element,!1)}Sw(M){M.target===this.element&&this.O()}O(){var M=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.OM()];if(M.length){var U=this.C.jd(!0,this.C.isFullscreen()),N=Math.floor((U.width-64+16)/(g.nF(U.width*.27,250,450)+16));U=Math.min(3,Math.floor((U.height-64)/((U.width-64-(N-1)*16)/N*.5625+70)));g.ru(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Gu(this.element,`ytp-modern-endscreen-limit-rows-${U}`);g.KO(this.element,"ytp-modern-endscreen-single-item",N===1);g.KO(this.element,"ytp-modern-endscreen-row-0",U===0);N=this.table.element;N.ariaLive="polite";this.Z.Y(this.videoData.OM());this.Z instanceof W2&&Sk(this.Z);g.KO(this.element,"ytp-endscreen-takeover",Eh(this));LM(this);U=0;N.ariaBusy="true";var m=M.length;for(let O=0;O<m;O++){let v=O%m,Y=this.stills[O];Y||(Y=new g.Xmi(this.player),this.stills[O]=Y,N.appendChild(Y.element));g.EDk(Y,
M[v]);U++}this.stills.length=U}}onVideoDataChange(){var M=this.player.getVideoData({playerType:1});this.videoData!==M&&(M?.OM()?(this.videoData=M,this.O()):this.player.FJ("missg",{vid:M?.videoId||"",cpn:M?.clientPlaybackNonce||""}))}ZQ(){return this.Z.Z()}V(M,U=!1){var N=this.videoData?.aP;if(M===1){if(!N||U)this.B=!1,this.S=this.videoData.clientPlaybackNonce;this.Z.O();this.PV&&this.O()}else this.B=!0,this.PV&&Eh(this)&&(M===2?this.Z.B():M===3&&this.Z.S())}u0(M){if(M){for(M=0;M<this.stills.length;M++)this.C.logVisibility(this.stills[M].element,
!0);this.V(1,!0)}else this.S=null,this.B=!1;this.O()}GW(){return this.PV&&Eh(this)}};var nbj=class extends g.d{constructor(M){var U=M.J(),N=g.n9||g.Gm?{style:"will-change: opacity"}:void 0,m=U.S,O=["ytp-videowall-still"];U.O&&O.push("ytp-videowall-show-text");super({W:"a",aS:O,L:{href:"{{url}}",target:m?U.ZQ:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{W:"div",N:"ytp-videowall-still-image",L:{style:"{{background}}"}},{W:"span",N:"ytp-videowall-still-info",L:{"aria-hidden":"true"},X:[{W:"span",N:"ytp-videowall-still-info-bg",
X:[{W:"span",N:"ytp-videowall-still-info-content",L:N,X:[{W:"span",N:"ytp-videowall-still-info-title",Hv:"{{title}}"},{W:"span",N:"ytp-videowall-still-info-author",Hv:"{{author_and_views}}"},{W:"span",N:"ytp-videowall-still-info-live",Hv:"Live"},{W:"span",N:"ytp-videowall-still-info-duration",Hv:"{{duration}}"}]}]}]},{W:"span",aS:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},X:[{W:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{W:"span",
N:"ytp-videowall-still-listlabel-length",X:[" (",{W:"span",Hv:"{{playlist_length}}"},")"]}]},{W:"span",aS:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},X:[{W:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{W:"span",N:"ytp-videowall-still-listlabel-length",Hv:" (50+)"}]}]});this.suggestion=null;this.K=m;this.api=M;this.Z=new g.Zv(this);g.D(this,this.Z);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.Z.U(M,"videodatachange",
this.onVideoDataChange);M.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.UE(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.w2||void 0)&&this.api.logClick(this.element)}onClick(M){if(g.Rk(this.api.J())&&this.api.G("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let U=this.suggestion.TA(),N={};g.iZ(this.api,N);U=g.up(U,N);g.lo(U,this.api,M)}else g.wg(M,this.api,
this.K,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(M){switch(M.keyCode){case 13:case 32:M.defaultPrevented||(this.select(),M.preventDefault())}}onVideoDataChange(){var M=this.api.getVideoData(),U=this.api.J();this.K=M.nP?!1:U.S}};var hGO=class extends P2{constructor(M){super(M,"videowall-endscreen");this.C=M;this.S=0;this.stills=[];this.B=this.videoData=null;this.A=this.b0=!1;this.u0=null;this.O=new g.Zv(this);g.D(this,this.O);this.V=new g.Fy(()=>{g.Gu(this.element,"ytp-show-tiles")},0);
g.D(this,this.V);var U=new g.d({W:"button",aS:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},X:[g.x2()]});g.D(this,U);U.IS(this.element);U.listen("click",this.ML,this);this.table=new g.ky({W:"div",N:"ytp-endscreen-content"});g.D(this,this.table);this.table.IS(this.element);U=new g.d({W:"button",aS:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"Next"},X:[g.QL()]});g.D(this,U);U.IS(this.element);U.listen("click",this.d6,this);M.getVideoData().Mh?this.Z=new W2(M):this.Z=new DgJ(M);
g.D(this,this.Z);g.tE(this.player,this.Z.element,4);M.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var M=this.player.getVideoData();M&&(this.videoData=M);this.K();this.O.U(this.player,"appresize",this.K);this.O.U(this.player,"onVideoAreaChange",this.K);this.O.U(this.player,"videodatachange",this.onVideoDataChange);this.O.U(this.player,"autonavchange",this.Y);this.O.U(this.player,"onAutonavCancelled",this.Sw);M=this.videoData.autonavState;M!==this.u0&&this.Y(M,!1);this.O.U(this.element,
"transitionend",this.sM)}destroy(){this.O.K();g.Dr(this.stills);this.stills=[];super.destroy();g.Tu(this.element,"ytp-show-tiles");this.V.stop();this.u0=this.videoData.autonavState}D(){return this.videoData?.aP||this.videoData?.autonavState!==1}show(){var M=this.PV;super.show();g.Tu(this.element,"ytp-show-tiles");this.player.J().O?g.qH(this.V):this.V.start();(this.A||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.uZ(this.player,!1);ek(this)?(A8(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||piJ(this.player.zu())&&this.player.G("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.B():this.videoData.autonavState===3&&this.Z.S()):(g.uZ(this.player,!0),A8(this));M!==this.PV&&this.player.logVisibility(this.element,!0)}hide(){var M=this.PV;super.hide();this.Z.S();A8(this);M!==this.PV&&this.player.logVisibility(this.element,!1)}sM(M){M.target===this.element&&this.K()}K(){var M=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.OM()];if(M.length){g.Gu(this.element,
"ytp-endscreen-paginate");var U=this.C.jd(!0,this.C.isFullscreen()),N=g.Kf(this.C);N&&(N=N.zt()?48:32,U.width-=N*2);var m=U.width/U.height,O=96/54,v=N=2,Y=Math.max(U.width/96,2),w=Math.max(U.height/54,2),l=M.length;var c=l*4;for(c-=4;c>0&&(N<Y||v<w);){var S=N/2,y=v/2,E=N<=Y-2&&c>=y*4,L=v<=w-2&&c>=S*4;if((S+1)/y*O/m>m/(S/(y+1)*O)&&L)c-=S*4,v+=2;else if(E)c-=y*4,N+=2;else if(L)c-=S*4,v+=2;else break}O=!1;c>=12&&l*4-c<=6&&(v>=4||N>=4)&&(O=!0);c=N*96;Y=v*54;m=c/Y<m?U.height/Y:U.width/c;m=Math.min(m,2);
c=Math.floor(Math.min(U.width,c*m));Y=Math.floor(Math.min(U.height,Y*m));U=this.table.element;U.ariaLive="polite";g.dr(U,c,Y);g.KK(U,{marginLeft:`${c/-2}px`,marginTop:`${Y/-2}px`});this.Z.Y(this.videoData.OM());this.Z instanceof W2&&Sk(this.Z);g.KO(this.element,"ytp-endscreen-takeover",ek(this));A8(this);c+=4;Y+=4;m=0;U.ariaBusy="true";for(w=0;w<N;w++)for(S=0;S<v;S++)if(E=m,L=0,O&&w>=N-2&&S>=v-2?L=1:S%2===0&&w%2===0&&(S<2&&w<2?S===0&&w===0&&(L=2):L=2),E=g.hY(E+this.S,l),L!==0){y=this.stills[m];y||
(y=new nbj(this.player),this.stills[m]=y,U.appendChild(y.element));var C=Math.floor(Y*S/v);let q=Math.floor(c*w/N),r=Math.floor(Y*(S+L)/v)-C-4,k=Math.floor(c*(w+L)/N)-q-4;g.I8(y.element,q,C);g.dr(y.element,k,r);g.KK(y.element,"transitionDelay",(S+w)/20+"s");g.KO(y.element,"ytp-videowall-still-mini",L===1);g.KO(y.element,"ytp-videowall-still-large",L>2);L=Math.max(k,r);g.KO(y.element,"ytp-videowall-still-round-large",L>=256);g.KO(y.element,"ytp-videowall-still-round-medium",L>96&&L<256);g.KO(y.element,
"ytp-videowall-still-round-small",L<=96);E=M[E];y.suggestion!==E&&(y.suggestion=E,L=y.api.J(),C=g.h1(y.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.f2(y,E,C),g.Rk(L)&&!y.api.G("web_player_log_click_before_generating_ve_conversion_params")&&(L=E.TA(),C={},g.GS(y.api,"addEmbedsConversionTrackingParams",[C]),L=g.up(L,C),y.updateValue("url",L)),(E=(E=E.sessionData)&&E.itct)&&y.api.setTrackingParams(y.element,E));m++}U.ariaBusy="false";g.KO(this.element,"ytp-endscreen-paginate",
m<l);for(M=this.stills.length-1;M>=m;M--)N=this.stills[M],g.SG(N.element),g.q2(N);this.stills.length=m}}onVideoDataChange(){var M=this.player.getVideoData({playerType:1});this.videoData!==M&&(M?.OM()?(this.S=0,this.videoData=M,this.K()):this.player.FJ("missg",{vid:M?.videoId||"",cpn:M?.clientPlaybackNonce||""}))}d6(){this.S+=this.stills.length;this.K()}ML(){this.S-=this.stills.length;this.K()}ZQ(){return this.Z.Z()}Y(M,U=!1){var N=this.videoData?.aP;if(M===1){if(!N||U)this.A=!1,this.B=this.videoData.clientPlaybackNonce;
this.Z.O();this.PV&&this.K()}else this.A=!0,this.PV&&ek(this)&&(M===2?this.Z.B():M===3&&this.Z.S())}Sw(M){if(M){for(M=0;M<this.stills.length;M++)this.C.logVisibility(this.stills[M].element,!0);this.Y(1,!0)}else this.B=null,this.A=!1;this.K()}GW(){return this.PV&&ek(this)}};var GaF=class extends g.d{constructor(M){super({W:"button",aS:["ytp-watch-on-youtube-button","ytp-button"],Hv:"{{content}}"});this.C=M;this.buttonType=this.buttonType=1;this.Z();this.buttonType===2&&g.Gu(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Z);this.kN(!0)}Z(){switch(this.buttonType){case 1:var M="Watch again on YouTube";var U=156915;break;case 2:M="Continue watching on YouTube";U=156942;break;default:M="Continue watching on YouTube",
U=156942}this.update({content:M});this.C.hasVe(this.element)&&this.C.destroyVe(this.element);this.C.createClientVe(this.element,this,U)}onClick(M){this.C.G("web_player_log_click_before_generating_ve_conversion_params")&&this.C.logClick(this.element);g.lo(this.getVideoUrl(),this.C,M);this.C.G("web_player_log_click_before_generating_ve_conversion_params")||this.C.logClick(this.element)}getVideoUrl(){var M=!0;switch(this.buttonType){case 1:M=!0;break;case 2:M=!1}M=this.C.getVideoUrl(M,!1,!1,!0);var U=
this.C.J();if(g.Rk(U)){let N={};g.Rk(U)&&g.GS(this.C,"addEmbedsConversionTrackingParams",[N]);M=g.up(M,N)}return M}logVisibility(){this.C.logVisibility(this.element,this.PV&&this.OM)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}RP(M){super.RP(M);this.logVisibility()}};var jqJ=class extends P2{constructor(M){super(M,"watch-again-on-youtube-endscreen");this.watchButton=new GaF(M);g.D(this,this.watchButton);this.watchButton.IS(this.element);g.S9A(M)&&(this.Z=new g.pGD(M),g.D(this,this.Z),this.K=new g.d({W:"div",aS:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],L:{tabIndex:"-1"},X:[this.Z]}),g.D(this,this.K),this.Z.IS(this.K.element),this.K.IS(this.element));M.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.Z?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let U=this.K;if(U){var M=this.Z.hasSuggestions();g.KO(this.element,"ytp-shorts-branded-ui",M);M?U.show():U.hide()}g.Kf(this.player)?.vR(!0);this.player.logVisibility(this.element,!0);this.watchButton.RP(!0)}}hide(){super.hide();g.Kf(this.player)?.vR(!1);this.player.logVisibility(this.element,!1);this.watchButton.RP(!1)}};g.l0("endscreen",class extends g.Qz{constructor(M){super(M);this.endScreen=null;this.Z=this.K=!1;this.listeners=new g.Zv(this);g.D(this,this.listeners);var U=M.J();M.isEmbedsShortsMode()?this.endScreen=new jqJ(M):FNj(M)?(this.K=!0,BlD(this),U.G("delhi_modern_endscreen")?this.endScreen=new zGJ(M):this.endScreen=new hGO(M)):this.endScreen=new P2(M);g.D(this,this.endScreen);g.tE(M,this.endScreen.element,4);qWF(this);this.listeners.U(M,"videodatachange",this.onVideoDataChange,this);this.listeners.U(M,
g.uV("endscreen"),N=>{this.onCueRangeEnter(N)});
this.listeners.U(M,g.Ix("endscreen"),N=>{this.onCueRangeExit(N)})}Ip(){var M=this.player.getVideoData(),U=M.mutedAutoplay&&(M.limitedPlaybackDurationInSeconds>0||M.endSeconds>0||M.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!U)return!0;var N=!(!M?.OM()&&!M?.suggestions?.length);N=!FNj(this.player)||N;var m=M.rI,O=this.player.cq();return(N||!!M?.aP)&&!m&&!O&&!U}GW(){return this.endScreen.GW()}TZ(){return this.GW()?this.endScreen.ZQ():!1}zS(){this.player.sa("endscreen");super.zS()}load(){{let N=this.player.getVideoData(),m=N.transitionEndpointAtEndOfStream;if(m&&m.videoId){var M=this.player.WV().HH.get("heartbeat");var U=N.OM();!U||m.videoId!==U.videoId||N.SM?(this.player.UE(m.videoId,
void 0,void 0,!0,!0,m),M&&M.OL("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),M=!0):M=!1}else M=!1}M||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(M){this.Ip()&&(this.endScreen.created||this.endScreen.create(),M.getId()==="load"&&this.load())}onCueRangeExit(M){M.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){qWF(this);this.K&&BlD(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new hGO(this.player),g.D(this,this.endScreen),g.tE(this.player,this.endScreen.element,4))}});})(_yt_player);
