package com.itinera.app.ui.components

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowDropDown
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp

data class Country(
    val name: String,
    val code: String,
    val dialCode: String,
    val flag: String
)

val countries = listOf(
    Country("Afghanistan", "AF", "+93", "🇦🇫"),
    Country("Albania", "AL", "+355", "🇦🇱"),
    Country("Algeria", "DZ", "+213", "🇩🇿"),
    Country("American Samoa", "AS", "+1", "🇦🇸"),
    Country("Andorra", "AD", "+376", "🇦🇩"),
    Country("Angola", "AO", "+244", "🇦🇴"),
    Country("Anguilla", "AI", "+1", "🇦🇮"),
    Country("Antarctica", "AQ", "+672", "🇦🇶"),
    Country("Antigua and Barbuda", "AG", "+1", "🇦🇬"),
    Country("Argentina", "AR", "+54", "🇦🇷"),
    Country("Armenia", "AM", "+374", "🇦🇲"),
    Country("Aruba", "AW", "+297", "🇦🇼"),
    Country("Australia", "AU", "+61", "🇦🇺"),
    Country("Austria", "AT", "+43", "🇦🇹"),
    Country("Azerbaijan", "AZ", "+994", "🇦🇿"),
    Country("Bahamas", "BS", "+1", "🇧🇸"),
    Country("Bahrain", "BH", "+973", "🇧🇭"),
    Country("Bangladesh", "BD", "+880", "🇧🇩"),
    Country("Barbados", "BB", "+1", "🇧🇧"),
    Country("Belarus", "BY", "+375", "🇧🇾"),
    Country("Belgium", "BE", "+32", "🇧🇪"),
    Country("Belize", "BZ", "+501", "🇧🇿"),
    Country("Benin", "BJ", "+229", "🇧🇯"),
    Country("Bermuda", "BM", "+1", "🇧🇲"),
    Country("Bhutan", "BT", "+975", "🇧🇹"),
    Country("Bolivia", "BO", "+591", "🇧🇴"),
    Country("Bosnia and Herzegovina", "BA", "+387", "🇧🇦"),
    Country("Botswana", "BW", "+267", "🇧🇼"),
    Country("Brazil", "BR", "+55", "🇧🇷"),
    Country("British Indian Ocean Territory", "IO", "+246", "🇮🇴"),
    Country("British Virgin Islands", "VG", "+1", "🇻🇬"),
    Country("Brunei", "BN", "+673", "🇧🇳"),
    Country("Bulgaria", "BG", "+359", "🇧🇬"),
    Country("Burkina Faso", "BF", "+226", "🇧🇫"),
    Country("Burundi", "BI", "+257", "🇧🇮"),
    Country("Cambodia", "KH", "+855", "🇰🇭"),
    Country("Cameroon", "CM", "+237", "🇨🇲"),
    Country("Canada", "CA", "+1", "🇨🇦"),
    Country("Cape Verde", "CV", "+238", "🇨🇻"),
    Country("Cayman Islands", "KY", "+1", "🇰🇾"),
    Country("Central African Republic", "CF", "+236", "🇨🇫"),
    Country("Chad", "TD", "+235", "🇹🇩"),
    Country("Chile", "CL", "+56", "🇨🇱"),
    Country("China", "CN", "+86", "🇨🇳"),
    Country("Christmas Island", "CX", "+61", "🇨🇽"),
    Country("Cocos Islands", "CC", "+61", "🇨🇨"),
    Country("Colombia", "CO", "+57", "🇨🇴"),
    Country("Comoros", "KM", "+269", "🇰🇲"),
    Country("Cook Islands", "CK", "+682", "🇨🇰"),
    Country("Costa Rica", "CR", "+506", "🇨🇷"),
    Country("Croatia", "HR", "+385", "🇭🇷"),
    Country("Cuba", "CU", "+53", "🇨🇺"),
    Country("Curacao", "CW", "+599", "🇨🇼"),
    Country("Cyprus", "CY", "+357", "🇨🇾"),
    Country("Czech Republic", "CZ", "+420", "🇨🇿"),
    Country("Democratic Republic of the Congo", "CD", "+243", "🇨🇩"),
    Country("Denmark", "DK", "+45", "🇩🇰"),
    Country("Djibouti", "DJ", "+253", "🇩🇯"),
    Country("Dominica", "DM", "+1", "🇩🇲"),
    Country("Dominican Republic", "DO", "+1", "🇩🇴"),
    Country("East Timor", "TL", "+670", "🇹🇱"),
    Country("Ecuador", "EC", "+593", "🇪🇨"),
    Country("Egypt", "EG", "+20", "🇪🇬"),
    Country("El Salvador", "SV", "+503", "🇸🇻"),
    Country("Equatorial Guinea", "GQ", "+240", "🇬🇶"),
    Country("Eritrea", "ER", "+291", "🇪🇷"),
    Country("Estonia", "EE", "+372", "🇪🇪"),
    Country("Ethiopia", "ET", "+251", "🇪🇹"),
    Country("Falkland Islands", "FK", "+500", "🇫🇰"),
    Country("Faroe Islands", "FO", "+298", "🇫🇴"),
    Country("Fiji", "FJ", "+679", "🇫🇯"),
    Country("Finland", "FI", "+358", "🇫🇮"),
    Country("France", "FR", "+33", "🇫🇷"),
    Country("French Guiana", "GF", "+594", "🇬🇫"),
    Country("French Polynesia", "PF", "+689", "🇵🇫"),
    Country("Gabon", "GA", "+241", "🇬🇦"),
    Country("Gambia", "GM", "+220", "🇬🇲"),
    Country("Georgia", "GE", "+995", "🇬🇪"),
    Country("Germany", "DE", "+49", "🇩🇪"),
    Country("Ghana", "GH", "+233", "🇬🇭"),
    Country("Gibraltar", "GI", "+350", "🇬🇮"),
    Country("Greece", "GR", "+30", "🇬🇷"),
    Country("Greenland", "GL", "+299", "🇬🇱"),
    Country("Grenada", "GD", "+1", "🇬🇩"),
    Country("Guadeloupe", "GP", "+590", "🇬🇵"),
    Country("Guam", "GU", "+1", "🇬🇺"),
    Country("Guatemala", "GT", "+502", "🇬🇹"),
    Country("Guernsey", "GG", "+44", "🇬🇬"),
    Country("Guinea", "GN", "+224", "🇬🇳"),
    Country("Guinea-Bissau", "GW", "+245", "🇬🇼"),
    Country("Guyana", "GY", "+592", "🇬🇾"),
    Country("Haiti", "HT", "+509", "🇭🇹"),
    Country("Honduras", "HN", "+504", "🇭🇳"),
    Country("Hong Kong", "HK", "+852", "🇭🇰"),
    Country("Hungary", "HU", "+36", "🇭🇺"),
    Country("Iceland", "IS", "+354", "🇮🇸"),
    Country("India", "IN", "+91", "🇮🇳"),
    Country("Indonesia", "ID", "+62", "🇮🇩"),
    Country("Iran", "IR", "+98", "🇮🇷"),
    Country("Iraq", "IQ", "+964", "🇮🇶"),
    Country("Ireland", "IE", "+353", "🇮🇪"),
    Country("Isle of Man", "IM", "+44", "🇮🇲"),
    Country("Israel", "IL", "+972", "🇮🇱"),
    Country("Italy", "IT", "+39", "🇮🇹"),
    Country("Ivory Coast", "CI", "+225", "🇨🇮"),
    Country("Jamaica", "JM", "+1", "🇯🇲"),
    Country("Japan", "JP", "+81", "🇯🇵"),
    Country("Jersey", "JE", "+44", "🇯🇪"),
    Country("Jordan", "JO", "+962", "🇯🇴"),
    Country("Kazakhstan", "KZ", "+7", "🇰🇿"),
    Country("Kenya", "KE", "+254", "🇰🇪"),
    Country("Kiribati", "KI", "+686", "🇰🇮"),
    Country("Kosovo", "XK", "+383", "🇽🇰"),
    Country("Kuwait", "KW", "+965", "🇰🇼"),
    Country("Kyrgyzstan", "KG", "+996", "🇰🇬"),
    Country("Laos", "LA", "+856", "🇱🇦"),
    Country("Latvia", "LV", "+371", "🇱🇻"),
    Country("Lebanon", "LB", "+961", "🇱🇧"),
    Country("Lesotho", "LS", "+266", "🇱🇸"),
    Country("Liberia", "LR", "+231", "🇱🇷"),
    Country("Libya", "LY", "+218", "🇱🇾"),
    Country("Liechtenstein", "LI", "+423", "🇱🇮"),
    Country("Lithuania", "LT", "+370", "🇱🇹"),
    Country("Luxembourg", "LU", "+352", "🇱🇺"),
    Country("Macau", "MO", "+853", "🇲🇴"),
    Country("Macedonia", "MK", "+389", "🇲🇰"),
    Country("Madagascar", "MG", "+261", "🇲🇬"),
    Country("Malawi", "MW", "+265", "🇲🇼"),
    Country("Malaysia", "MY", "+60", "🇲🇾"),
    Country("Maldives", "MV", "+960", "🇲🇻"),
    Country("Mali", "ML", "+223", "🇲🇱"),
    Country("Malta", "MT", "+356", "🇲🇹"),
    Country("Marshall Islands", "MH", "+692", "🇲🇭"),
    Country("Martinique", "MQ", "+596", "🇲🇶"),
    Country("Mauritania", "MR", "+222", "🇲🇷"),
    Country("Mauritius", "MU", "+230", "🇲🇺"),
    Country("Mayotte", "YT", "+262", "🇾🇹"),
    Country("Mexico", "MX", "+52", "🇲🇽"),
    Country("Micronesia", "FM", "+691", "🇫🇲"),
    Country("Moldova", "MD", "+373", "🇲🇩"),
    Country("Monaco", "MC", "+377", "🇲🇨"),
    Country("Mongolia", "MN", "+976", "🇲🇳"),
    Country("Montenegro", "ME", "+382", "🇲🇪"),
    Country("Montserrat", "MS", "+1", "🇲🇸"),
    Country("Morocco", "MA", "+212", "🇲🇦"),
    Country("Mozambique", "MZ", "+258", "🇲🇿"),
    Country("Myanmar", "MM", "+95", "🇲🇲"),
    Country("Namibia", "NA", "+264", "🇳🇦"),
    Country("Nauru", "NR", "+674", "🇳🇷"),
    Country("Nepal", "NP", "+977", "🇳🇵"),
    Country("Netherlands", "NL", "+31", "🇳🇱"),
    Country("Netherlands Antilles", "AN", "+599", "🇦🇳"),
    Country("New Caledonia", "NC", "+687", "🇳🇨"),
    Country("New Zealand", "NZ", "+64", "🇳🇿"),
    Country("Nicaragua", "NI", "+505", "🇳🇮"),
    Country("Niger", "NE", "+227", "🇳🇪"),
    Country("Nigeria", "NG", "+234", "🇳🇬"),
    Country("Niue", "NU", "+683", "🇳🇺"),
    Country("North Korea", "KP", "+850", "🇰🇵"),
    Country("Northern Mariana Islands", "MP", "+1", "🇲🇵"),
    Country("Norway", "NO", "+47", "🇳🇴"),
    Country("Oman", "OM", "+968", "🇴🇲"),
    Country("Pakistan", "PK", "+92", "🇵🇰"),
    Country("Palau", "PW", "+680", "🇵🇼"),
    Country("Palestine", "PS", "+970", "🇵🇸"),
    Country("Panama", "PA", "+507", "🇵🇦"),
    Country("Papua New Guinea", "PG", "+675", "🇵🇬"),
    Country("Paraguay", "PY", "+595", "🇵🇾"),
    Country("Peru", "PE", "+51", "🇵🇪"),
    Country("Philippines", "PH", "+63", "🇵🇭"),
    Country("Pitcairn", "PN", "+64", "🇵🇳"),
    Country("Poland", "PL", "+48", "🇵🇱"),
    Country("Portugal", "PT", "+351", "🇵🇹"),
    Country("Puerto Rico", "PR", "+1", "🇵🇷"),
    Country("Qatar", "QA", "+974", "🇶🇦"),
    Country("Republic of the Congo", "CG", "+242", "🇨🇬"),
    Country("Reunion", "RE", "+262", "🇷🇪"),
    Country("Romania", "RO", "+40", "🇷🇴"),
    Country("Russia", "RU", "+7", "🇷🇺"),
    Country("Rwanda", "RW", "+250", "🇷🇼"),
    Country("Saint Barthelemy", "BL", "+590", "🇧🇱"),
    Country("Saint Helena", "SH", "+290", "🇸🇭"),
    Country("Saint Kitts and Nevis", "KN", "+1", "🇰🇳"),
    Country("Saint Lucia", "LC", "+1", "🇱🇨"),
    Country("Saint Martin", "MF", "+590", "🇲🇫"),
    Country("Saint Pierre and Miquelon", "PM", "+508", "🇵🇲"),
    Country("Saint Vincent and the Grenadines", "VC", "+1", "🇻🇨"),
    Country("Samoa", "WS", "+685", "🇼🇸"),
    Country("San Marino", "SM", "+378", "🇸🇲"),
    Country("Sao Tome and Principe", "ST", "+239", "🇸🇹"),
    Country("Saudi Arabia", "SA", "+966", "🇸🇦"),
    Country("Senegal", "SN", "+221", "🇸🇳"),
    Country("Serbia", "RS", "+381", "🇷🇸"),
    Country("Seychelles", "SC", "+248", "🇸🇨"),
    Country("Sierra Leone", "SL", "+232", "🇸🇱"),
    Country("Singapore", "SG", "+65", "🇸🇬"),
    Country("Sint Maarten", "SX", "+1", "🇸🇽"),
    Country("Slovakia", "SK", "+421", "🇸🇰"),
    Country("Slovenia", "SI", "+386", "🇸🇮"),
    Country("Solomon Islands", "SB", "+677", "🇸🇧"),
    Country("Somalia", "SO", "+252", "🇸🇴"),
    Country("South Africa", "ZA", "+27", "🇿🇦"),
    Country("South Korea", "KR", "+82", "🇰🇷"),
    Country("South Sudan", "SS", "+211", "🇸🇸"),
    Country("Spain", "ES", "+34", "🇪🇸"),
    Country("Sri Lanka", "LK", "+94", "🇱🇰"),
    Country("Sudan", "SD", "+249", "🇸🇩"),
    Country("Suriname", "SR", "+597", "🇸🇷"),
    Country("Svalbard and Jan Mayen", "SJ", "+47", "🇸🇯"),
    Country("Swaziland", "SZ", "+268", "🇸🇿"),
    Country("Sweden", "SE", "+46", "🇸🇪"),
    Country("Switzerland", "CH", "+41", "🇨🇭"),
    Country("Syria", "SY", "+963", "🇸🇾"),
    Country("Taiwan", "TW", "+886", "🇹🇼"),
    Country("Tajikistan", "TJ", "+992", "🇹🇯"),
    Country("Tanzania", "TZ", "+255", "🇹🇿"),
    Country("Thailand", "TH", "+66", "🇹🇭"),
    Country("Togo", "TG", "+228", "🇹🇬"),
    Country("Tokelau", "TK", "+690", "🇹🇰"),
    Country("Tonga", "TO", "+676", "🇹🇴"),
    Country("Trinidad and Tobago", "TT", "+1", "🇹🇹"),
    Country("Tunisia", "TN", "+216", "🇹🇳"),
    Country("Turkey", "TR", "+90", "🇹🇷"),
    Country("Turkmenistan", "TM", "+993", "🇹🇲"),
    Country("Turks and Caicos Islands", "TC", "+1", "🇹🇨"),
    Country("Tuvalu", "TV", "+688", "🇹🇻"),
    Country("U.S. Virgin Islands", "VI", "+1", "🇻🇮"),
    Country("Uganda", "UG", "+256", "🇺🇬"),
    Country("Ukraine", "UA", "+380", "🇺🇦"),
    Country("United Arab Emirates", "AE", "+971", "🇦🇪"),
    Country("United Kingdom", "GB", "+44", "🇬🇧"),
    Country("United States", "US", "+1", "🇺🇸"),
    Country("Uruguay", "UY", "+598", "🇺🇾"),
    Country("Uzbekistan", "UZ", "+998", "🇺🇿"),
    Country("Vanuatu", "VU", "+678", "🇻🇺"),
    Country("Vatican", "VA", "+379", "🇻🇦"),
    Country("Venezuela", "VE", "+58", "🇻🇪"),
    Country("Vietnam", "VN", "+84", "🇻🇳"),
    Country("Wallis and Futuna", "WF", "+681", "🇼🇫"),
    Country("Western Sahara", "EH", "+212", "🇪🇭"),
    Country("Yemen", "YE", "+967", "🇾🇪"),
    Country("Zambia", "ZM", "+260", "🇿🇲"),
    Country("Zimbabwe", "ZW", "+263", "🇿🇼"),
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PhoneNumberField(
    value: String,
    onValueChange: (String) -> Unit,
    selectedCountry: Country,
    onCountrySelected: (Country) -> Unit,
    label: @Composable () -> Unit,
    shape: Shape,
    modifier: Modifier = Modifier,
) {
    var expanded by remember { mutableStateOf(false) }

    Row(modifier = modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        ExposedDropdownMenuBox(
            expanded = expanded,
            onExpandedChange = { expanded = !expanded },
            modifier = Modifier.width(145.dp)
        ) {
            OutlinedTextField(
                value = "${selectedCountry.dialCode} ${selectedCountry.code} ${selectedCountry.flag}",
                onValueChange = {},
                readOnly = true,
                enabled = false,
                trailingIcon = { Icon(Icons.Filled.ArrowDropDown, contentDescription = null) },
                shape = shape,
                singleLine = true,
                modifier = Modifier
                    .menuAnchor(ExposedDropdownMenuAnchorType.PrimaryNotEditable)
                    .fillMaxWidth(),
                colors = OutlinedTextFieldDefaults.colors(
                    disabledTextColor = MaterialTheme.colorScheme.onSurface,
                    disabledBorderColor = MaterialTheme.colorScheme.outline,
                    disabledTrailingIconColor = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f),
                ),
            )

            MaterialTheme(shapes = MaterialTheme.shapes.copy(extraSmall = RoundedCornerShape(16.dp))) {
                ExposedDropdownMenu(
                    expanded = expanded,
                    onDismissRequest = { expanded = false }
                ) {
                    countries.forEach { country ->
                        DropdownMenuItem(
                            text = { Text("(${country.dialCode}) ${country.name} ${country.flag}") },
                            onClick = {
                                onCountrySelected(country)
                                expanded = false
                            }
                        )
                    }
                }
            }
        }

        Spacer(Modifier.width(8.dp))

        OutlinedTextField(
            value = value,
            onValueChange = { input -> onValueChange(input.filter { it.isDigit() }) },
            placeholder = label,                // ⬅ CHANGED: placeholder, not label
            singleLine = true,
            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Phone),
            shape = shape,
            modifier = Modifier.weight(1f),
        )
    }
}
